from django.core.management.base import BaseCommand
from auth_app.security_models import AgentSecurityRule


class Command(BaseCommand):
    help = '初始化Agent安全防护规则'

    def handle(self, *args, **options):
        rules_data = [
            # ===== 提示词注入检测规则 =====
            {
                'name': '忽略之前的指令-Jailbreak检测',
                'rule_type': 'prompt_injection',
                'description': '检测典型的提示词注入攻击模式',
                'pattern': 'ignore|forget|disregard|previous instructions|you are now|act as|jailbreak|system prompt|override',
                'pattern_type': 'keyword',
                'severity': 'critical',
                'action': 'block',
                'is_enabled': True,
                'priority': 1,
            },
            {
                'name': '角色扮演攻击检测',
                'rule_type': 'prompt_injection',
                'description': '检测试图让AI扮演危险角色的攻击',
                'pattern': 'you are a hacker|you are an admin|you have full access|root access|sudo|elevated privileges',
                'pattern_type': 'keyword',
                'severity': 'high',
                'action': 'block',
                'is_enabled': True,
                'priority': 2,
            },
            {
                'name': '指令泄露攻击检测',
                'rule_type': 'prompt_injection',
                'description': '检测试图获取系统提示词或内部指令的攻击',
                'pattern': 'show me your prompt|what are your instructions|reveal your system prompt|print your configuration',
                'pattern_type': 'keyword',
                'severity': 'high',
                'action': 'block',
                'is_enabled': True,
                'priority': 3,
            },
            # ===== 敏感内容过滤规则 =====
            {
                'name': '暴力恐怖内容过滤',
                'rule_type': 'sensitive_content',
                'description': '过滤涉及暴力、恐怖主义的内容',
                'pattern': 'bomb|terrorist|kill everyone|mass shooting|attack|violence|harm people|weapon|explosive',
                'pattern_type': 'keyword',
                'severity': 'critical',
                'action': 'block',
                'is_enabled': True,
                'priority': 10,
            },
            {
                'name': '色情成人内容过滤',
                'rule_type': 'sensitive_content',
                'description': '过滤色情、成人内容',
                'pattern': 'porn|nude|sexually explicit|adult content|NSFW|xxx|erotic',
                'pattern_type': 'keyword',
                'severity': 'high',
                'action': 'block',
                'is_enabled': True,
                'priority': 11,
            },
            {
                'name': '政治敏感内容过滤',
                'rule_type': 'sensitive_content',
                'description': '过滤政治敏感、反动内容',
                'pattern': 'overthrow government|subversive activity|political extremism|separatist|terrorism support',
                'pattern_type': 'keyword',
                'severity': 'high',
                'action': 'warn',
                'is_enabled': True,
                'priority': 12,
            },
            {
                'name': '个人隐私信息脱敏（身份证/手机号）',
                'rule_type': 'sensitive_content',
                'description': '检测并脱敏身份证号、手机号等PII信息',
                'pattern': '\\d{15,18}|1[3-9]\\d{9}',
                'pattern_type': 'regex',
                'severity': 'medium',
                'action': 'mask',
                'is_enabled': True,
                'priority': 20,
                'metadata': {'mask_char': '*', 'keep_first_last': 4},
            },
            # ===== 工具调用权限规则 =====
            {
                'name': '禁止执行系统命令',
                'rule_type': 'tool_permission',
                'description': '限制Agent调用系统命令执行工具',
                'pattern': 'exec|shell_command|run_code|execute_script|os.system|subprocess',
                'pattern_type': 'keyword',
                'severity': 'critical',
                'action': 'block',
                'is_enabled': True,
                'priority': 30,
            },
            {
                'name': '限制危险SQL操作',
                'rule_type': 'tool_permission',
                'description': '限制Agent执行DELETE、DROP等危险SQL',
                'pattern': 'DROP|DELETE FROM|TRUNCATE|ALTER TABLE|GRANT|REVOKE',
                'pattern_type': 'keyword',
                'severity': 'critical',
                'action': 'block',
                'is_enabled': True,
                'priority': 31,
            },
            {
                'name': '限制系统关键文件写入',
                'rule_type': 'tool_permission',
                'description': '限制Agent修改系统关键文件',
                'pattern': '/etc/|C:\\\\Windows|System32|.env|config\\.json',
                'pattern_type': 'regex',
                'severity': 'high',
                'action': 'block',
                'is_enabled': True,
                'priority': 32,
            },
            # ===== 输入长度限制 =====
            {
                'name': '单次输入长度限制（10000字符）',
                'rule_type': 'input_length',
                'description': '限制单次输入最大长度为10000字符',
                'pattern': '10000',
                'pattern_type': 'regex',
                'severity': 'medium',
                'action': 'block',
                'is_enabled': True,
                'priority': 40,
                'metadata': {'max_length': 10000},
            },
            # ===== 输出内容过滤 =====
            {
                'name': '输出敏感信息过滤（API密钥/密码）',
                'rule_type': 'output_filter',
                'description': '过滤AI回复中的API密钥、密码等',
                'pattern': '(api[_-]?key|secret|password|token)\\s*[:=]\\s*[\'"][^\'"]+[\'"]|sk-[a-zA-Z0-9]{20,}',
                'pattern_type': 'regex',
                'severity': 'high',
                'action': 'mask',
                'is_enabled': True,
                'priority': 50,
                'metadata': {'mask_char': '*', 'mask_all': True},
            },
            # ===== API安全防护规则 (2026-05 安全扫描新增) =====
            {
                'name': '硬编码凭证检测',
                'rule_type': 'code_security',
                'description': '检测源代码中的硬编码API Key、Secret、Password',
                'pattern': '(sk-[a-zA-Z0-9]{20,}|AIza[a-zA-Z0-9_-]{35}|ghp_[a-zA-Z0-9]{36}|xox[bps]-[a-zA-Z0-9-]+)',
                'pattern_type': 'regex',
                'severity': 'critical',
                'action': 'block',
                'is_enabled': True,
                'priority': 60,
            },
            {
                'name': 'SQL注入攻击检测',
                'rule_type': 'injection',
                'description': "检测SQL注入攻击模式（UNION SELECT、OR 1=1、'; DROP等）",
                'pattern': "(\"\\s*(OR|AND)\\s+['\"]?\\d*['\"]?\\s*=\\s*['\"]?\\d*|'\\s*;\\s*(DROP|DELETE|INSERT|UPDATE|UNION|EXEC)|1\\s*=\\s*1\\s*(OR|AND)|--\\s*$|\\/\\*.*\\*\\/)",
                'pattern_type': 'regex',
                'severity': 'critical',
                'action': 'block',
                'is_enabled': True,
                'priority': 61,
            },
            {
                'name': 'XSS跨站脚本攻击检测',
                'rule_type': 'injection',
                'description': '检测XSS攻击向量（script标签、事件处理器、javascript:协议等）',
                'pattern': '<script[\\s>]|javascript\\s*:|on(load|error|click|mouse|focus|blur|key|touch|submit|change)\\s*=|<iframe|<object|<embed|expression\\s*\\(|vbscript:',
                'pattern_type': 'regex',
                'severity': 'critical',
                'action': 'block',
                'is_enabled': True,
                'priority': 62,
            },
            {
                'name': 'IDOR越权访问检测',
                'rule_type': 'access_control',
                'description': '检测可能的越权访问模式（遍历ID参数）',
                'pattern': 'id=\\d+(&id=\\d+){3,}',
                'pattern_type': 'regex',
                'severity': 'high',
                'action': 'warn',
                'is_enabled': True,
                'priority': 63,
                'metadata': {'check_ownership': True},
            },
            {
                'name': '暴力破解/频率异常检测',
                'rule_type': 'rate_limit',
                'description': '检测同一IP短时间内大量认证请求或API调用',
                'pattern': '',
                'pattern_type': 'keyword',
                'severity': 'high',
                'action': 'rate_limit',
                'is_enabled': True,
                'priority': 64,
                'metadata': {
                    'max_attempts_per_minute': 10,
                    'max_attempts_per_hour': 60,
                    'lockout_duration_minutes': 15,
                    'window_seconds': 60,
                },
            },
            {
                'name': '路径穿越攻击检测',
                'rule_type': 'injection',
                'description': '检测目录穿越攻击模式（../、..\\等）',
                'pattern': '\\.\\.[\\\\/]|%2e%2e[%2f/]|\\.\\.%2[fF]',
                'pattern_type': 'regex',
                'severity': 'critical',
                'action': 'block',
                'is_enabled': True,
                'priority': 65,
            },
            {
                'name': 'SSRF服务端请求伪造检测',
                'rule_type': 'injection',
                'description': '检测SSRF攻击（内网IP地址、云元数据端点等）',
                'pattern': '(169\\.254\\.(169\\.254|254\\.254)|10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|172\\.(1[6-9]|2\\d|3[01])\\.\\d{1,3}\\.\\d{1,3}|192\\.168\\.\\d{1,3}\\.\\d{1,3})|metadata\\.google\\.internal|169\\.254\\.169\\.254',
                'pattern_type': 'regex',
                'severity': 'critical',
                'action': 'block',
                'is_enabled': True,
                'priority': 66,
            },
            {
                'name': 'JWT Token安全检测',
                'rule_type': 'auth_security',
                'description': '检测异常的JWT Token使用模式（过期token、篡改token）',
                'pattern': 'eyJ[A-Za-z0-9-_]+\\.eyJ[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]{0,}',
                'pattern_type': 'regex',
                'severity': 'medium',
                'action': 'validate',
                'is_enabled': True,
                'priority': 67,
                'metadata': {'check_expiry': True, 'check_algorithm': 'HS256'},
            },
        ]

        created_count = 0
        for rule_data in rules_data:
            rule, created = AgentSecurityRule.objects.get_or_create(
                name=rule_data['name'],
                defaults=rule_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'[OK] Created: {rule.name}'))
            else:
                self.stdout.write(self.style.WARNING(f'[SKIP] Exists: {rule.name}'))

        self.stdout.write(self.style.SUCCESS(f'\n[DONE] Init complete! Created {created_count} rules. Total: {AgentSecurityRule.objects.count()}'))
