# Generated by Django 6.0.1 on 2026-06-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "p2p_app",
            "0003_rename_idx_result_accepted_shard_resul_shard_i_4eaecb_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain_type",
                    models.CharField(
                        choices=[
                            ("task_lifecycle", "任务生命周期链"),
                            ("execution_log", "执行日志链"),
                            ("security_events", "安全事件链"),
                            ("cost_tracking", "成本追踪链"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="链类型",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="事件类型"
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="前一节点哈希",
                    ),
                ),
                (
                    "current_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="当前节点哈希"
                    ),
                ),
                ("data_hash", models.CharField(max_length=64, verbose_name="数据哈希")),
                ("payload", models.JSONField(default=dict, verbose_name="事件载荷")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, verbose_name="元信息(IP/用户/时间戳等)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "审计链节点",
                "verbose_name_plural": "审计链节点",
                "db_table": "p2p_audit_chain",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chain_type", "-created_at"],
                        name="idx_audit_chain_time",
                    ),
                    models.Index(
                        fields=["chain_type", "event_type"],
                        name="idx_audit_chain_event",
                    ),
                    models.Index(fields=["current_hash"], name="idx_audit_chain_hash"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RateLimitRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limit_type",
                    models.CharField(
                        choices=[
                            ("user", "用户级"),
                            ("ip", "IP级"),
                            ("device", "设备指纹级"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        verbose_name="标识(user_id/ip/device_fp)",
                    ),
                ),
                ("window_start", models.DateTimeField(verbose_name="窗口开始时间")),
                (
                    "request_count",
                    models.IntegerField(default=1, verbose_name="请求次数"),
                ),
                (
                    "blocked",
                    models.BooleanField(default=False, verbose_name="是否被拦截"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "限流记录",
                "db_table": "p2p_rate_limit_record",
                "indexes": [
                    models.Index(
                        fields=["limit_type", "identifier", "-created_at"],
                        name="idx_rl_ident",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("critical", "严重"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth_failure", "认证失败"),
                            ("rate_limit_exceeded", "频率超限"),
                            ("injection_detected", "注入检测"),
                            ("blocked_request", "拦截请求"),
                            ("suspicious_activity", "可疑行为"),
                            ("access_granted", "正常访问"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="用户标识"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="设备指纹"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("message", models.TextField(verbose_name="事件描述")),
                ("details", models.JSONField(default=dict, verbose_name="详细信息")),
                ("risk_score", models.FloatField(default=0.0, verbose_name="风险评分")),
                (
                    "action_taken",
                    models.CharField(
                        default="none", max_length=20, verbose_name="采取动作"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发生时间"),
                ),
            ],
            options={
                "verbose_name": "安全事件日志",
                "verbose_name_plural": "安全事件日志",
                "db_table": "p2p_security_event_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["level", "-created_at"], name="idx_sec_level_time"
                    ),
                    models.Index(
                        fields=["category", "-created_at"], name="idx_sec_cat_time"
                    ),
                    models.Index(fields=["user_id"], name="idx_sec_user"),
                    models.Index(fields=["ip_address"], name="idx_sec_ip"),
                    models.Index(fields=["risk_score"], name="idx_sec_risk"),
                ],
            },
        ),
    ]
