# Generated by Django 6.0.1 on 2026-05-26 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_loginlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=50, verbose_name="模块")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "新增"),
                            ("update", "修改"),
                            ("delete", "删除"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="请求方法"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="请求URL"
                    ),
                ),
                (
                    "params",
                    models.TextField(blank=True, default="", verbose_name="请求参数"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="用户代理"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=10,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="执行消息"),
                ),
                ("duration", models.IntegerField(default=0, verbose_name="耗时(ms)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "rbac_operation_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(max_length=20, verbose_name="目标类型"),
                ),
                ("target_id", models.IntegerField(verbose_name="目标ID")),
                (
                    "target_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="目标名称"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assign_role", "分配角色"),
                            ("remove_role", "移除角色"),
                            ("assign_perm", "分配权限"),
                            ("remove_perm", "移除权限"),
                            ("create_role", "创建角色"),
                            ("update_role", "更新角色"),
                            ("delete_role", "删除角色"),
                            ("create_menu", "创建菜单"),
                            ("update_menu", "更新菜单"),
                            ("delete_menu", "删除菜单"),
                        ],
                        max_length=20,
                        verbose_name="操作动作",
                    ),
                ),
                (
                    "detail_before",
                    models.TextField(blank=True, default="", verbose_name="变更前内容"),
                ),
                (
                    "detail_after",
                    models.TextField(blank=True, default="", verbose_name="变更后内容"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限审计日志",
                "verbose_name_plural": "权限审计日志",
                "db_table": "rbac_permission_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="角色编码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "data_scope",
                    models.CharField(
                        choices=[
                            ("all", "全部数据"),
                            ("self", "仅本人数据"),
                            ("role", "本角色数据"),
                        ],
                        default="self",
                        max_length=10,
                        verbose_name="数据权限范围",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "db_table": "rbac_role",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="权限名称")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="权限标识"
                    ),
                ),
                (
                    "perm_type",
                    models.CharField(
                        choices=[("menu", "菜单"), ("button", "按钮"), ("api", "接口")],
                        default="menu",
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="路由路径"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="请求方法"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="组件路径"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="图标"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("visible", models.BooleanField(default=True, verbose_name="是否可见")),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="auth_app.permission",
                        verbose_name="上级权限",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permissions",
                        to="auth_app.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限",
                "verbose_name_plural": "权限",
                "db_table": "rbac_permission",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="菜单名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="菜单编码"
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("directory", "目录"),
                            ("menu", "菜单"),
                            ("button", "按钮"),
                        ],
                        default="menu",
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="路由路径"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="组件路径"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="图标"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("visible", models.BooleanField(default=True, verbose_name="是否显示")),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="auth_app.menu",
                        verbose_name="上级菜单",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menus",
                        to="auth_app.permission",
                        verbose_name="关联权限",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="menus",
                        to="auth_app.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单",
                "db_table": "rbac_menu",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
