# Generated by Django 6.0.1 on 2026-05-26 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_operationlog_permissionauditlog_role_permission_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("auditor", "auditor"),
                            ("verifier", "verifier"),
                            ("archiver", "archiver"),
                            ("judge", "judge"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="sort_order"),
                ),
                (
                    "short_desc",
                    models.CharField(
                        default="", max_length=200, verbose_name="short_desc"
                    ),
                ),
                ("full_desc", models.TextField(default="", verbose_name="full_desc")),
                (
                    "icon",
                    models.CharField(
                        default="RobotOutlined", max_length=50, verbose_name="icon"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2563EB", max_length=20, verbose_name="color"
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#EFF6FF", max_length=20, verbose_name="bg_color"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(default="", verbose_name="system_prompt"),
                ),
                (
                    "welcome_msg",
                    models.CharField(
                        default="", max_length=500, verbose_name="welcome_msg"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.7, verbose_name="temperature"),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=2000, verbose_name="max_tokens"),
                ),
                (
                    "allow_summary",
                    models.BooleanField(default=True, verbose_name="allow_summary"),
                ),
                (
                    "allow_analysis",
                    models.BooleanField(default=True, verbose_name="allow_analysis"),
                ),
                (
                    "allow_query",
                    models.BooleanField(default=True, verbose_name="allow_query"),
                ),
                (
                    "allow_export",
                    models.BooleanField(default=False, verbose_name="allow_export"),
                ),
                ("timeout", models.IntegerField(default=30, verbose_name="timeout")),
                (
                    "retry_count",
                    models.IntegerField(default=2, verbose_name="retry_count"),
                ),
                (
                    "model",
                    models.CharField(
                        default="gpt-4o", max_length=50, verbose_name="model"
                    ),
                ),
                (
                    "api_endpoint",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="api_endpoint",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="api_key_encrypted",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AgentConfig",
                "verbose_name_plural": "AgentConfig",
                "db_table": "agent_config",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_code",
                    models.CharField(max_length=20, verbose_name="agent_code"),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="session_id"
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=200, verbose_name="title"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="status"
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(default=0, verbose_name="message_count"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expired_at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "AgentSession",
                "db_table": "agent_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "user"),
                            ("assistant", "assistant"),
                            ("system", "system"),
                        ],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "token_count",
                    models.IntegerField(default=0, verbose_name="token_count"),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="model_used"
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(default=0, verbose_name="latency_ms"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="auth_app.agentsession",
                        verbose_name="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "AgentMessage",
                "db_table": "agent_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentVerificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.IntegerField(verbose_name="article_id")),
                (
                    "agent_code",
                    models.CharField(
                        choices=[
                            ("auditor", "auditor"),
                            ("verifier", "verifier"),
                            ("archiver", "archiver"),
                            ("judge", "judge"),
                        ],
                        max_length=20,
                        verbose_name="agent_code",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(max_length=50, verbose_name="agent_name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("summary", models.TextField(default="", verbose_name="summary")),
                (
                    "detail",
                    models.TextField(blank=True, default="", verbose_name="detail"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(default=0, verbose_name="duration_ms"),
                ),
                (
                    "result_data",
                    models.JSONField(blank=True, null=True, verbose_name="result_data"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="sort_order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_time"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="operator",
                    ),
                ),
            ],
            options={
                "verbose_name": "AgentVerificationRecord",
                "db_table": "agent_verification_record",
                "ordering": ["article_id", "sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["article_id", "agent_code"],
                        name="agent_verif_article_f5c864_idx",
                    )
                ],
            },
        ),
    ]
