# Generated by Django 6.0.1 on 2026-05-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0004_add_agent_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSecurityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="规则名称")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("prompt_injection", "提示词注入检测"),
                            ("sensitive_content", "敏感内容过滤"),
                            ("tool_permission", "工具调用权限"),
                            ("rate_limit", "频率限制"),
                            ("input_length", "输入长度限制"),
                            ("output_filter", "输出内容过滤"),
                        ],
                        max_length=50,
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="规则描述"),
                ),
                ("pattern", models.TextField(verbose_name="匹配模式/关键词")),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("keyword", "关键词匹配"),
                            ("regex", "正则表达式"),
                            ("ml_model", "ML模型检测"),
                        ],
                        default="keyword",
                        max_length=20,
                        verbose_name="模式类型",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重风险"),
                        ],
                        default="high",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("block", "拦截并拒绝"),
                            ("warn", "警告但放行"),
                            ("mask", "脱敏处理"),
                            ("log_only", "仅记录日志"),
                        ],
                        default="block",
                        max_length=20,
                        verbose_name="处理动作",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100, verbose_name="优先级（数字越小越优先）"
                    ),
                ),
                (
                    "target_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="适用角色ID列表"
                    ),
                ),
                (
                    "exclude_users",
                    models.JSONField(
                        blank=True, default=list, verbose_name="排除用户ID列表"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("created_by", models.IntegerField(default=0, verbose_name="创建人ID")),
            ],
            options={
                "verbose_name": "Agent安全规则",
                "verbose_name_plural": "Agent安全规则",
                "db_table": "agent_security_rule",
                "ordering": ["priority", "-created_at"],
                "indexes": [
                    models.Index(fields=["rule_type"], name="idx_security_rule_type"),
                    models.Index(fields=["is_enabled"], name="idx_security_enabled"),
                    models.Index(fields=["severity"], name="idx_security_severity"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentRiskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="会话ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="用户ID"
                    ),
                ),
                (
                    "agent_role",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Agent角色"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("blocked", "已拦截"),
                            ("warned", "已警告"),
                            ("passed", "已放行"),
                            ("masked", "已脱敏"),
                        ],
                        default="blocked",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "input_content",
                    models.TextField(
                        blank=True, default="", verbose_name="输入内容（截断）"
                    ),
                ),
                (
                    "detected_pattern",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="检测到的模式",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        default="block", max_length=20, verbose_name="执行的动作"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(default="", verbose_name="IP地址"),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, default="", verbose_name="响应消息"),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_logs",
                        to="auth_app.agentsecurityrule",
                        verbose_name="触发的规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent风控日志",
                "verbose_name_plural": "Agent风控日志",
                "db_table": "agent_risk_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "-created_at"], name="idx_risk_user_time"
                    ),
                    models.Index(fields=["risk_level"], name="idx_risk_level"),
                    models.Index(fields=["status"], name="idx_risk_status"),
                    models.Index(fields=["-created_at"], name="idx_risk_created"),
                ],
            },
        ),
    ]
