# Generated by Django 6.0.1 on 2026-05-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0006_securitytestcase_securityvulnerability"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="原始内容")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="内容哈希",
                    ),
                ),
                (
                    "source",
                    models.CharField(default="web", max_length=50, verbose_name="来源"),
                ),
                (
                    "user_id",
                    models.IntegerField(blank=True, null=True, verbose_name="用户ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="用户名"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "通过"),
                            ("blocked", "已拦截"),
                            ("warning", "警告"),
                            ("pending", "待审核"),
                        ],
                        default="passed",
                        max_length=20,
                        verbose_name="检测结果",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        default="low", max_length=20, verbose_name="风险等级"
                    ),
                ),
                (
                    "total_matches",
                    models.IntegerField(default=0, verbose_name="匹配总数"),
                ),
                (
                    "matched_rules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="命中规则详情"
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("check", "内容检测"),
                            ("block", "拦截"),
                            ("pass", "放行"),
                            ("manual_review", "转人工审核"),
                        ],
                        default="check",
                        max_length=30,
                        verbose_name="执行动作",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "内容审核日志",
                "verbose_name_plural": "内容审核日志",
                "db_table": "content_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["result"], name="idx_audit_result"),
                    models.Index(fields=["risk_level"], name="idx_audit_risk"),
                    models.Index(fields=["source"], name="idx_audit_source"),
                    models.Index(fields=["-created_at"], name="idx_audit_created"),
                    models.Index(fields=["user_id"], name="idx_audit_user"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegexRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="规则名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sensitive_word", "敏感词"),
                            ("spam", "垃圾广告"),
                            ("political", "政治敏感"),
                            ("pornography", "色情低俗"),
                            ("violence", "暴力恐吓"),
                            ("personal_info", "个人信息"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="分类",
                    ),
                ),
                ("pattern", models.TextField(verbose_name="正则表达式")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="规则描述"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("warn", "警告"),
                            ("block", "拦截"),
                            ("replace", "替换"),
                            ("review", "人工审核"),
                        ],
                        default="warn",
                        max_length=20,
                        verbose_name="处置动作",
                    ),
                ),
                (
                    "replacement",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="替换文本"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "match_count",
                    models.IntegerField(default=0, verbose_name="匹配次数"),
                ),
                (
                    "false_positive_count",
                    models.IntegerField(default=0, verbose_name="误报次数"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "正则规则",
                "verbose_name_plural": "正则规则",
                "db_table": "regex_rule",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["category"], name="idx_rule_category"),
                    models.Index(fields=["is_enabled"], name="idx_rule_enabled"),
                    models.Index(fields=["severity"], name="idx_rule_severity"),
                    models.Index(fields=["-match_count"], name="idx_rule_match_count"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegexTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_text", models.TextField(verbose_name="测试文本")),
                (
                    "expected_match",
                    models.BooleanField(default=True, verbose_name="预期是否匹配"),
                ),
                (
                    "expected_hits",
                    models.IntegerField(default=1, verbose_name="预期命中次数"),
                ),
                (
                    "actual_match",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="实际是否匹配"
                    ),
                ),
                (
                    "actual_hits",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="实际命中次数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("inactive", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="auth_app.regexrule",
                        verbose_name="关联规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "正则测试用例",
                "verbose_name_plural": "正则测试用例",
                "db_table": "regex_test_case",
                "ordering": ["-created_at"],
            },
        ),
    ]
