# Generated by Django 6.0.1 on 2026-05-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_contentauditlog_regexrule_regextestcase"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日报"),
                            ("weekly", "周报"),
                            ("monthly", "月报"),
                            ("custom", "自定义"),
                        ],
                        max_length=20,
                        verbose_name="报表类型",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="报表标题")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="generating",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="周期开始")),
                ("period_end", models.DateField(verbose_name="周期结束")),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="摘要数据"),
                ),
                (
                    "detail_data",
                    models.JSONField(blank=True, default=dict, verbose_name="详细数据"),
                ),
                (
                    "file_path",
                    models.FilePathField(
                        blank=True, max_length=500, null=True, verbose_name="文件路径"
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "安全报表",
                "verbose_name_plural": "安全报表",
                "db_table": "security_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.IntegerField(default=100, verbose_name="总分")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("excellent", "优秀"),
                            ("good", "良好"),
                            ("warning", "警告"),
                            ("danger", "危险"),
                            ("critical", "严重"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="等级",
                    ),
                ),
                (
                    "vulnerability_score",
                    models.IntegerField(default=0, verbose_name="漏洞扣分"),
                ),
                ("risk_score", models.IntegerField(default=0, verbose_name="风险扣分")),
                (
                    "audit_score",
                    models.IntegerField(default=0, verbose_name="审计扣分"),
                ),
                (
                    "open_vulns",
                    models.IntegerField(default=0, verbose_name="未修复漏洞数"),
                ),
                (
                    "critical_vulns",
                    models.IntegerField(default=0, verbose_name="严重漏洞数"),
                ),
                (
                    "high_risk_events",
                    models.IntegerField(default=0, verbose_name="高风险事件数"),
                ),
                (
                    "blocked_content",
                    models.IntegerField(default=0, verbose_name="拦截内容数"),
                ),
                (
                    "failed_tests",
                    models.IntegerField(default=0, verbose_name="失败测试数"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="详细评分项"
                    ),
                ),
                (
                    "scored_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评分时间"),
                ),
            ],
            options={
                "verbose_name": "安全评分",
                "verbose_name_plural": "安全评分",
                "db_table": "security_score",
                "ordering": ["-scored_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="告警标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vulnerability", "漏洞告警"),
                            ("risk_event", "风险事件"),
                            ("audit_anomaly", "审计异常"),
                            ("content_violation", "内容违规"),
                            ("system", "系统告警"),
                            ("permission", "权限异常"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="分类",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                            ("suppressed", "已抑制"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="", max_length=50, verbose_name="来源类型"
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(blank=True, null=True, verbose_name="来源ID"),
                ),
                (
                    "source_detail",
                    models.JSONField(blank=True, default=dict, verbose_name="来源详情"),
                ),
                (
                    "assignee_id",
                    models.IntegerField(blank=True, null=True, verbose_name="处理人ID"),
                ),
                (
                    "assignee_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="处理人姓名",
                    ),
                ),
                (
                    "resolved_by",
                    models.IntegerField(blank=True, null=True, verbose_name="解决人ID"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, default="", verbose_name="解决备注"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="触发时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "安全告警",
                "verbose_name_plural": "安全告警",
                "db_table": "security_alert",
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(fields=["severity"], name="idx_alert_severity"),
                    models.Index(fields=["status"], name="idx_alert_status"),
                    models.Index(fields=["category"], name="idx_alert_category"),
                    models.Index(fields=["-triggered_at"], name="idx_alert_triggered"),
                ],
            },
        ),
    ]
