# Generated by Django 6.0.1 on 2026-05-27 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0009_delete_agentconfig_remove_agentmessage_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("auditor", "auditor"),
                            ("verifier", "verifier"),
                            ("archiver", "archiver"),
                            ("judge", "judge"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="sort_order"),
                ),
                (
                    "short_desc",
                    models.CharField(
                        default="", max_length=200, verbose_name="short_desc"
                    ),
                ),
                ("full_desc", models.TextField(default="", verbose_name="full_desc")),
                (
                    "icon",
                    models.CharField(
                        default="RobotOutlined", max_length=50, verbose_name="icon"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2563EB", max_length=20, verbose_name="color"
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#EFF6FF", max_length=20, verbose_name="bg_color"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(default="", verbose_name="system_prompt"),
                ),
                (
                    "welcome_msg",
                    models.CharField(
                        default="", max_length=500, verbose_name="welcome_msg"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.7, verbose_name="temperature"),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=2000, verbose_name="max_tokens"),
                ),
                (
                    "allow_summary",
                    models.BooleanField(default=True, verbose_name="allow_summary"),
                ),
                (
                    "allow_analysis",
                    models.BooleanField(default=True, verbose_name="allow_analysis"),
                ),
                (
                    "allow_query",
                    models.BooleanField(default=True, verbose_name="allow_query"),
                ),
                (
                    "allow_export",
                    models.BooleanField(default=False, verbose_name="allow_export"),
                ),
                ("timeout", models.IntegerField(default=30, verbose_name="timeout")),
                (
                    "retry_count",
                    models.IntegerField(default=2, verbose_name="retry_count"),
                ),
                (
                    "model",
                    models.CharField(
                        default="gpt-4o", max_length=50, verbose_name="model"
                    ),
                ),
                (
                    "api_endpoint",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="api_endpoint",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="api_key_encrypted",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AgentConfig",
                "verbose_name_plural": "AgentConfig",
                "db_table": "agent_config",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SecurityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日报"),
                            ("weekly", "周报"),
                            ("monthly", "月报"),
                            ("custom", "自定义"),
                        ],
                        max_length=20,
                        verbose_name="报表类型",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="报表标题")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="generating",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="周期开始")),
                ("period_end", models.DateField(verbose_name="周期结束")),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="摘要数据"),
                ),
                (
                    "detail_data",
                    models.JSONField(blank=True, default=dict, verbose_name="详细数据"),
                ),
                (
                    "file_path",
                    models.FilePathField(
                        blank=True, max_length=500, null=True, verbose_name="文件路径"
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "安全报表",
                "verbose_name_plural": "安全报表",
                "db_table": "security_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.IntegerField(default=100, verbose_name="总分")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("excellent", "优秀"),
                            ("good", "良好"),
                            ("warning", "警告"),
                            ("danger", "危险"),
                            ("critical", "严重"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="等级",
                    ),
                ),
                (
                    "vulnerability_score",
                    models.IntegerField(default=0, verbose_name="漏洞扣分"),
                ),
                ("risk_score", models.IntegerField(default=0, verbose_name="风险扣分")),
                (
                    "audit_score",
                    models.IntegerField(default=0, verbose_name="审计扣分"),
                ),
                (
                    "open_vulns",
                    models.IntegerField(default=0, verbose_name="未修复漏洞数"),
                ),
                (
                    "critical_vulns",
                    models.IntegerField(default=0, verbose_name="严重漏洞数"),
                ),
                (
                    "high_risk_events",
                    models.IntegerField(default=0, verbose_name="高风险事件数"),
                ),
                (
                    "blocked_content",
                    models.IntegerField(default=0, verbose_name="拦截内容数"),
                ),
                (
                    "failed_tests",
                    models.IntegerField(default=0, verbose_name="失败测试数"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="详细评分项"
                    ),
                ),
                (
                    "scored_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评分时间"),
                ),
            ],
            options={
                "verbose_name": "安全评分",
                "verbose_name_plural": "安全评分",
                "db_table": "security_score",
                "ordering": ["-scored_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_code",
                    models.CharField(max_length=20, verbose_name="agent_code"),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="session_id"
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=200, verbose_name="title"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="status"
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(default=0, verbose_name="message_count"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expired_at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "AgentSession",
                "db_table": "agent_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "user"),
                            ("assistant", "assistant"),
                            ("system", "system"),
                        ],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "token_count",
                    models.IntegerField(default=0, verbose_name="token_count"),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="model_used"
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(default=0, verbose_name="latency_ms"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="auth_app.agentsession",
                        verbose_name="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "AgentMessage",
                "db_table": "agent_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="原始内容")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="内容哈希",
                    ),
                ),
                (
                    "source",
                    models.CharField(default="web", max_length=50, verbose_name="来源"),
                ),
                (
                    "user_id",
                    models.IntegerField(blank=True, null=True, verbose_name="用户ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="用户名"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "通过"),
                            ("blocked", "已拦截"),
                            ("warning", "警告"),
                            ("pending", "待审核"),
                        ],
                        default="passed",
                        max_length=20,
                        verbose_name="检测结果",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        default="low", max_length=20, verbose_name="风险等级"
                    ),
                ),
                (
                    "total_matches",
                    models.IntegerField(default=0, verbose_name="匹配总数"),
                ),
                (
                    "matched_rules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="命中规则详情"
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("check", "内容检测"),
                            ("block", "拦截"),
                            ("pass", "放行"),
                            ("manual_review", "转人工审核"),
                        ],
                        default="check",
                        max_length=30,
                        verbose_name="执行动作",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "内容审核日志",
                "verbose_name_plural": "内容审核日志",
                "db_table": "content_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["result"], name="idx_audit_result"),
                    models.Index(fields=["risk_level"], name="idx_audit_risk"),
                    models.Index(fields=["source"], name="idx_audit_source"),
                    models.Index(fields=["-created_at"], name="idx_audit_created"),
                    models.Index(fields=["user_id"], name="idx_audit_user"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=50, verbose_name="模块")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "新增"),
                            ("update", "修改"),
                            ("delete", "删除"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="请求方法"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="请求URL"
                    ),
                ),
                (
                    "params",
                    models.TextField(blank=True, default="", verbose_name="请求参数"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="用户代理"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=10,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="执行消息"),
                ),
                ("duration", models.IntegerField(default=0, verbose_name="耗时(ms)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "rbac_operation_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(max_length=20, verbose_name="目标类型"),
                ),
                ("target_id", models.IntegerField(verbose_name="目标ID")),
                (
                    "target_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="目标名称"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assign_role", "分配角色"),
                            ("remove_role", "移除角色"),
                            ("assign_perm", "分配权限"),
                            ("remove_perm", "移除权限"),
                            ("create_role", "创建角色"),
                            ("update_role", "更新角色"),
                            ("delete_role", "删除角色"),
                            ("create_menu", "创建菜单"),
                            ("update_menu", "更新菜单"),
                            ("delete_menu", "删除菜单"),
                        ],
                        max_length=20,
                        verbose_name="操作动作",
                    ),
                ),
                (
                    "detail_before",
                    models.TextField(blank=True, default="", verbose_name="变更前内容"),
                ),
                (
                    "detail_after",
                    models.TextField(blank=True, default="", verbose_name="变更后内容"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限审计日志",
                "verbose_name_plural": "权限审计日志",
                "db_table": "rbac_permission_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegexRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="规则名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sensitive_word", "敏感词"),
                            ("spam", "垃圾广告"),
                            ("political", "政治敏感"),
                            ("pornography", "色情低俗"),
                            ("violence", "暴力恐吓"),
                            ("personal_info", "个人信息"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="分类",
                    ),
                ),
                ("pattern", models.TextField(verbose_name="正则表达式")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="规则描述"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("warn", "警告"),
                            ("block", "拦截"),
                            ("replace", "替换"),
                            ("review", "人工审核"),
                        ],
                        default="warn",
                        max_length=20,
                        verbose_name="处置动作",
                    ),
                ),
                (
                    "replacement",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="替换文本"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "match_count",
                    models.IntegerField(default=0, verbose_name="匹配次数"),
                ),
                (
                    "false_positive_count",
                    models.IntegerField(default=0, verbose_name="误报次数"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "正则规则",
                "verbose_name_plural": "正则规则",
                "db_table": "regex_rule",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["category"], name="idx_rule_category"),
                    models.Index(fields=["is_enabled"], name="idx_rule_enabled"),
                    models.Index(fields=["severity"], name="idx_rule_severity"),
                    models.Index(fields=["-match_count"], name="idx_rule_match_count"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegexTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_text", models.TextField(verbose_name="测试文本")),
                (
                    "expected_match",
                    models.BooleanField(default=True, verbose_name="预期是否匹配"),
                ),
                (
                    "expected_hits",
                    models.IntegerField(default=1, verbose_name="预期命中次数"),
                ),
                (
                    "actual_match",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="实际是否匹配"
                    ),
                ),
                (
                    "actual_hits",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="实际命中次数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("inactive", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="auth_app.regexrule",
                        verbose_name="关联规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "正则测试用例",
                "verbose_name_plural": "正则测试用例",
                "db_table": "regex_test_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="角色编码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "data_scope",
                    models.CharField(
                        choices=[
                            ("all", "全部数据"),
                            ("self", "仅本人数据"),
                            ("role", "本角色数据"),
                        ],
                        default="self",
                        max_length=10,
                        verbose_name="数据权限范围",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "db_table": "rbac_role",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="权限名称")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="权限标识"
                    ),
                ),
                (
                    "perm_type",
                    models.CharField(
                        choices=[("menu", "菜单"), ("button", "按钮"), ("api", "接口")],
                        default="menu",
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="路由路径"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="请求方法"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="组件路径"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="图标"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("visible", models.BooleanField(default=True, verbose_name="是否可见")),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="auth_app.permission",
                        verbose_name="上级权限",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permissions",
                        to="auth_app.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限",
                "verbose_name_plural": "权限",
                "db_table": "rbac_permission",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="菜单名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="菜单编码"
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("directory", "目录"),
                            ("menu", "菜单"),
                            ("button", "按钮"),
                        ],
                        default="menu",
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="路由路径"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="组件路径"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="图标"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("visible", models.BooleanField(default=True, verbose_name="是否显示")),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="auth_app.menu",
                        verbose_name="上级菜单",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menus",
                        to="auth_app.permission",
                        verbose_name="关联权限",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="menus",
                        to="auth_app.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单",
                "db_table": "rbac_menu",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="告警标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vulnerability", "漏洞告警"),
                            ("risk_event", "风险事件"),
                            ("audit_anomaly", "审计异常"),
                            ("content_violation", "内容违规"),
                            ("system", "系统告警"),
                            ("permission", "权限异常"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="分类",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                            ("suppressed", "已抑制"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="", max_length=50, verbose_name="来源类型"
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(blank=True, null=True, verbose_name="来源ID"),
                ),
                (
                    "source_detail",
                    models.JSONField(blank=True, default=dict, verbose_name="来源详情"),
                ),
                (
                    "assignee_id",
                    models.IntegerField(blank=True, null=True, verbose_name="处理人ID"),
                ),
                (
                    "assignee_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="处理人姓名",
                    ),
                ),
                (
                    "resolved_by",
                    models.IntegerField(blank=True, null=True, verbose_name="解决人ID"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, default="", verbose_name="解决备注"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="触发时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "安全告警",
                "verbose_name_plural": "安全告警",
                "db_table": "security_alert",
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(fields=["severity"], name="idx_alert_severity"),
                    models.Index(fields=["status"], name="idx_alert_status"),
                    models.Index(fields=["category"], name="idx_alert_category"),
                    models.Index(fields=["-triggered_at"], name="idx_alert_triggered"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="用例名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("prompt_injection", "提示词注入"),
                            ("sensitive_content", "敏感内容"),
                            ("tool_abuse", "工具滥用"),
                            ("data_leakage", "数据泄露"),
                            ("rate_limit", "频率限制"),
                            ("output_filter", "输出过滤"),
                        ],
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("input_payload", models.TextField(verbose_name="测试输入")),
                (
                    "expected_risk_level",
                    models.CharField(
                        default="high", max_length=20, verbose_name="预期风险等级"
                    ),
                ),
                (
                    "expected_action",
                    models.CharField(
                        default="block", max_length=20, verbose_name="期望动作"
                    ),
                ),
                (
                    "expected_pattern",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="应匹配的模式",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        default="high", max_length=20, verbose_name="严重程度"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("deprecated", "已废弃"),
                            ("draft", "草稿"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "安全测试用例",
                "verbose_name_plural": "安全测试用例",
                "db_table": "security_test_case",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["category"], name="idx_test_case_category"),
                    models.Index(fields=["status"], name="idx_test_case_status"),
                    models.Index(fields=["severity"], name="idx_test_case_severity"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityVulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="漏洞标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("category", models.CharField(max_length=50, verbose_name="分类")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        default="high",
                        max_length=20,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待修复"),
                            ("in_progress", "修复中"),
                            ("fixed", "已修复"),
                            ("wontfix", "不修复"),
                            ("false_positive", "误报"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "related_rule_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="关联规则ID"
                    ),
                ),
                (
                    "related_test_case_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="关联测试用例ID"
                    ),
                ),
                (
                    "detected_input",
                    models.TextField(blank=True, default="", verbose_name="触发输入"),
                ),
                (
                    "matched_pattern",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="匹配模式"
                    ),
                ),
                (
                    "fix_description",
                    models.TextField(blank=True, default="", verbose_name="修复方案"),
                ),
                (
                    "fixed_by",
                    models.IntegerField(blank=True, null=True, verbose_name="修复人ID"),
                ),
                (
                    "fixed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="修复时间"
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="发现人ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "安全漏洞",
                "verbose_name_plural": "安全漏洞",
                "db_table": "security_vulnerability",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_vuln_status"),
                    models.Index(fields=["severity"], name="idx_vuln_severity"),
                    models.Index(fields=["category"], name="idx_vuln_category"),
                    models.Index(fields=["-created_at"], name="idx_vuln_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentVerificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.IntegerField(verbose_name="article_id")),
                (
                    "agent_code",
                    models.CharField(
                        choices=[
                            ("auditor", "auditor"),
                            ("verifier", "verifier"),
                            ("archiver", "archiver"),
                            ("judge", "judge"),
                        ],
                        max_length=20,
                        verbose_name="agent_code",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(max_length=50, verbose_name="agent_name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("summary", models.TextField(default="", verbose_name="summary")),
                (
                    "detail",
                    models.TextField(blank=True, default="", verbose_name="detail"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(default=0, verbose_name="duration_ms"),
                ),
                (
                    "result_data",
                    models.JSONField(blank=True, null=True, verbose_name="result_data"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="sort_order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_time"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="operator",
                    ),
                ),
            ],
            options={
                "verbose_name": "AgentVerificationRecord",
                "db_table": "agent_verification_record",
                "ordering": ["article_id", "sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["article_id", "agent_code"],
                        name="agent_verif_article_f5c864_idx",
                    )
                ],
            },
        ),
    ]
