# Generated by Django 6.0.1 on 2026-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0010_fix_missing_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="IMAutoReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("keyword", "关键词匹配"),
                            ("regex", "正则表达式"),
                            ("welcome", "欢迎语"),
                            ("offline", "离线自动回复"),
                            ("default", "默认回复"),
                        ],
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="关键词/正则",
                    ),
                ),
                ("reply_content", models.TextField(verbose_name="回复内容")),
                (
                    "priority",
                    models.IntegerField(
                        default=0, verbose_name="优先级（数字越大越优先）"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "match_count",
                    models.IntegerField(default=0, verbose_name="匹配次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "IM自动回复",
                "verbose_name_plural": "IM自动回复",
                "db_table": "im_auto_reply",
                "ordering": ["-priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[
                            ("privacy", "隐私政策"),
                            ("terms", "用户服务条款"),
                            ("cookie", "Cookie政策"),
                        ],
                        default="privacy",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="协议内容（HTML/富文本）")),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="版本号"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否生效"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="是否必须同意"),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="生效日期"),
                ),
                (
                    "created_by",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "隐私协议",
                "verbose_name_plural": "隐私协议",
                "db_table": "privacy_agreement",
                "ordering": ["-version", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceAssistantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_key",
                    models.CharField(max_length=50, unique=True, verbose_name="配置键"),
                ),
                (
                    "config_value",
                    models.TextField(blank=True, default="", verbose_name="配置值"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="描述"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "语音助手配置",
                "verbose_name_plural": "语音助手配置",
                "db_table": "voice_assistant_config",
            },
        ),
        migrations.CreateModel(
            name="IMMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="会话ID"
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("agent", "客服"),
                            ("system", "系统"),
                            ("auto_reply", "自动回复"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="发送者类型",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="发送者用户ID（用户时）"
                    ),
                ),
                (
                    "agent_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="客服ID（客服时）"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文本消息"),
                            ("image", "图片消息"),
                            ("file", "文件消息"),
                            ("system", "系统消息"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="消息内容"),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, default="", verbose_name="文件URL"),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已读"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "IM消息",
                "verbose_name_plural": "IM消息",
                "db_table": "im_message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "-created_at"], name="idx_im_session_time"
                    ),
                    models.Index(fields=["is_read"], name="idx_im_read"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True, verbose_name="用户ID")),
                (
                    "username",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="用户名"
                    ),
                ),
                (
                    "agreement_type",
                    models.CharField(max_length=20, verbose_name="协议类型"),
                ),
                (
                    "agreement_version",
                    models.CharField(max_length=20, verbose_name="协议版本"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agreed", "已同意"),
                            ("declined", "已拒绝"),
                            ("pending", "待处理"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "consented_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="同意时间"),
                ),
            ],
            options={
                "verbose_name": "用户同意记录",
                "verbose_name_plural": "用户同意记录",
                "db_table": "user_consent_record",
                "ordering": ["-consented_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "agreement_type"],
                        name="idx_consent_user_type",
                    ),
                    models.Index(fields=["status"], name="idx_consent_status"),
                ],
                "unique_together": {("user_id", "agreement_type", "agreement_version")},
            },
        ),
    ]
