# Generated by Django 6.0.1 on 2026-05-27 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0012_hotcontenttemplate_order_paymentrecord_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationlog",
            name="params",
        ),
        migrations.RemoveField(
            model_name="operationlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="operationlog",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="loginlog",
            name="device_info",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="登录设备"
            ),
        ),
        migrations.AddField(
            model_name="loginlog",
            name="logout_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="退出时间"),
        ),
        migrations.AddField(
            model_name="loginlog",
            name="message",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="备注信息"
            ),
        ),
        migrations.AddField(
            model_name="loginlog",
            name="session_id",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="会话ID"
            ),
        ),
        migrations.AddField(
            model_name="loginlog",
            name="username",
            field=models.CharField(
                db_index=True, default="", max_length=150, verbose_name="账号"
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="operator_name",
            field=models.CharField(
                db_index=True, default="", max_length=150, verbose_name="操作人账号"
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="request_data",
            field=models.TextField(blank=True, default="", verbose_name="请求数据"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="response_code",
            field=models.IntegerField(default=0, verbose_name="响应状态码"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="role_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="角色"
            ),
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="登录IP"
            ),
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="login_time",
            field=models.DateTimeField(db_index=True, verbose_name="登录时间"),
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "登录成功"),
                    ("failed", "登录失败"),
                    ("logout", "正常退出"),
                    ("timeout", "会话超时"),
                    ("kicked", "被踢下线"),
                ],
                default="success",
                max_length=10,
                verbose_name="登录状态",
            ),
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="账号",
            ),
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="user_agent",
            field=models.TextField(blank=True, default="", verbose_name="User-Agent"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="created_at",
            field=models.DateTimeField(db_index=True, verbose_name="操作时间"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="IP地址"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="method",
            field=models.CharField(
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("DELETE", "DELETE"),
                    ("PATCH", "PATCH"),
                ],
                default="GET",
                max_length=10,
                verbose_name="请求方法",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="module",
            field=models.CharField(db_index=True, max_length=50, verbose_name="模块"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="result",
            field=models.CharField(
                choices=[
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("error", "异常"),
                    ("denied", "无权限"),
                ],
                default="success",
                max_length=10,
                verbose_name="操作结果",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="url",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="请求接口"
            ),
        ),
        migrations.CreateModel(
            name="FrontendUserManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="昵称"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="手机号"
                    ),
                ),
                (
                    "avatar",
                    models.URLField(blank=True, default="", verbose_name="头像"),
                ),
                (
                    "login_count",
                    models.IntegerField(default=0, verbose_name="登录次数"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="最后登录IP"
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(default=False, verbose_name="是否禁用"),
                ),
                (
                    "ban_reason",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="禁用原因"
                    ),
                ),
                (
                    "banned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="禁用时间"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banned_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="禁用人",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frontend_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "前台用户管理",
                "verbose_name_plural": "前台用户管理",
                "db_table": "system_frontend_user_manager",
            },
        ),
        migrations.CreateModel(
            name="PermissionInterceptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=150,
                        verbose_name="账号",
                    ),
                ),
                (
                    "intercept_type",
                    models.CharField(
                        choices=[
                            ("menu_unauthorized", "越权访问菜单"),
                            ("api_unauthorized", "越权调用接口"),
                            ("button_denied", "无权限按钮点击"),
                            ("token_expired", "Token过期访问"),
                            ("token_invalid", "无效Token访问"),
                            ("rate_limited", "频率限制拦截"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="拦截类型",
                    ),
                ),
                (
                    "target_resource",
                    models.CharField(
                        max_length=500, verbose_name="目标资源(菜单/接口/按钮)"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="请求方法"
                    ),
                ),
                (
                    "request_url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="请求URL"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "detail",
                    models.TextField(blank=True, default="", verbose_name="拦截详情"),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, verbose_name="拦截时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intercept_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限拦截日志",
                "verbose_name_plural": "权限拦截日志",
                "db_table": "log_center_permission_intercept",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSecurityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_key",
                    models.CharField(max_length=50, unique=True, verbose_name="配置键"),
                ),
                ("config_value", models.TextField(verbose_name="配置值")),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("string", "字符串"),
                            ("int", "整数"),
                            ("json", "JSON"),
                            ("bool", "布尔"),
                        ],
                        default="string",
                        max_length=10,
                        verbose_name="值类型",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="描述"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统安全配置",
                "verbose_name_plural": "系统安全配置",
                "db_table": "system_security_config",
            },
        ),
        migrations.CreateModel(
            name="UserBrowseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_url", models.CharField(max_length=500, verbose_name="页面URL")),
                (
                    "page_title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="页面标题"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "stay_duration",
                    models.IntegerField(default=0, verbose_name="停留时长(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, verbose_name="访问时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browse_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户浏览记录",
                "verbose_name_plural": "用户浏览记录",
                "db_table": "system_user_browse_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
