# Generated by Django 6.0.1 on 2026-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0014_functioncard"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="功能名称")),
                ("category", models.CharField(max_length=50, verbose_name="功能分类")),
                (
                    "main_scenario",
                    models.CharField(max_length=50, verbose_name="对应主场景"),
                ),
                (
                    "keywords",
                    models.JSONField(default=list, verbose_name="Prompt关键词"),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="推荐权重"
                    ),
                ),
                (
                    "dev_days",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="开发周期(天)"
                    ),
                ),
                (
                    "monetization_type",
                    models.CharField(
                        choices=[
                            ("free+pay", "免费基础+按次付费"),
                            ("member+pay", "会员免费+按次付费"),
                            ("pay+enterprise", "按次付费+企业定制"),
                            ("enterprise", "企业定制"),
                            ("free", "完全免费"),
                        ],
                        default="free+pay",
                        max_length=30,
                        verbose_name="变现类型",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("core", "核心鉴别场景"),
                            ("security", "安全融合层"),
                            ("product", "产品融合层"),
                            ("vertical", "垂直场景层"),
                            ("monetization", "变现生态层"),
                            ("multilingual", "多语言蓝海层"),
                            ("professional", "专业领域层"),
                            ("special", "特殊内容层"),
                            ("compliance", "合规审计层"),
                            ("ai-detect", "AI检测同行层"),
                            ("content-security", "内容安全同行层"),
                            ("ai-governance", "AI治理同行层"),
                            ("vertical-peer", "垂直场景同行层"),
                            ("infoflow-detect", "信息流检测层"),
                            ("traffic-optimize", "流量优化层"),
                            ("infoflow-compliance", "信息流合规层"),
                            ("multimodal-infoflow", "多模态信息流层"),
                            ("context-understanding", "上下文理解层"),
                            ("long-conversation", "长对话管理层"),
                            ("context-risk-control", "上下文风控层"),
                            ("vertical-context", "垂直上下文层"),
                            ("retrieval-system", "检索系统层"),
                            ("cluster-management", "集群管理层"),
                            ("file-operation", "文件操作层"),
                            ("voice-input", "语音输入层"),
                            ("general-agent", "通用Agent层"),
                            ("enterprise-agent", "企业Agent层"),
                            ("vertical-agent", "垂直Agent层"),
                            ("multi-agent-collab", "多Agent协作层"),
                        ],
                        default="core",
                        max_length=30,
                        verbose_name="所属层级",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="Zap", max_length=30, verbose_name="图标名称"
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        default="#165DFF", max_length=7, verbose_name="图标颜色"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="功能描述"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "上线"),
                            ("offline", "下线"),
                            ("beta", "内测"),
                            ("coming_soon", "即将上线"),
                        ],
                        default="online",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "is_recommended",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                ("is_hot", models.BooleanField(default=False, verbose_name="是否热门")),
                (
                    "is_new",
                    models.BooleanField(default=True, verbose_name="是否新上线"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "技能配置",
                "verbose_name_plural": "技能配置",
                "db_table": "system_skill_config",
                "ordering": ["-weight", "-sort_order", "id"],
            },
        ),
    ]
