# Generated by Django 6.0.1 on 2026-05-28 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0015_skillconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="副标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="详细描述"),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("vip_basic", "基础会员"),
                            ("vip_premium", "高级会员"),
                            ("vip_enterprise", "企业定制"),
                            ("pay_per_use", "按次付费"),
                            ("feature_launch", "新功能上线"),
                            ("limited_offer", "限时优惠"),
                            ("referral", "邀请有礼"),
                        ],
                        default="vip_basic",
                        max_length=30,
                        verbose_name="卡片类型",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("feed_top", "信息流顶部"),
                            ("feed_middle", "信息流中部(每5条)"),
                            ("feed_bottom", "信息流底部"),
                            ("skill_panel_header", "技能面板头部"),
                            ("skill_panel_footer", "技能面板底部"),
                            ("sidebar", "侧边栏"),
                        ],
                        default="feed_middle",
                        max_length=30,
                        verbose_name="展示位置",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="Crown", max_length=30, verbose_name="图标名称"
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        default="#F5A623", max_length=7, verbose_name="图标颜色"
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#FFF7E8", max_length=7, verbose_name="背景色"
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="#FFD666", max_length=7, verbose_name="边框色"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#F5A623", max_length=7, verbose_name="强调色"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, default="", verbose_name="封面图URL"),
                ),
                (
                    "link_url",
                    models.URLField(blank=True, default="", verbose_name="跳转链接"),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="立即开通", max_length=30, verbose_name="按钮文字"
                    ),
                ),
                (
                    "price_text",
                    models.CharField(
                        blank=True,
                        default="¥9.9/月起",
                        max_length=50,
                        verbose_name="价格文案",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(default=10, verbose_name="优先级"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "上线"),
                            ("offline", "下线"),
                            ("scheduled", "定时上线"),
                        ],
                        default="online",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "show_count_limit",
                    models.PositiveIntegerField(
                        default=0, help_text="0=不限", verbose_name="展示次数上限"
                    ),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(default=0, verbose_name="点击次数"),
                ),
                (
                    "conversion_count",
                    models.PositiveIntegerField(default=0, verbose_name="转化次数"),
                ),
                (
                    "target_user_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="all/free_user/vip/non_vip/active/inactive",
                        max_length=20,
                        verbose_name="目标用户",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "推广卡片配置",
                "verbose_name_plural": "推广卡片配置",
                "db_table": "promo_card_config",
                "ordering": ["-priority", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "preferred_tiers",
                    models.JSONField(
                        blank=True, default=list, verbose_name="偏好层级列表"
                    ),
                ),
                (
                    "preferred_categories",
                    models.JSONField(
                        blank=True, default=list, verbose_name="偏好分类列表"
                    ),
                ),
                (
                    "preferred_scenarios",
                    models.JSONField(
                        blank=True, default=list, verbose_name="偏好场景列表"
                    ),
                ),
                (
                    "total_clicks",
                    models.PositiveIntegerField(default=0, verbose_name="总点击次数"),
                ),
                (
                    "total_executions",
                    models.PositiveIntegerField(default=0, verbose_name="总执行次数"),
                ),
                (
                    "active_days",
                    models.PositiveIntegerField(default=1, verbose_name="活跃天数"),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后活跃时间"),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="是否VIP会员"),
                ),
                (
                    "vip_level",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "普通"), (1, "基础"), (2, "高级"), (3, "企业")],
                        default=0,
                        verbose_name="会员等级",
                    ),
                ),
                (
                    "conversion_count",
                    models.PositiveIntegerField(default=0, verbose_name="付费转化次数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommend_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户推荐画像",
                "verbose_name_plural": "用户推荐画像",
                "db_table": "user_recommend_profile",
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, default="", max_length=64, verbose_name="会话ID"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("skill", "技能"),
                            ("article", "文章"),
                            ("promo", "推广卡片"),
                            ("scenario", "场景"),
                        ],
                        default="skill",
                        max_length=20,
                        verbose_name="目标类型",
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(db_index=True, verbose_name="目标ID"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("click", "点击"),
                            ("view", "浏览"),
                            ("select", "选择"),
                            ("execute", "执行"),
                            ("favorite", "收藏"),
                            ("share", "分享"),
                        ],
                        default="click",
                        max_length=20,
                        verbose_name="行为类型",
                    ),
                ),
                (
                    "skill_tier",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="技能层级"
                    ),
                ),
                (
                    "skill_category",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="技能分类"
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="关联场景"
                    ),
                ),
                (
                    "source_page",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="来源页面"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="停留时长(秒)"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户行为日志",
                "verbose_name_plural": "用户行为日志",
                "db_table": "user_behavior_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "target_type", "target_id"],
                        name="idx_user_target",
                    ),
                    models.Index(
                        fields=["session_id", "target_type"], name="idx_session_target"
                    ),
                    models.Index(
                        fields=["skill_tier", "created_at"], name="idx_tier_time"
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="idx_action_time"
                    ),
                ],
            },
        ),
    ]
