# Generated by Django 6.0.1 on 2026-05-28 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0016_promocard_userprofile_userbehaviorlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "order_no",
                    models.CharField(
                        db_index=True, max_length=40, unique=True, verbose_name="订单号"
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("per_use", "按次付费(¥19)"),
                            ("vip_monthly", "月度会员(¥99)"),
                            ("vip_yearly", "年度会员(¥599)"),
                            ("vip_enterprise", "企业定制(¥5999)"),
                        ],
                        default="per_use",
                        max_length=20,
                        verbose_name="订单类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("failed", "支付失败"),
                            ("refunded", "已退款"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.0,
                        max_digits=10,
                        verbose_name="金额(元)",
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.0,
                        max_digits=10,
                        verbose_name="原价(元)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="优惠额(元)",
                    ),
                ),
                (
                    "pay_channel",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="alipay/wechat/mock",
                        max_length=20,
                        verbose_name="支付渠道",
                    ),
                ),
                (
                    "pay_trade_no",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="交易号"
                    ),
                ),
                (
                    "pay_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        default="", max_length=100, verbose_name="订单标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付成功时间"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款时间"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付订单",
                "verbose_name_plural": "支付订单",
                "db_table": "payment_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserQuota",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "free_daily_remaining",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="免费每日剩余次数"
                    ),
                ),
                (
                    "free_daily_limit",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="免费每日上限"
                    ),
                ),
                (
                    "free_used_today",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="今日已用免费次数"
                    ),
                ),
                (
                    "quota_reset_date",
                    models.DateField(auto_now_add=True, verbose_name="配额重置日期"),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="是否VIP会员"),
                ),
                (
                    "vip_level",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "普通"), (1, "基础"), (2, "高级"), (3, "企业")],
                        default=0,
                        verbose_name="会员等级",
                    ),
                ),
                (
                    "vip_expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="会员到期时间"
                    ),
                ),
                (
                    "total_paid_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="付费使用总次数"
                    ),
                ),
                (
                    "total_free_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="免费使用总次数"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_quota",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户使用配额",
                "verbose_name_plural": "用户使用配额",
                "db_table": "user_usage_quota",
            },
        ),
        migrations.CreateModel(
            name="SkillHotnessSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "hour_key",
                    models.CharField(
                        db_index=True,
                        max_length=12,
                        verbose_name="小时标识(YYYYMMDDHH)",
                    ),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(default=0, verbose_name="点击次数"),
                ),
                (
                    "select_count",
                    models.PositiveIntegerField(default=0, verbose_name="选择次数"),
                ),
                (
                    "execute_count",
                    models.PositiveIntegerField(default=0, verbose_name="执行次数"),
                ),
                (
                    "share_count",
                    models.PositiveIntegerField(default=0, verbose_name="分享次数"),
                ),
                (
                    "raw_hotness",
                    models.FloatField(default=0.0, verbose_name="原始热度值"),
                ),
                (
                    "normalized_hotness",
                    models.FloatField(default=0.0, verbose_name="归一化热度(0~100)"),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        default=999, verbose_name="当前排名"
                    ),
                ),
                (
                    "trend",
                    models.SmallIntegerField(
                        default=0, verbose_name="趋势(-1下降/0平稳/1上升)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotness_snapshots",
                        to="auth_app.skillconfig",
                        verbose_name="技能",
                    ),
                ),
            ],
            options={
                "verbose_name": "技能热度快照",
                "verbose_name_plural": "技能热度快照",
                "db_table": "skill_hotness_snapshot",
                "ordering": ["-hour_key", "-normalized_hotness"],
                "indexes": [
                    models.Index(
                        fields=["hour_key", "-normalized_hotness"], name="idx_hour_hot"
                    ),
                    models.Index(fields=["hour_key", "rank"], name="idx_hour_rank"),
                ],
                "unique_together": {("skill", "hour_key")},
            },
        ),
    ]
