# Generated by Django 5.2.14 on 2026-05-28 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0017_paymentorder_userquota_skillhotnesssnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("per_use", "按次付费(¥19)"),
                            ("vip_monthly", "月度会员(¥99)"),
                            ("vip_yearly_199", "年度会员(¥199)"),
                            ("vip_yearly_599", "年度会员專享(¥599)"),
                            ("vip_enterprise", "企业定制(¥5999)"),
                            ("combo_security", "安全检测套餐(¥299)"),
                            ("combo_content", "内容安全套餐(¥398)"),
                            ("combo_enterprise_full", "企业全景套餐(¥2999)"),
                        ],
                        max_length=25,
                        unique=True,
                        verbose_name="套餐类型",
                    ),
                ),
                ("plan_name", models.CharField(max_length=50, verbose_name="套餐名称")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="售价(元)"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="原价(元)",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0=按次", verbose_name="有效天数"
                    ),
                ),
                (
                    "vip_level",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="会员等级"
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0=无限", verbose_name="每日限额"
                    ),
                ),
                (
                    "features",
                    models.JSONField(blank=True, default=list, verbose_name="功能列表"),
                ),
                (
                    "skill_categories",
                    models.JSONField(
                        blank=True, default=list, verbose_name="包含技能分类"
                    ),
                ),
                (
                    "included_skills_count",
                    models.PositiveIntegerField(default=0, verbose_name="包含技能数"),
                ),
                ("is_hot", models.BooleanField(default=False, verbose_name="热门推荐")),
                ("is_new", models.BooleanField(default=False, verbose_name="新品")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="标签文字"
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        blank=True,
                        default="#165DFF",
                        max_length=10,
                        verbose_name="标签颜色",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "会员套餐",
                "verbose_name_plural": "会员套餐",
                "db_table": "membership_plan",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("per_use", "按次付费(¥19)"),
                    ("vip_monthly", "月度会员(¥99)"),
                    ("vip_yearly_199", "年度会员(¥199)♦超值"),
                    ("vip_yearly_599", "年度会员专享(¥599)"),
                    ("vip_enterprise", "企业定制(¥5999)"),
                    ("combo_security", "安全检测套餐(¥299)"),
                    ("combo_content", "内容安全套餐(¥398)"),
                    ("combo_enterprise_full", "企业全景套餐(¥2999)"),
                ],
                default="per_use",
                max_length=25,
                verbose_name="订单类型",
            ),
        ),
        migrations.CreateModel(
            name="AffiliateRelationship",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "invite_code",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="邀请码"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "有效"), ("disabled", "停用")],
                        default="active",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="累计佣金(元)",
                    ),
                ),
                (
                    "withdrawn_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="已提现金额(元)",
                    ),
                ),
                (
                    "pending_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="待结算金额(元)",
                    ),
                ),
                (
                    "invitee_first_order_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="被邀首次付款时间"
                    ),
                ),
                (
                    "total_invitee_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="被邀人总订单数"
                    ),
                ),
                (
                    "total_invitee_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="被邀人总消费(元)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_inviter",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被邀请人",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_invited",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "分销关系",
                "verbose_name_plural": "分销关系",
                "db_table": "affiliate_relationship",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateWithdrawalRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="提现金额(元)"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="手续费(元)",
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="实际到账(元)",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="银行名称"
                    ),
                ),
                (
                    "account_no",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="账号"
                    ),
                ),
                (
                    "account_holder",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="户名"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "审核中"),
                            ("approved", "已通过"),
                            ("completed", "已到账"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="审核人"
                    ),
                ),
                (
                    "review_remark",
                    models.TextField(blank=True, default="", verbose_name="审核备注"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affiliate_rel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="auth_app.affiliaterelationship",
                        verbose_name="分销关系",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提现记录",
                "verbose_name_plural": "提现记录",
                "db_table": "affiliate_withdrawal_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=5,
                        verbose_name="佣金比例(%)",
                    ),
                ),
                (
                    "order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="订单金额(元)",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="佣金金额(元)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待结算"),
                            ("settled", "已结算"),
                            ("withdrawn", "已提现"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "settle_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结算时间"
                    ),
                ),
                (
                    "withdraw_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提现时间"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="auth_app.affiliaterelationship",
                        verbose_name="分销关系",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_records",
                        to="auth_app.paymentorder",
                        verbose_name="关联订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "佣金记录",
                "verbose_name_plural": "佣金记录",
                "db_table": "commission_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="affiliaterelationship",
            index=models.Index(fields=["inviter", "status"], name="idx_inviter_status"),
        ),
        migrations.AddIndex(
            model_name="affiliaterelationship",
            index=models.Index(fields=["invite_code"], name="idx_invite_code"),
        ),
        migrations.AddIndex(
            model_name="commissionrecord",
            index=models.Index(fields=["affiliate", "status"], name="idx_aff_status"),
        ),
        migrations.AddIndex(
            model_name="commissionrecord",
            index=models.Index(fields=["status", "created_at"], name="idx_status_time"),
        ),
    ]
