# Generated by Django 5.2.14 on 2026-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0018_affiliate_and_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPlatformStats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="日期"),
                ),
                (
                    "dau",
                    models.PositiveIntegerField(
                        default=0, verbose_name="DAU(活跃用户)"
                    ),
                ),
                (
                    "wau",
                    models.PositiveIntegerField(default=0, verbose_name="WAU(周活)"),
                ),
                (
                    "mau",
                    models.PositiveIntegerField(default=0, verbose_name="MAU(月活)"),
                ),
                (
                    "new_users",
                    models.PositiveIntegerField(default=0, verbose_name="新注册"),
                ),
                (
                    "total_users",
                    models.PositiveIntegerField(default=0, verbose_name="累计用户"),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(default=0, verbose_name="总会话数"),
                ),
                (
                    "avg_session_duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="平均会话长度(s)"
                    ),
                ),
                (
                    "total_clicks",
                    models.PositiveIntegerField(default=0, verbose_name="总点击"),
                ),
                (
                    "total_executions",
                    models.PositiveIntegerField(default=0, verbose_name="总执行"),
                ),
                (
                    "total_shares",
                    models.PositiveIntegerField(default=0, verbose_name="分享"),
                ),
                (
                    "free_uses",
                    models.PositiveIntegerField(default=0, verbose_name="免费使用"),
                ),
                (
                    "paid_uses",
                    models.PositiveIntegerField(default=0, verbose_name="付费使用"),
                ),
                (
                    "conversion_rate",
                    models.FloatField(default=0.0, verbose_name="付费转化率(%)"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="营收(元)",
                    ),
                ),
                (
                    "avg_revenue_per_user",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ARPU(元)",
                    ),
                ),
                (
                    "retention_d1",
                    models.FloatField(default=0.0, verbose_name="次留存(%)"),
                ),
                (
                    "retention_d7",
                    models.FloatField(default=0.0, verbose_name="7日留存(%)"),
                ),
                (
                    "retention_d30",
                    models.FloatField(default=0.0, verbose_name="30日留存(%)"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "日平台统计",
                "verbose_name_plural": "日平台统计",
                "db_table": "daily_platform_stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RevenueDailyStats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="日期"),
                ),
                (
                    "gross_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="总营收(元)",
                    ),
                ),
                (
                    "net_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="净营收(元)",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="退款金额(元)",
                    ),
                ),
                (
                    "order_count",
                    models.PositiveIntegerField(default=0, verbose_name="订单数"),
                ),
                (
                    "paid_order_count",
                    models.PositiveIntegerField(default=0, verbose_name="已付款订单"),
                ),
                (
                    "refund_order_count",
                    models.PositiveIntegerField(default=0, verbose_name="退款订单"),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="平均订单额(元)",
                    ),
                ),
                (
                    "conversion_rate",
                    models.FloatField(default=0.0, verbose_name="整体转化率(%)"),
                ),
                (
                    "per_use_orders",
                    models.PositiveIntegerField(default=0, verbose_name="按次订单"),
                ),
                (
                    "monthly_orders",
                    models.PositiveIntegerField(default=0, verbose_name="月呖订单"),
                ),
                (
                    "yearly_199_orders",
                    models.PositiveIntegerField(default=0, verbose_name="199年卡订单"),
                ),
                (
                    "yearly_599_orders",
                    models.PositiveIntegerField(default=0, verbose_name="599年卡订单"),
                ),
                (
                    "enterprise_orders",
                    models.PositiveIntegerField(default=0, verbose_name="企业订单"),
                ),
                (
                    "combo_security_orders",
                    models.PositiveIntegerField(default=0, verbose_name="安全套餐订单"),
                ),
                (
                    "combo_content_orders",
                    models.PositiveIntegerField(default=0, verbose_name="内容套餐订单"),
                ),
                (
                    "combo_enterprise_orders",
                    models.PositiveIntegerField(default=0, verbose_name="企业全景订单"),
                ),
                (
                    "commission_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="已支付佣金(元)",
                    ),
                ),
                (
                    "affiliate_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="分销营收(元)",
                    ),
                ),
                (
                    "vip_active_count",
                    models.PositiveIntegerField(default=0, verbose_name="VIP活跃数"),
                ),
                (
                    "new_vip_count",
                    models.PositiveIntegerField(default=0, verbose_name="新增VIP"),
                ),
                (
                    "vip_renewal_count",
                    models.PositiveIntegerField(default=0, verbose_name="VIP续费"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "营收日统计",
                "verbose_name_plural": "营收日统计",
                "db_table": "revenue_daily_stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AreaClickStats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("carousel", "轮播区(Top9)"),
                            ("recommendation", "为你推荐"),
                            ("new_for_you", "新品专区"),
                            ("promo_feed", "推广信息流"),
                            ("article_cta", "文章CTA"),
                            ("skill_grid", "技能网格"),
                            ("search_result", "搜索结果"),
                            ("hot_skills_list", "热门列表"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="区域类型",
                    ),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="曝光量"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="点击量"),
                ),
                (
                    "unique_visitors",
                    models.PositiveIntegerField(default=0, verbose_name="UV"),
                ),
                (
                    "click_rate",
                    models.FloatField(default=0.0, verbose_name="点击率(%)"),
                ),
                (
                    "avg_position",
                    models.FloatField(default=0.0, verbose_name="平均点击位置"),
                ),
                (
                    "top_clicked_item_id",
                    models.CharField(
                        default="", max_length=50, verbose_name="热门点击项ID"
                    ),
                ),
                (
                    "top_clicked_item_name",
                    models.CharField(
                        default="", max_length=100, verbose_name="热门点击项名"
                    ),
                ),
                (
                    "top_item_clicks",
                    models.PositiveIntegerField(default=0, verbose_name="热门项点击数"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "区域点击统计",
                "verbose_name_plural": "区域点击统计",
                "db_table": "area_click_stats",
                "ordering": ["-date", "area_type"],
                "indexes": [
                    models.Index(fields=["date", "area_type"], name="idx_date_area")
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillDailyStats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                (
                    "skill_id",
                    models.PositiveIntegerField(db_index=True, verbose_name="技能ID"),
                ),
                (
                    "skill_name",
                    models.CharField(
                        default="", max_length=100, verbose_name="技能名称"
                    ),
                ),
                (
                    "skill_tier",
                    models.CharField(default="", max_length=50, verbose_name="属性"),
                ),
                (
                    "skill_category",
                    models.CharField(default="", max_length=50, verbose_name="分类"),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="曝光量"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="点击量"),
                ),
                (
                    "executions",
                    models.PositiveIntegerField(default=0, verbose_name="使用量"),
                ),
                (
                    "shares",
                    models.PositiveIntegerField(default=0, verbose_name="分享量"),
                ),
                (
                    "click_rate",
                    models.FloatField(default=0.0, verbose_name="点击率(%)"),
                ),
                (
                    "execution_rate",
                    models.FloatField(default=0.0, verbose_name="使用率(%)"),
                ),
                (
                    "conversion_rate",
                    models.FloatField(default=0.0, verbose_name="付费转化率(%)"),
                ),
                ("hotness", models.FloatField(default=0.0, verbose_name="热度值")),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="排名"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="营收(元)",
                    ),
                ),
            ],
            options={
                "verbose_name": "技能日统计",
                "verbose_name_plural": "技能日统计",
                "db_table": "skill_daily_stats",
                "ordering": ["-date", "-clicks"],
                "indexes": [
                    models.Index(fields=["date", "skill_id"], name="idx_date_skill"),
                    models.Index(fields=["date", "-clicks"], name="idx_date_clicks"),
                    models.Index(
                        fields=["date", "skill_category"], name="idx_date_cat"
                    ),
                    models.Index(fields=["date", "skill_tier"], name="idx_date_tier"),
                ],
            },
        ),
    ]
