# Generated by Django 6.0.5 on 2026-05-28 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0019_data_stats_monitoring"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABTestAssignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="会话ID"
                    ),
                ),
                ("variant", models.CharField(max_length=50, verbose_name="分配变体")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "A/B测试分配",
                "verbose_name_plural": "A/B测试分配",
                "db_table": "ab_test_assignment",
            },
        ),
        migrations.CreateModel(
            name="ABTestEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("impression", "曝光"),
                            ("click", "点击"),
                            ("execute", "执行"),
                            ("payment_start", "开始支付"),
                            ("payment_complete", "支付完成"),
                            ("share", "分享"),
                            ("time_on_page", "页面停留"),
                        ],
                        max_length=20,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="目标ID"
                    ),
                ),
                ("value", models.FloatField(default=0, verbose_name="值")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "A/B测试事件",
                "verbose_name_plural": "A/B测试事件",
                "db_table": "ab_test_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ABTestExperiment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="实验名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("rec_strategy", "推荐策略"),
                            ("promo_card", "推广卡片"),
                            ("ui_layout", "UI布局"),
                        ],
                        max_length=30,
                        verbose_name="测试类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("running", "进行中"),
                            ("paused", "已暂停"),
                            ("completed", "已完成"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "traffic_allocation",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="流量分配(%)"
                    ),
                ),
                (
                    "variants_config",
                    models.JSONField(default=list, verbose_name="变体配置"),
                ),
                (
                    "control_group_pct",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="对照组(%)"
                    ),
                ),
                (
                    "metric_primary",
                    models.CharField(
                        default="conversion_rate",
                        max_length=30,
                        verbose_name="主要指标",
                    ),
                ),
                (
                    "metric_secondary",
                    models.JSONField(default=list, verbose_name="次要指标"),
                ),
                (
                    "sample_size_target",
                    models.PositiveIntegerField(default=500, verbose_name="目标样本数"),
                ),
                (
                    "confidence_level",
                    models.FloatField(default=0.95, verbose_name="置信度"),
                ),
                (
                    "min_detectable_effect",
                    models.FloatField(default=0.05, verbose_name="最小检测效应"),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "winner_variant",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="菜胜变体"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "A/B测试实验",
                "verbose_name_plural": "A/B测试实验",
                "db_table": "ab_test_experiment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCardImpressionLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="会话ID"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, default="", max_length=25, verbose_name="展示位置"
                    ),
                ),
                ("shown_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clicked",
                    models.BooleanField(default=False, verbose_name="是否点击"),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="点击时间"
                    ),
                ),
                (
                    "converted",
                    models.BooleanField(default=False, verbose_name="是否转化"),
                ),
            ],
            options={
                "verbose_name": "推广卡片曝光日志",
                "verbose_name_plural": "推广卡片曝光日志",
                "db_table": "promo_card_impression_log",
                "ordering": ["-shown_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCardScheduleRule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user_segment",
                    models.CharField(
                        choices=[
                            ("all", "所有用户"),
                            ("new", "新用户(<3天)"),
                            ("active", "活跃用户"),
                            ("vip", "VIP会员"),
                            ("non_payer", "未付费"),
                            ("high_intent", "高意图"),
                        ],
                        default="all",
                        max_length=15,
                        verbose_name="用户分层",
                    ),
                ),
                (
                    "position_priority",
                    models.JSONField(default=list, verbose_name="位置优先级"),
                ),
                (
                    "show_frequency_max",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="每日最多显示"
                    ),
                ),
                (
                    "show_interval_hours",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="间隔小时数"
                    ),
                ),
                (
                    "cooldown_after_click",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="点击后冷却(h)"
                    ),
                ),
                ("time_rules", models.JSONField(default=dict, verbose_name="时间规则")),
                (
                    "device_rules",
                    models.JSONField(default=dict, verbose_name="设备规则"),
                ),
                (
                    "weight_multiplier",
                    models.FloatField(default=1.0, verbose_name="权重加成"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "priority_score",
                    models.PositiveSmallIntegerField(default=50, verbose_name="优先级"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "推广卡片调度规则",
                "verbose_name_plural": "推广卡片调度规则",
                "db_table": "promo_card_schedule_rule",
                "ordering": ["-priority_score"],
            },
        ),
        migrations.DeleteModel(
            name="AgentConfig",
        ),
        migrations.RemoveField(
            model_name="agentmessage",
            name="session",
        ),
        migrations.RemoveField(
            model_name="agentsession",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="agentverificationrecord",
            name="agent_verif_article_f5c864_idx",
        ),
        migrations.RemoveIndex(
            model_name="contentauditlog",
            name="idx_audit_result",
        ),
        migrations.RemoveIndex(
            model_name="contentauditlog",
            name="idx_audit_risk",
        ),
        migrations.RemoveIndex(
            model_name="contentauditlog",
            name="idx_audit_source",
        ),
        migrations.RemoveIndex(
            model_name="contentauditlog",
            name="idx_audit_created",
        ),
        migrations.RemoveIndex(
            model_name="contentauditlog",
            name="idx_audit_user",
        ),
        migrations.DeleteModel(
            name="ContentAuditLog",
        ),
        migrations.RemoveField(
            model_name="frontendusermanager",
            name="banned_by",
        ),
        migrations.RemoveField(
            model_name="frontendusermanager",
            name="user",
        ),
        migrations.RemoveField(
            model_name="functioncard",
            name="knowledge_base",
        ),
        migrations.RemoveField(
            model_name="hotcontenttemplate",
            name="creator_id",
        ),
        migrations.DeleteModel(
            name="IMAutoReply",
        ),
        migrations.RemoveIndex(
            model_name="immessage",
            name="idx_im_session_time",
        ),
        migrations.RemoveIndex(
            model_name="immessage",
            name="idx_im_read",
        ),
        migrations.DeleteModel(
            name="IMMessage",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="operationlog",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="permissionauditlog",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="permissioninterceptlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="PrivacyAgreement",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_by",
        ),
        migrations.RemoveIndex(
            model_name="regexrule",
            name="idx_rule_category",
        ),
        migrations.RemoveIndex(
            model_name="regexrule",
            name="idx_rule_enabled",
        ),
        migrations.RemoveIndex(
            model_name="regexrule",
            name="idx_rule_severity",
        ),
        migrations.RemoveIndex(
            model_name="regexrule",
            name="idx_rule_match_count",
        ),
        migrations.RemoveField(
            model_name="regextestcase",
            name="rule",
        ),
        migrations.RemoveField(
            model_name="role",
            name="users",
        ),
        migrations.RemoveIndex(
            model_name="securityalert",
            name="idx_alert_severity",
        ),
        migrations.RemoveIndex(
            model_name="securityalert",
            name="idx_alert_status",
        ),
        migrations.RemoveIndex(
            model_name="securityalert",
            name="idx_alert_category",
        ),
        migrations.RemoveIndex(
            model_name="securityalert",
            name="idx_alert_triggered",
        ),
        migrations.DeleteModel(
            name="SecurityAlert",
        ),
        migrations.DeleteModel(
            name="SecurityReport",
        ),
        migrations.DeleteModel(
            name="SecurityScore",
        ),
        migrations.RemoveIndex(
            model_name="securitytestcase",
            name="idx_test_case_category",
        ),
        migrations.RemoveIndex(
            model_name="securitytestcase",
            name="idx_test_case_status",
        ),
        migrations.RemoveIndex(
            model_name="securitytestcase",
            name="idx_test_case_severity",
        ),
        migrations.DeleteModel(
            name="SecurityTestCase",
        ),
        migrations.RemoveIndex(
            model_name="securityvulnerability",
            name="idx_vuln_status",
        ),
        migrations.RemoveIndex(
            model_name="securityvulnerability",
            name="idx_vuln_severity",
        ),
        migrations.RemoveIndex(
            model_name="securityvulnerability",
            name="idx_vuln_category",
        ),
        migrations.RemoveIndex(
            model_name="securityvulnerability",
            name="idx_vuln_created",
        ),
        migrations.DeleteModel(
            name="SecurityVulnerability",
        ),
        migrations.RemoveField(
            model_name="systemsecurityconfig",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="userbrowserecord",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userconsentrecord",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="userconsentrecord",
            name="idx_consent_user_type",
        ),
        migrations.RemoveIndex(
            model_name="userconsentrecord",
            name="idx_consent_status",
        ),
        migrations.DeleteModel(
            name="UserConsentRecord",
        ),
        migrations.DeleteModel(
            name="VoiceAssistantConfig",
        ),
        migrations.RemoveField(
            model_name="withdrawalrecord",
            name="user_id",
        ),
        migrations.AddField(
            model_name="abtestassignment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ab_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="abtestevent",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="auth_app.abtestassignment",
            ),
        ),
        migrations.AddField(
            model_name="abtestevent",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="auth_app.abtestexperiment",
            ),
        ),
        migrations.AddField(
            model_name="abtestassignment",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="auth_app.abtestexperiment",
            ),
        ),
        migrations.AddField(
            model_name="promocardimpressionlog",
            name="promo_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impression_logs",
                to="auth_app.promocard",
            ),
        ),
        migrations.AddField(
            model_name="promocardimpressionlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promo_impressions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="promocardschedulerule",
            name="promo_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_rules",
                to="auth_app.promocard",
            ),
        ),
        migrations.DeleteModel(
            name="AgentMessage",
        ),
        migrations.DeleteModel(
            name="AgentSession",
        ),
        migrations.RemoveField(
            model_name="agentverificationrecord",
            name="operator",
        ),
        migrations.DeleteModel(
            name="FrontendUserManager",
        ),
        migrations.DeleteModel(
            name="FunctionCard",
        ),
        migrations.DeleteModel(
            name="HotContentTemplate",
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
        migrations.DeleteModel(
            name="OperationLog",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="PaymentRecord",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="PermissionAuditLog",
        ),
        migrations.DeleteModel(
            name="PermissionInterceptLog",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="RegexRule",
        ),
        migrations.DeleteModel(
            name="RegexTestCase",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="SystemSecurityConfig",
        ),
        migrations.DeleteModel(
            name="UserBrowseRecord",
        ),
        migrations.DeleteModel(
            name="WithdrawalRecord",
        ),
        migrations.AddIndex(
            model_name="abtestevent",
            index=models.Index(
                fields=["experiment", "assignment", "event_type"], name="idx_exp_evt"
            ),
        ),
        migrations.AddIndex(
            model_name="abtestassignment",
            index=models.Index(
                fields=["experiment", "session_id"], name="idx_exp_session"
            ),
        ),
        migrations.AddIndex(
            model_name="abtestassignment",
            index=models.Index(
                fields=["experiment", "variant"], name="idx_exp_variant"
            ),
        ),
        migrations.AddIndex(
            model_name="promocardimpressionlog",
            index=models.Index(
                fields=["promo_card", "user", "shown_at"], name="idx_promo_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="promocardimpressionlog",
            index=models.Index(
                fields=["session_id", "clicked"], name="idx_session_clicked"
            ),
        ),
        migrations.DeleteModel(
            name="AgentVerificationRecord",
        ),
    ]
