# Generated by Django 6.0.1 on 2026-05-28 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0020_abtest_and_promo_optimization"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareCopyrightApplication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "software_name",
                    models.CharField(max_length=100, verbose_name="软件名称"),
                ),
                (
                    "software_type",
                    models.CharField(
                        choices=[
                            ("ai_detection_platform", "AI内容检测平台"),
                            ("ai_recommendation_engine", "AI智能推荐引擎"),
                            ("enterprise_security_system", "企业安全管理系统"),
                            ("data_monitoring_dashboard", "数据监控可视化平台"),
                            ("affiliate_marketing_system", "分销营销系统"),
                        ],
                        max_length=35,
                        verbose_name="软件类型",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="V1.0", max_length=10, verbose_name="版本号"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="功能描述"),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        default="Python/Django/React/TypeScript",
                        max_length=200,
                        verbose_name="技术栈栈",
                    ),
                ),
                (
                    "lines_of_code",
                    models.PositiveIntegerField(default=0, verbose_name="代码行数(行)"),
                ),
                (
                    "development_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="开发完成日期"
                    ),
                ),
                (
                    "first_public_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="首次发表日期"
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(max_length=50, verbose_name="申请人"),
                ),
                (
                    "applicant_type",
                    models.CharField(
                        choices=[
                            ("individual", "自然人"),
                            ("corporate", "法人"),
                            ("institution", "事业单位"),
                        ],
                        default="corporate",
                        max_length=10,
                        verbose_name="申请人类型",
                    ),
                ),
                (
                    "applicant_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="身份证号/号",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=13,
                        unique=True,
                        verbose_name="登记号",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, default="", max_length=13, verbose_name="证书号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("under_review", "审核中"),
                            ("accepted", "已受理"),
                            ("certificate_issued", "证书已发"),
                            ("rejected", "已驳回"),
                        ],
                        default="draft",
                        max_length=18,
                        verbose_name="状态",
                    ),
                ),
                (
                    "submit_to",
                    models.CharField(
                        choices=[
                            ("csdncc", "中国软件登记"),
                            ("sipa", "知产知保"),
                            ("copyright_center", "版权中心"),
                        ],
                        default="csdncc",
                        max_length=20,
                        verbose_name="提交机关",
                    ),
                ),
                (
                    "documents",
                    models.JSONField(blank=True, default=list, verbose_name="附件清单"),
                ),
                (
                    "source_code_repo",
                    models.URLField(blank=True, default="", verbose_name="源代码仓库"),
                ),
                (
                    "screenshots",
                    models.JSONField(blank=True, default=list, verbose_name="截图"),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, default="", verbose_name="审核意见"),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="copyright_certs/",
                        verbose_name="证书文件",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "软件著保申请",
                "verbose_name_plural": "软件著保申请",
                "db_table": "software_copyright_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="企业名称")),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="公司全称"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="邮箱"
                    ),
                ),
                (
                    "business_license",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="营业执照号"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, default="", max_length=25, verbose_name="纳税号"
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("starter", "企业基础版(¥2999)"),
                            ("professional", "企业专业版(¥19999)"),
                            ("enterprise_premium", "企业高级版(¥19999)"),
                        ],
                        default="starter",
                        max_length=20,
                        verbose_name="套餐类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "试用中"),
                            ("active", "正常"),
                            ("suspended", "已停用"),
                            ("expired", "已过期"),
                        ],
                        default="trial",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "api_calls_limit",
                    models.PositiveIntegerField(
                        default=10000, verbose_name="API调用限额(每月)"
                    ),
                ),
                (
                    "api_calls_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="API已调用(本月)"
                    ),
                ),
                (
                    "members_limit",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="成员数限制"
                    ),
                ),
                (
                    "concurrent_sessions",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="并发会话数"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="余额(元)",
                    ),
                ),
                (
                    "total_recharged",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="总充值(元)",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="总消费(元)",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="试用截止时间"
                    ),
                ),
                (
                    "paid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="到期时间"
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(default=False, verbose_name="自动续费"),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, default="", verbose_name="Webhook URL"),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Webhook Secret",
                    ),
                ),
                (
                    "ip_whitelist",
                    models.TextField(blank=True, default="", verbose_name="IP白名单"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_admin",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="企业管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业账号",
                "verbose_name_plural": "企业账号",
                "db_table": "enterprise_account",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseAPIKey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="密钥名称")),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("production", "正式环境"),
                            ("sandbox", "测试环境"),
                            ("readonly", "只读密钥"),
                        ],
                        default="production",
                        max_length=15,
                        verbose_name="密钥类型",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="密钥Hash",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        default="yjd_", max_length=8, verbose_name="密钥前缀"
                    ),
                ),
                (
                    "key_last_4",
                    models.CharField(
                        default="****", max_length=4, verbose_name="密钥后4位"
                    ),
                ),
                (
                    "allowed_endpoints",
                    models.JSONField(blank=True, default=list, verbose_name="允许接口"),
                ),
                (
                    "rate_limit_per_minute",
                    models.PositiveSmallIntegerField(
                        default=120, verbose_name="分钟限额"
                    ),
                ),
                (
                    "daily_quota",
                    models.PositiveIntegerField(default=5000, verbose_name="日限额"),
                ),
                (
                    "monthly_quota",
                    models.PositiveIntegerField(default=50000, verbose_name="月限额"),
                ),
                (
                    "ip_restrictions",
                    models.TextField(blank=True, default="", verbose_name="IP限制"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用"
                    ),
                ),
                (
                    "total_calls",
                    models.PositiveIntegerField(default=0, verbose_name="总调用次数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="auth_app.enterpriseaccount",
                        verbose_name="企业",
                    ),
                ),
            ],
            options={
                "verbose_name": "API密钥",
                "verbose_name_plural": "API密钥",
                "db_table": "enterprise_api_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseBatchRecharge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "recharge_type",
                    models.CharField(
                        choices=[
                            ("balance", "余额充值"),
                            ("api_quota", "API额额度补充"),
                            ("plan_upgrade", "升级套餐"),
                            ("extension", "续费延长"),
                        ],
                        default="balance",
                        max_length=15,
                        verbose_name="充值类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="金额(元)"
                    ),
                ),
                (
                    "api_calls_added",
                    models.PositiveIntegerField(
                        default=0, verbose_name="补充API调用次数"
                    ),
                ),
                (
                    "days_added",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="补充天数"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "银行汇款"),
                            ("alipay", "支付宝"),
                            ("wechat", "微信支付"),
                            ("system", "系统充值"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="交易号"
                    ),
                ),
                (
                    "invoice_requested",
                    models.BooleanField(default=False, verbose_name="是否开票"),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="发票号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("approved", "已审核通过"),
                            ("completed", "已完成"),
                            ("rejected", "已拒绝"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="审核人"
                    ),
                ),
                (
                    "review_remark",
                    models.TextField(blank=True, default="", verbose_name="审核备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recharges",
                        to="auth_app.enterpriseaccount",
                        verbose_name="企业",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_recharges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作员",
                    ),
                ),
            ],
            options={
                "verbose_name": "批量充值",
                "verbose_name_plural": "批量充值",
                "db_table": "enterprise_batch_recharge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "创始人"),
                            ("admin", "管理员"),
                            ("developer", "开发者"),
                            ("analyst", "分析师"),
                            ("viewer", "只读用户"),
                        ],
                        default="developer",
                        max_length=15,
                        verbose_name="角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "正常"),
                            ("pending", "待接受"),
                            ("disabled", "已禁用"),
                            ("removed", "已移除"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="部门"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="职位"
                    ),
                ),
                (
                    "api_daily_limit",
                    models.PositiveIntegerField(default=500, verbose_name="API日限额"),
                ),
                (
                    "api_monthly_limit",
                    models.PositiveIntegerField(default=5000, verbose_name="API月限额"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="auth_app.enterpriseaccount",
                        verbose_name="企业",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_enterprise_members",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业成员",
                "verbose_name_plural": "企业成员",
                "db_table": "enterprise_member",
                "ordering": ["role", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseUsageLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("api_call", "API调用"),
                            ("skill_execute", "技能执行"),
                            ("report_download", "报告下载"),
                            ("storage_usage", "存储使用"),
                            ("member_seat", "成员位置"),
                        ],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="接口路径"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="GET", max_length=10, verbose_name="HTTP方法"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="消耗量"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="组成本(元)",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="请求ID",
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(default=0, verbose_name="响应时间(ms)"),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        default=200, verbose_name="状态码"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="auth_app.enterpriseapikey",
                        verbose_name="API密钥",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="auth_app.enterpriseaccount",
                        verbose_name="企业",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="auth_app.enterprisemember",
                        verbose_name="操作成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用日志",
                "verbose_name_plural": "使用日志",
                "db_table": "enterprise_usage_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="enterpriseaccount",
            index=models.Index(fields=["admin_user"], name="idx_ent_admin"),
        ),
        migrations.AddIndex(
            model_name="enterpriseaccount",
            index=models.Index(
                fields=["status", "plan_type"], name="idx_ent_status_plan"
            ),
        ),
        migrations.AddIndex(
            model_name="enterpriseaccount",
            index=models.Index(fields=["paid_until"], name="idx_ent_paid_until"),
        ),
        migrations.AddIndex(
            model_name="enterprisemember",
            index=models.Index(fields=["enterprise", "role"], name="idx_mem_ent_role"),
        ),
        migrations.AddIndex(
            model_name="enterprisemember",
            index=models.Index(fields=["user", "status"], name="idx_mem_user_status"),
        ),
        migrations.AlterUniqueTogether(
            name="enterprisemember",
            unique_together={("enterprise", "user")},
        ),
        migrations.AddIndex(
            model_name="enterpriseusagelog",
            index=models.Index(
                fields=["enterprise", "resource_type", "created_at"],
                name="idx_use_ent_res_time",
            ),
        ),
        migrations.AddIndex(
            model_name="enterpriseusagelog",
            index=models.Index(
                fields=["api_key", "created_at"], name="idx_use_api_time"
            ),
        ),
    ]
