# Generated by Django 6.0.5 on 2026-05-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0022_agentconfig_imautoreply_privacyagreement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginlog",
            name="login_time",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="登录时间"
            ),
        ),
    ]
