# Generated by Django 6.0.1 on 2026-05-29 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0023_fix_login_time_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstOrderPromo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        default="新人首单优惠", max_length=100, verbose_name="活动名称"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "百分比折扣"), ("fixed", "固定金额减免")],
                        default="percent",
                        max_length=20,
                        verbose_name="折扣类型",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=10,
                        verbose_name="折扣值",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=10,
                        verbose_name="最大优惠金额(元)",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.0,
                        max_digits=10,
                        verbose_name="最低订单金额(元)",
                    ),
                ),
                (
                    "applicable_types",
                    models.JSONField(default=list, verbose_name="适用订单类型"),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "total_limit",
                    models.PositiveIntegerField(
                        default=0, help_text="0=无限制", verbose_name="总使用次数限制"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="已使用次数"),
                ),
                (
                    "per_user_limit",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="每人只能用一次",
                        verbose_name="每人限用次数",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活动中"),
                            ("paused", "已暂停"),
                            ("expired", "已结束"),
                        ],
                        default="active",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="额外配置"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "首单优惠活动",
                "verbose_name_plural": "首单优惠活动",
                "db_table": "first_order_promo",
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "coupon_code",
                    models.CharField(
                        db_index=True, max_length=32, unique=True, verbose_name="优惠码"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        default="unused",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="实际优惠金额",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                ("expire_at", models.DateTimeField(verbose_name="过期时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_coupon",
                        to="auth_app.paymentorder",
                        verbose_name="使用的订单",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="auth_app.firstorderpromo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "db_table": "user_coupon",
                "unique_together": {("user", "promo")},
            },
        ),
    ]
