# Generated by Django 6.0.5 on 2026-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0024_add_first_order_promo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="firstorderpromo",
            index=models.Index(fields=["status"], name="idx_promo_status"),
        ),
        migrations.AddIndex(
            model_name="firstorderpromo",
            index=models.Index(
                fields=["start_time", "end_time"], name="idx_promo_time_range"
            ),
        ),
        migrations.AddIndex(
            model_name="firstorderpromo",
            index=models.Index(
                fields=["status", "start_time", "end_time"], name="idx_promo_active"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_payment_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(fields=["status"], name="idx_payment_status"),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(fields=["order_type"], name="idx_payment_order_type"),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["user", "status"], name="idx_payment_user_status"
            ),
        ),
    ]
