# Generated by Django 6.0.1 on 2026-05-30 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0025_add_perf_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("per_use", "按次付费(¥19)"),
                    ("vip_monthly", "月度会员(¥99)"),
                    ("vip_yearly_199", "年度会员(¥199)♦超值"),
                    ("vip_yearly_599", "年度会员专享(¥599)"),
                    ("vip_enterprise", "企业定制(¥5999)"),
                    ("combo_security", "安全检测套餐(¥299)"),
                    ("combo_content", "内容安全套餐(¥398)"),
                    ("combo_enterprise_full", "企业全景套餐(¥2999)"),
                    ("vip_monthly_trial", "月度会员首月特惠(¥9.9)"),
                    ("digital_prompt_pack", "提示词大礼包(¥9.9)"),
                    ("digital_handbook", "安全开发手册(¥19.9)"),
                    ("digital_toolkit", "企业安全工具包(¥29.9)"),
                ],
                default="per_use",
                max_length=25,
                verbose_name="订单类型",
            ),
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1星"),
                            (2, "2星"),
                            (3, "3星"),
                            (4, "4星"),
                            (5, "5星"),
                        ],
                        default=5,
                        verbose_name="评分",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("general", "综合反馈"),
                            ("agent_quality", "Agent回答质量"),
                            ("agent_speed", "Agent响应速度"),
                            ("product_suggestion", "产品建议"),
                            ("bug_report", "问题反馈"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="反馈类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="反馈内容"),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="关联会话ID"
                    ),
                ),
                (
                    "agent_response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="响应时间(ms)"
                    ),
                ),
                (
                    "query_text",
                    models.TextField(blank=True, default="", verbose_name="用户提问"),
                ),
                (
                    "agent_answer_preview",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Agent回答摘要",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="是否已解决"),
                ),
                (
                    "admin_reply",
                    models.TextField(blank=True, default="", verbose_name="管理员回复"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "db_table": "user_feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_feedback_user_time"
                    ),
                    models.Index(fields=["feedback_type"], name="idx_feedback_type"),
                    models.Index(fields=["rating"], name="idx_feedback_rating"),
                ],
            },
        ),
    ]
