# Generated by Django 6.0.1 on 2026-05-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0026_alter_paymentorder_order_type_userfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("per_use", "按次付费(¥19)"),
                    ("vip_monthly", "月度会员(¥99)"),
                    ("vip_yearly_199", "年度会员(¥199)♦超值"),
                    ("vip_yearly_599", "年度会员专享(¥599)"),
                    ("vip_enterprise", "企业定制(¥5999)"),
                    ("combo_security", "安全检测套餐(¥299)"),
                    ("combo_content", "内容安全套餐(¥398)"),
                    ("combo_enterprise_full", "企业全景套餐(¥2999)"),
                    ("vip_monthly_trial", "月度会员首月特惠(¥9.9)"),
                    ("digital_prompt_pack", "提示词大礼包(¥9.9)"),
                    ("digital_handbook", "安全开发手册(¥19.9)"),
                    ("digital_toolkit", "企业安全工具包(¥29.9)"),
                    ("enterprise_rag_deploy", "企业私有RAG部署(¥5000起)"),
                    ("enterprise_agent_dev", "定制Agent开发(¥10000起)"),
                    ("course_agent_dev", "AI Agent开发实战课(¥299)"),
                    ("course_rag_intro", "RAG搭建入门课(¥99)"),
                    ("ad_cooperation", "广告合作(面议)"),
                    ("kol_cooperation", "KOL合作(面议)"),
                ],
                default="per_use",
                max_length=25,
                verbose_name="订单类型",
            ),
        ),
    ]
