# Generated by Django 6.0.1 on 2026-05-30 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0027_alter_paymentorder_order_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("enterprise_rag", "企业RAG部署咨询"),
                            ("enterprise_agent", "企业Agent开发咨询"),
                            ("ad_cooperation", "广告合作咨询"),
                            ("kol_cooperation", "KOL合作申请"),
                        ],
                        max_length=30,
                        verbose_name="咨询类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("contacted", "已联系"),
                            ("converted", "已转化"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="公司名称"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=100, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="联系电话"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="邮箱"
                    ),
                ),
                (
                    "requirement",
                    models.TextField(blank=True, default="", verbose_name="需求描述"),
                ),
                (
                    "ad_type",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="广告类型"
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="预算范围"
                    ),
                ),
                (
                    "kol_target",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="目标合作KOL",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="所在平台"
                    ),
                ),
                (
                    "followers",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="粉丝数量"
                    ),
                ),
                (
                    "cooperation_intent",
                    models.TextField(blank=True, default="", verbose_name="合作意向"),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, default="", verbose_name="管理员备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_inquiries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商务咨询",
                "verbose_name_plural": "商务咨询",
                "db_table": "business_inquiry",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["inquiry_type", "status"],
                        name="idx_inquiry_type_status",
                    ),
                    models.Index(fields=["-created_at"], name="idx_inquiry_created"),
                ],
            },
        ),
    ]
