# Generated by Django 6.0.1 on 2026-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0028_add_business_inquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="course_meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="课程元信息(大纲/课时/难度)",
            ),
        ),
    ]
