# Generated by Django 6.0.1 on 2026-05-31 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0029_add_course_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICallRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key_id", models.IntegerField(verbose_name="API Key ID")),
                ("window_start", models.DateTimeField(verbose_name="窗口开始时间")),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="窗口内调用次数"
                    ),
                ),
            ],
            options={
                "db_table": "api_call_rate_limit",
                "unique_together": {("api_key_id", "window_start")},
            },
        ),
        migrations.CreateModel(
            name="DeveloperAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="公司/组织"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, default="", verbose_name="网站"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="联系邮箱"
                    ),
                ),
                (
                    "use_case",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="使用场景描述",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "免费版"),
                            ("pro", "专业版(¥99/月)"),
                            ("team", "团队版(¥299/月)"),
                            ("unlimited", "无限版"),
                        ],
                        default="free",
                        max_length=15,
                        verbose_name="套餐等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "正常"),
                            ("suspended", "已停用"),
                            ("expired", "已过期"),
                        ],
                        default="active",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "daily_quota",
                    models.PositiveIntegerField(default=100, verbose_name="日调用限额"),
                ),
                (
                    "monthly_quota",
                    models.PositiveIntegerField(
                        default=3000, verbose_name="月调用限额"
                    ),
                ),
                (
                    "calls_today",
                    models.PositiveIntegerField(default=0, verbose_name="今日已用"),
                ),
                (
                    "calls_this_month",
                    models.PositiveIntegerField(default=0, verbose_name="本月已用"),
                ),
                (
                    "calls_today_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="今日日期（用于重置）"
                    ),
                ),
                (
                    "total_calls",
                    models.PositiveIntegerField(default=0, verbose_name="累计调用次数"),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, default="", verbose_name="回调通知URL"),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "开发者账号",
                "verbose_name_plural": "开发者账号",
                "db_table": "developer_account",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeveloperAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="密钥名称")),
                (
                    "key_type",
                    models.CharField(
                        choices=[("production", "正式环境"), ("sandbox", "测试环境")],
                        default="production",
                        max_length=15,
                        verbose_name="密钥类型",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="密钥Hash(SHA-256)",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        default="yjdp_", max_length=8, verbose_name="密钥前缀"
                    ),
                ),
                (
                    "key_last_4",
                    models.CharField(
                        default="****", max_length=4, verbose_name="密钥后4位"
                    ),
                ),
                (
                    "allowed_apis",
                    models.JSONField(
                        blank=True, default=list, verbose_name="允许调用的API列表"
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="分钟速率限制"
                    ),
                ),
                (
                    "daily_quota",
                    models.PositiveIntegerField(
                        default=0, verbose_name="日限额（覆盖账号默认）"
                    ),
                ),
                (
                    "ip_whitelist",
                    models.TextField(
                        blank=True, default="", verbose_name="IP白名单（空=不限制）"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用时间"
                    ),
                ),
                (
                    "last_used_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="最后使用IP"
                    ),
                ),
                (
                    "total_calls",
                    models.PositiveIntegerField(default=0, verbose_name="总调用次数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="撤销时间"
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="auth_app.developeraccount",
                        verbose_name="开发者",
                    ),
                ),
            ],
            options={
                "verbose_name": "开发者API密钥",
                "verbose_name_plural": "开发者API密钥",
                "db_table": "developer_api_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeveloperUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("detect_text", "AI文本检测"),
                            ("detect_image", "AI图像检测"),
                            ("agent_chat", "Agent对话"),
                            ("rag_search", "RAG检索"),
                            ("rag_ask", "RAG问答"),
                            ("skill_execute", "技能执行"),
                        ],
                        max_length=20,
                        verbose_name="API类型",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="接口路径"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="POST", max_length=10, verbose_name="HTTP方法"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="请求ID",
                    ),
                ),
                (
                    "input_preview",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="输入摘要"
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(default=0, verbose_name="响应时间(ms)"),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        default=200, verbose_name="HTTP状态码"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("rate_limited", "限流"),
                            ("auth_failed", "认证失败"),
                            ("quota_exceeded", "配额耗尽"),
                            ("server_error", "服务端错误"),
                        ],
                        default="success",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(default=0, verbose_name="消耗Token数"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="费用(元)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="客户端IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="错误信息"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="auth_app.developerapikey",
                        verbose_name="API密钥",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="auth_app.developeraccount",
                        verbose_name="开发者",
                    ),
                ),
            ],
            options={
                "verbose_name": "开发者调用日志",
                "verbose_name_plural": "开发者调用日志",
                "db_table": "developer_usage_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="developeraccount",
            index=models.Index(fields=["user"], name="idx_dev_user"),
        ),
        migrations.AddIndex(
            model_name="developeraccount",
            index=models.Index(fields=["status", "tier"], name="idx_dev_status_tier"),
        ),
        migrations.AddIndex(
            model_name="developerusagelog",
            index=models.Index(
                fields=["api_key", "created_at"], name="idx_dul_api_time"
            ),
        ),
        migrations.AddIndex(
            model_name="developerusagelog",
            index=models.Index(
                fields=["developer", "api_type", "created_at"],
                name="idx_dul_dev_api_time",
            ),
        ),
        migrations.AddIndex(
            model_name="developerusagelog",
            index=models.Index(
                fields=["api_type", "status", "created_at"],
                name="idx_dul_api_status_time",
            ),
        ),
    ]
