# Generated by Django 6.0.1 on 2026-05-31 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0030_add_developer_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类代码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("personal_info", "个人信息"),
                            ("business_data", "业务数据"),
                            ("system_data", "系统运行数据"),
                            ("log_audit_data", "日志审计数据"),
                            ("financial_data", "财务数据"),
                            ("security_data", "安全相关数据"),
                            ("third_party_data", "第三方数据"),
                            ("knowledge_base", "知识库数据"),
                        ],
                        max_length=30,
                        verbose_name="分类类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="分类描述"),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="法律依据（如：个人信息保护法第XX条）",
                    ),
                ),
                (
                    "compliance_requirements",
                    models.JSONField(default=list, verbose_name="合规要求清单"),
                ),
                (
                    "cross_border_transfer_allowed",
                    models.BooleanField(default=False, verbose_name="允许跨境传输"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "数据分类",
                "verbose_name_plural": "数据分类",
                "db_table": "data_category",
                "ordering": ["category_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="DataSensitivityLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("L1", "L1-公开"),
                            ("L2", "L2-内部"),
                            ("L3", "L3-机密"),
                            ("L4", "L4-绝密"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="级别代码",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="级别名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="级别说明"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#86909C", max_length=7, verbose_name="标识颜色"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="标识图标"
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=180, verbose_name="最小保留天数(天)"
                    ),
                ),
                (
                    "encryption_required",
                    models.BooleanField(default=False, verbose_name="是否需要加密存储"),
                ),
                (
                    "access_log_required",
                    models.BooleanField(default=True, verbose_name="是否记录访问日志"),
                ),
                (
                    "export_approval_required",
                    models.BooleanField(default=False, verbose_name="导出是否需要审批"),
                ),
                (
                    "allowed_roles",
                    models.JSONField(default=list, verbose_name="允许访问的角色列表"),
                ),
                (
                    "dpo_review_required",
                    models.BooleanField(default=False, verbose_name="是否需要DPO审核"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "数据敏感度等级",
                "verbose_name_plural": "数据敏感度等级",
                "db_table": "data_sensitivity_level",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="DataExportApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_description", models.TextField(verbose_name="导出数据描述")),
                (
                    "object_types",
                    models.JSONField(default=list, verbose_name="涉及的数据类型列表"),
                ),
                (
                    "max_sensitivity_level",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="涉及最高敏感级别",
                    ),
                ),
                (
                    "record_count_estimate",
                    models.PositiveIntegerField(default=0, verbose_name="预估记录数"),
                ),
                ("purpose", models.TextField(verbose_name="导出用途")),
                (
                    "recipient",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="接收方"
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                        ],
                        default="csv",
                        max_length=20,
                        verbose_name="导出格式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                            ("revoked", "已撤销"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, default="", verbose_name="审批意见"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="授权过期时间"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="生成文件路径",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "last_download_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后下载时间"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="申请IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据导出审批",
                "verbose_name_plural": "数据导出审批",
                "db_table": "data_export_approval",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataProtectionOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="工号"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="部门"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "certificate",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="资质证书"
                    ),
                ),
                (
                    "scope",
                    models.JSONField(
                        default=list, verbose_name="负责范围（数据分类列表）"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="在职状态"),
                ),
                ("appointed_at", models.DateField(verbose_name="任命日期")),
                (
                    "term_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="任期结束日期"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dpo_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据保护官(DPO)",
                "verbose_name_plural": "数据保护官(DPO)",
                "db_table": "data_protection_officer",
            },
        ),
        migrations.CreateModel(
            name="DataFieldTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_path",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="字段路径（如：auth_app.User.email）",
                    ),
                ),
                (
                    "field_label",
                    models.CharField(max_length=100, verbose_name="字段中文名"),
                ),
                (
                    "pii_type",
                    models.CharField(
                        choices=[
                            ("identity_card", "身份证号"),
                            ("phone", "手机号码"),
                            ("email", "电子邮箱"),
                            ("real_name", "真实姓名"),
                            ("address", "居住地址"),
                            ("bank_account", "银行账号"),
                            ("ip_address", "IP地址"),
                            ("device_id", "设备标识"),
                            ("biometric", "生物识别信息"),
                            ("location", "位置信息"),
                            ("password_hash", "密码哈希"),
                            ("api_key", "API密钥"),
                            ("session_token", "会话令牌"),
                            ("financial", "财务信息"),
                            ("health", "健康信息"),
                            ("other_sensitive", "其他敏感信息"),
                        ],
                        max_length=30,
                        verbose_name="PII类型",
                    ),
                ),
                (
                    "mask_rule",
                    models.CharField(
                        choices=[
                            ("none", "不脱敏"),
                            ("full", "完全脱敏"),
                            ("partial", "部分脱敏"),
                            ("hash", "哈希替换"),
                        ],
                        default="partial",
                        max_length=100,
                        verbose_name="展示脱敏规则",
                    ),
                ),
                (
                    "mask_pattern",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="脱敏模式（正则）",
                    ),
                ),
                (
                    "is_encrypted_at_rest",
                    models.BooleanField(default=False, verbose_name="静态加密存储"),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="法律依据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "data_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tagged_fields",
                        to="auth_app.datacategory",
                        verbose_name="所属分类",
                    ),
                ),
                (
                    "sensitivity_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tagged_fields",
                        to="auth_app.datasensitivitylevel",
                        verbose_name="敏感级别",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据字段标签（PII标注）",
                "verbose_name_plural": "数据字段标签（PII标注）",
                "db_table": "data_field_tag",
                "ordering": ["pii_type", "field_path"],
            },
        ),
        migrations.AddField(
            model_name="datacategory",
            name="default_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_categories",
                to="auth_app.datasensitivitylevel",
                verbose_name="默认敏感级别",
            ),
        ),
        migrations.CreateModel(
            name="DataClassificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(max_length=100, verbose_name="对象类型（模型名）"),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="对象ID")),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="对象摘要"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("auto_classified", "自动分级"),
                            ("manual_classified", "手动分级"),
                            ("level_changed", "级别变更"),
                            ("access_granted", "访问授权"),
                            ("access_denied", "访问拒绝"),
                            ("exported", "数据导出"),
                            ("deleted", "数据删除"),
                            ("retention_expired", "保留期满销毁"),
                        ],
                        max_length=30,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "operator_role",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="操作时角色"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", verbose_name="操作原因/备注"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="操作IP"
                    ),
                ),
                (
                    "previous_level_code",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="变更前级别"
                    ),
                ),
                (
                    "new_level_code",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="变更后级别"
                    ),
                ),
                (
                    "auto_classification_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="自动分类置信度(0-1)"
                    ),
                ),
                (
                    "classification_rules_matched",
                    models.JSONField(default=list, verbose_name="匹配的分类规则"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="操作时间"
                    ),
                ),
                (
                    "data_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth_app.datacategory",
                        verbose_name="数据分类",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classification_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "sensitivity_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth_app.datasensitivitylevel",
                        verbose_name="敏感级别",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据分级操作记录",
                "verbose_name_plural": "数据分级操作记录",
                "db_table": "data_classification_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"], name="idx_dc_object"
                    ),
                    models.Index(fields=["action_type"], name="idx_dc_action"),
                    models.Index(fields=["sensitivity_level"], name="idx_dc_level"),
                ],
            },
        ),
    ]
