# Generated by Django 6.0.1 on 2026-05-31 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0031_add_data_classification_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseAuditService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="服务名称")),
                (
                    "audit_tier",
                    models.CharField(
                        choices=[
                            ("essential", "基础审计版"),
                            ("professional", "专业审计版"),
                            ("enterprise", "企业旗舰版"),
                            ("flagship", "至尊定制版"),
                        ],
                        max_length=20,
                        verbose_name="审计级别",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ai_content", "AI内容安全审计"),
                            ("agent_security", "Agent系统安全审计"),
                            ("rag_compliance", "RAG合规性审计"),
                            ("data_classification", "数据分类分级审计"),
                            ("api_security", "API接口安全审计"),
                            ("full_stack", "全栈安全审计"),
                        ],
                        max_length=30,
                        verbose_name="审计范围",
                    ),
                ),
                ("description", models.TextField(verbose_name="服务描述")),
                (
                    "deliverables",
                    models.JSONField(default=list, verbose_name="交付物清单"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="基础价格(元/年)"
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000,
                        max_digits=12,
                        verbose_name="最低报价(元/年)",
                    ),
                ),
                (
                    "profit_margin",
                    models.PositiveSmallIntegerField(
                        default=80, verbose_name="利润率(%)"
                    ),
                ),
                (
                    "audit_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="审计周期(工作日)"
                    ),
                ),
                (
                    "on_site_visits",
                    models.PositiveIntegerField(default=1, verbose_name="现场次数"),
                ),
                (
                    "report_count",
                    models.PositiveIntegerField(default=4, verbose_name="报告数量"),
                ),
                (
                    "includes_remediation",
                    models.BooleanField(default=False, verbose_name="是否含整改建议"),
                ),
                (
                    "includes_certification",
                    models.BooleanField(
                        default=False, verbose_name="是否含合规认证辅导"
                    ),
                ),
                (
                    "includes_training",
                    models.BooleanField(default=False, verbose_name="是否含培训服务"),
                ),
                (
                    "target_company_size",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="目标企业规模",
                    ),
                ),
                (
                    "industry_focus",
                    models.JSONField(default=list, verbose_name="聚焦行业"),
                ),
                (
                    "compliance_standards",
                    models.JSONField(
                        default=list, verbose_name="符合标准(等保2.0/ISO27001等)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                (
                    "is_recommended",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "企业安全审计服务",
                "verbose_name_plural": "企业安全审计服务",
                "db_table": "enterprise_audit_service",
                "ordering": ["base_price"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="套餐名称")),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("combo_sab", "S+A+B联动套餐"),
                            ("combo_sa", "S+A双核套餐"),
                            ("combo_sb", "S+B快速套餐"),
                            ("combo_ab", "A+B进阶套餐"),
                        ],
                        max_length=20,
                        verbose_name="套餐类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="套餐描述")),
                (
                    "cover_image",
                    models.URLField(blank=True, default="", verbose_name="封面图"),
                ),
                (
                    "original_total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="原价总和",
                    ),
                ),
                (
                    "package_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="套餐价格"
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="相对于单独购买的总价折扣",
                        verbose_name="折扣比例(%)",
                    ),
                ),
                (
                    "saved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="节省金额",
                    ),
                ),
                (
                    "included_features",
                    models.JSONField(default=list, verbose_name="包含权益列表"),
                ),
                (
                    "tier_badges",
                    models.JSONField(default=list, verbose_name="等级徽章展示"),
                ),
                (
                    "validity_days",
                    models.PositiveIntegerField(default=365, verbose_name="有效期(天)"),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(default=1, verbose_name="最大用户数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                ("sales_count", models.IntegerField(default=0, verbose_name="销量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "a_scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="a_in_packages",
                        to="auth_app.product",
                        verbose_name="A级场景产品",
                    ),
                ),
                (
                    "b_scenarios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="b_in_packages",
                        to="auth_app.product",
                        verbose_name="可选B级场景(选1)",
                    ),
                ),
                (
                    "s_scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="s_in_packages",
                        to="auth_app.product",
                        verbose_name="S级场景产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景联动套餐",
                "verbose_name_plural": "场景联动套餐",
                "db_table": "scenario_package",
                "ordering": ["sort_order", "-sales_count"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseAuditContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="企业名称"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=30, verbose_name="联系电话"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "contract_no",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="合同编号"
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="签约金额(元/年)"
                    ),
                ),
                (
                    "actual_profit_margin",
                    models.PositiveSmallIntegerField(
                        default=80, verbose_name="实际利润率(%)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquiry", "咨询中"),
                            ("quoting", "报价中"),
                            ("negotiating", "洽谈中"),
                            ("signed", "已签约"),
                            ("auditing", "审计中"),
                            ("reporting", "出报告中"),
                            ("completed", "已完成"),
                            ("renewed", "已续约"),
                            ("cancelled", "已取消"),
                        ],
                        default="inquiry",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "audit_scope_detail",
                    models.JSONField(default=dict, verbose_name="审计范围详情"),
                ),
                (
                    "special_requirements",
                    models.TextField(blank=True, default="", verbose_name="特殊要求"),
                ),
                (
                    "signed_at",
                    models.DateField(blank=True, null=True, verbose_name="签约时间"),
                ),
                (
                    "completed_at",
                    models.DateField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "renewal_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="续约次数"
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, default="", verbose_name="内部备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="auth_app.enterpriseauditservice",
                        verbose_name="审计服务",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业审计合同",
                "verbose_name_plural": "企业审计合同",
                "db_table": "enterprise_audit_contract",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="idx_audit_status_time"
                    ),
                    models.Index(fields=["company_name"], name="idx_audit_company"),
                ],
            },
        ),
    ]
