# Generated by Django 6.0.1 on 2026-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0032_enterpriseauditservice_scenariopackage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillconfig",
            name="api_endpoint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="对应的后端API路径",
                max_length=200,
                verbose_name="API端点",
            ),
        ),
        migrations.AddField(
            model_name="skillconfig",
            name="target_product",
            field=models.CharField(
                blank=True,
                default="",
                help_text="对标的产品名称",
                max_length=50,
                verbose_name="对标产品",
            ),
        ),
    ]
