# Generated by Django 6.0.1 on 2026-05-31 17:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0033_skillconfig_api_endpoint_skillconfig_target_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentconfig",
            name="code",
            field=models.CharField(
                choices=[
                    ("auditor", "auditor"),
                    ("verifier", "verifier"),
                    ("archiver", "archiver"),
                    ("judge", "judge"),
                    ("detector", "detector"),
                ],
                max_length=20,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="agentverificationrecord",
            name="agent_code",
            field=models.CharField(
                choices=[
                    ("auditor", "auditor"),
                    ("verifier", "verifier"),
                    ("archiver", "archiver"),
                    ("judge", "judge"),
                    ("detector", "detector"),
                ],
                max_length=20,
                verbose_name="agent_code",
            ),
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="工作流名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("chatflow", "对话型工作流"),
                            ("workflow", "自动化工作流"),
                            ("agent", "智能体编排"),
                            ("custom", "自定义流程"),
                        ],
                        default="chatflow",
                        max_length=30,
                        verbose_name="工作流类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                            ("disabled", "已禁用"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="图标"
                    ),
                ),
                (
                    "icon_background",
                    models.CharField(
                        blank=True,
                        default="#EF4444",
                        max_length=20,
                        verbose_name="图标背景色",
                    ),
                ),
                (
                    "graph_data",
                    models.JSONField(default=dict, verbose_name="可视化图数据"),
                ),
                (
                    "environment_variables",
                    models.JSONField(default=list, verbose_name="环境变量列表"),
                ),
                (
                    "is_template",
                    models.BooleanField(default=False, verbose_name="是否为模板"),
                ),
                (
                    "template_category",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="模板分类"
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_workflow",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "edge_id",
                    models.CharField(max_length=100, verbose_name="边ID（前端标识）"),
                ),
                (
                    "source_node_id",
                    models.CharField(max_length=100, verbose_name="源节点ID"),
                ),
                (
                    "target_node_id",
                    models.CharField(max_length=100, verbose_name="目标节点ID"),
                ),
                (
                    "source_handle",
                    models.CharField(
                        default="source", max_length=50, verbose_name="源连接点"
                    ),
                ),
                (
                    "target_handle",
                    models.CharField(
                        default="target", max_length=50, verbose_name="目标连接点"
                    ),
                ),
                (
                    "condition_data",
                    models.JSONField(default=dict, verbose_name="分支条件表达式"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="连线标签"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="auth_app.workflow",
                        verbose_name="所属工作流",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_edge",
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("succeeded", "成功"),
                            ("failed", "失败"),
                            ("stopped", "已停止"),
                            ("timeout", "超时"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("inputs", models.JSONField(default=dict, verbose_name="输入数据")),
                ("outputs", models.JSONField(default=dict, verbose_name="输出数据")),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="总Token消耗"),
                ),
                (
                    "total_steps",
                    models.PositiveIntegerField(default=0, verbose_name="总步骤数"),
                ),
                (
                    "elapsed_time_ms",
                    models.PositiveIntegerField(default=0, verbose_name="耗时(毫秒)"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行用户",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="auth_app.workflow",
                        verbose_name="工作流",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_id",
                    models.CharField(max_length=100, verbose_name="节点ID（前端标识）"),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("start", "开始节点"),
                            ("end", "结束节点"),
                            ("llm", "LLM 调用"),
                            ("knowledge_retrieval", "知识库检索"),
                            ("condition", "条件分支"),
                            ("iteration", "迭代循环"),
                            ("tool", "工具调用"),
                            ("code", "代码执行"),
                            ("http_request", "HTTP 请求"),
                            ("variable_assigner", "变量赋值"),
                            ("template_transform", "模板转换"),
                            ("question_classifier", "问题分类"),
                            ("document_extractor", "文档提取"),
                            ("tipping", "打赏处理"),
                            ("notification", "通知推送"),
                        ],
                        max_length=30,
                        verbose_name="节点类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="节点标题")),
                ("desc", models.TextField(blank=True, default="", verbose_name="描述")),
                ("position_x", models.FloatField(default=0, verbose_name="X坐标")),
                ("position_y", models.FloatField(default=0, verbose_name="Y坐标")),
                (
                    "config_data",
                    models.JSONField(default=dict, verbose_name="节点配置数据"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="auth_app.workflow",
                        verbose_name="所属工作流",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_node",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                ("description", models.TextField(verbose_name="模板描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("agent", "智能体助手"),
                            ("automation", "自动化流程"),
                            ("content", "内容生成"),
                            ("analysis", "数据分析"),
                            ("customer_service", "客服场景"),
                            ("security", "安全检测"),
                            ("education", "教育培训"),
                            ("other", "其他场景"),
                        ],
                        max_length=30,
                        verbose_name="分类",
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(blank=True, default="", verbose_name="封面图"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="Workflow", max_length=50, verbose_name="图标"
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        default="#165DFF", max_length=20, verbose_name="图标颜色"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "入门"),
                            ("intermediate", "中级"),
                            ("advanced", "高级"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="难度等级",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签列表")),
                (
                    "use_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次数"),
                ),
                ("rating", models.FloatField(default=0.0, verbose_name="评分")),
                (
                    "is_official",
                    models.BooleanField(default=True, verbose_name="是否官方模板"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_meta",
                        to="auth_app.workflow",
                        verbose_name="基础工作流",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_template",
                "ordering": ["-is_featured", "-use_count"],
            },
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["owner", "status"], name="workflow_wo_owner_i_50bb28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["workflow_type", "status"],
                name="workflow_wo_workflo_402b2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["is_template", "template_category"],
                name="workflow_wo_is_temp_26c828_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowedge",
            index=models.Index(
                fields=["workflow", "source_node_id"],
                name="workflow_ed_workflo_080c53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowedge",
            index=models.Index(
                fields=["workflow", "target_node_id"],
                name="workflow_ed_workflo_2a57d8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowedge",
            unique_together={("workflow", "edge_id")},
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "status"], name="workflow_ex_workflo_8c0c9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["user", "-started_at"], name="workflow_ex_user_id_1f6178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflownode",
            index=models.Index(
                fields=["workflow", "node_type"], name="workflow_no_workflo_66b74f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflownode",
            unique_together={("workflow", "node_id")},
        ),
    ]
