# Generated by Django 6.0.1 on 2026-06-26 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0035_fix_user_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperApplication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "company",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="公司/组织"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, default="", verbose_name="网站"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="联系邮箱"
                    ),
                ),
                (
                    "use_case",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="使用场景描述",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="为什么需要API访问权限？",
                        max_length=500,
                        verbose_name="申请理由",
                    ),
                ),
                (
                    "requested_tier",
                    models.CharField(
                        choices=[
                            ("free", "免费版"),
                            ("pro", "专业版"),
                            ("team", "团队版"),
                        ],
                        default="free",
                        max_length=15,
                        verbose_name="申请套餐",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, default="", verbose_name="审核备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_developer_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "developer_application",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="developer_a_user_id_0693ff_idx"
                    ),
                    models.Index(
                        fields=["status"], name="developer_a_status_64f952_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="developer_a_created_97e368_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TipRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="article/user/page等",
                        max_length=50,
                        verbose_name="内容类型",
                    ),
                ),
                (
                    "content_id",
                    models.IntegerField(blank=True, null=True, verbose_name="内容ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        max_digits=10,
                        verbose_name="金额(元)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="货币"),
                ),
                (
                    "tip_option",
                    models.CharField(
                        choices=[
                            ("coffee", "咖啡 ¥3"),
                            ("tea", "奶茶 ¥5"),
                            ("lunch", "午餐 ¥15"),
                            ("dinner", "晚餐 ¥30"),
                            ("movie", "电影 ¥50"),
                            ("custom", "自定义"),
                        ],
                        default="coffee",
                        max_length=20,
                        verbose_name="打赏选项",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="打赏时的公开留言",
                        verbose_name="留言",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="是否公开显示"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("failed", "支付失败"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_tips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="打赏者",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tip_record",
                        to="auth_app.paymentorder",
                        verbose_name="关联订单",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_tips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
            ],
            options={
                "verbose_name": "打赏记录",
                "verbose_name_plural": "打赏记录",
                "db_table": "tip_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_user", "-created_at"], name="idx_tip_receiver"
                    ),
                    models.Index(
                        fields=["from_user", "-created_at"], name="idx_tip_sender"
                    ),
                    models.Index(fields=["status"], name="idx_tip_status"),
                ],
            },
        ),
    ]
