# Generated by Django 4.2 migration
# Agent行为基线建模引擎 - 数据库迁移

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0036_add_developer_application'),
    ]

    operations = [
        # 1. Agent行为日志表
        migrations.CreateModel(
            name='AgentBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(db_index=True, max_length=50, verbose_name='Agent编码')),
                ('agent_name', models.CharField(max_length=100, verbose_name='Agent名称')),
                ('session_id', models.CharField(db_index=True, max_length=64, verbose_name='会话ID')),
                ('behavior_type', models.CharField(
                    choices=[
                        ('api_call', 'API调用'),
                        ('data_access', '数据访问'),
                        ('permission_use', '权限使用'),
                        ('tool_call', 'Tool调用'),
                        ('session_create', '会话创建'),
                        ('session_complete', '会话完成'),
                    ],
                    db_index=True, max_length=20, verbose_name='行为类型'
                )),
                ('behavior_data', models.JSONField(default=dict, verbose_name='行为详情')),
                ('risk_level', models.CharField(
                    choices=[
                        ('low', '低风险'),
                        ('medium', '中风险'),
                        ('high', '高风险'),
                        ('critical', '严重风险'),
                    ],
                    db_index=True, default='low', max_length=20, verbose_name='风险等级'
                )),
                ('risk_score', models.FloatField(default=0.0, verbose_name='风险评分(0-100)')),
                ('anomaly_score', models.FloatField(default=0.0, verbose_name='异常分数(0-1)')),
                ('baseline_deviation', models.FloatField(default=0.0, verbose_name='基线偏离度')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='用户代理')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='行为时间')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='持续时间(毫秒)')),
                ('is_anomaly', models.BooleanField(db_index=True, default=False, verbose_name='是否异常')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('user', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='agent_behaviors',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='用户'
                )),
                ('related_session', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='behaviors',
                    to='auth_app.agentsession',
                    verbose_name='关联会话'
                )),
                ('reviewed_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='reviewed_behaviors',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='审核人'
                )),
            ],
            options={
                'verbose_name': 'Agent行为日志',
                'verbose_name_plural': 'Agent行为日志',
                'db_table': 'agent_behavior_log',
                'ordering': ['-timestamp'],
            },
        ),
        
        # 2. 行为基线表
        migrations.CreateModel(
            name='BehaviorBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(db_index=True, max_length=50, verbose_name='Agent编码')),
                ('baseline_type', models.CharField(
                    choices=[
                        ('api_call', 'API调用基线'),
                        ('data_access', '数据访问基线'),
                        ('permission_use', '权限使用基线'),
                        ('tool_call', 'Tool调用基线'),
                        ('session_pattern', '会话模式基线'),
                    ],
                    db_index=True, max_length=20, verbose_name='基线类型'
                )),
                ('period_start', models.DateTimeField(verbose_name='统计开始时间')),
                ('period_end', models.DateTimeField(verbose_name='统计结束时间')),
                ('sample_count', models.IntegerField(default=0, verbose_name='样本数量')),
                ('baseline_data', models.JSONField(default=dict, verbose_name='基线数据')),
                ('version', models.CharField(default='v1.0', max_length=20, verbose_name='模型版本')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='模型准确率')),
                ('precision', models.FloatField(default=0.0, verbose_name='模型精确率')),
                ('recall', models.FloatField(default=0.0, verbose_name='模型召回率')),
                ('f1_score', models.FloatField(default=0.0, verbose_name='F1分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '行为基线',
                'verbose_name_plural': '行为基线',
                'db_table': 'behavior_baseline',
                'ordering': ['-updated_at'],
            },
        ),
        
        # 3. 异常检测结果表
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(max_length=50, verbose_name='异常类型')),
                ('severity', models.CharField(
                    choices=[
                        ('low', '低危'),
                        ('medium', '中危'),
                        ('high', '高危'),
                        ('critical', '严重'),
                    ],
                    db_index=True, default='medium', max_length=20, verbose_name='严重程度'
                )),
                ('detection_method', models.CharField(max_length=50, verbose_name='检测方法')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度(0-1)')),
                ('anomaly_description', models.TextField(verbose_name='异常描述')),
                ('anomaly_data', models.JSONField(default=dict, verbose_name='异常详情数据')),
                ('status', models.CharField(
                    choices=[
                        ('detected', '已检测'),
                        ('investigating', '调查中'),
                        ('resolved', '已解决'),
                        ('false_positive', '误报'),
                    ],
                    db_index=True, default='detected', max_length=20, verbose_name='处理状态'
                )),
                ('resolution_notes', models.TextField(blank=True, default='', verbose_name='解决说明')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='检测时间')),
                ('behavior_log', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='anomalies',
                    to='auth_app.agentbehaviorlog',
                    verbose_name='关联行为日志'
                )),
                ('assigned_to', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='assigned_anomalies',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='分配给'
                )),
            ],
            options={
                'verbose_name': '异常检测',
                'verbose_name_plural': '异常检测',
                'db_table': 'anomaly_detection',
                'ordering': ['-detected_at'],
            },
        ),
        
        # 4. 行为模式表
        migrations.CreateModel(
            name='BehaviorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(db_index=True, max_length=50, verbose_name='Agent编码')),
                ('pattern_type', models.CharField(
                    choices=[
                        ('sequence', '序列模式'),
                        ('frequency', '频率模式'),
                        ('temporal', '时间模式'),
                        ('contextual', '上下文模式'),
                    ],
                    db_index=True, max_length=20, verbose_name='模式类型'
                )),
                ('pattern_name', models.CharField(max_length=100, verbose_name='模式名称')),
                ('pattern_definition', models.JSONField(default=dict, verbose_name='模式定义')),
                ('occurrence_count', models.IntegerField(default=0, verbose_name='出现次数')),
                ('support', models.FloatField(default=0.0, verbose_name='支持度')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('last_occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='最后出现时间')),
                ('is_normal', models.BooleanField(default=True, verbose_name='是否正常模式')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '行为模式',
                'verbose_name_plural': '行为模式',
                'db_table': 'behavior_pattern',
                'ordering': ['-occurrence_count'],
            },
        ),
        
        # 5. 添加复合索引
        migrations.RunSQL(
            "CREATE INDEX idx_behavior_agent_type ON agent_behavior_log (agent_code, behavior_type);",
            "DROP INDEX idx_behavior_agent_type ON agent_behavior_log;"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_behavior_time_risk ON agent_behavior_log (timestamp, risk_level);",
            "DROP INDEX idx_behavior_time_risk ON agent_behavior_log;"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_behavior_session_time ON agent_behavior_log (session_id, timestamp);",
            "DROP INDEX idx_behavior_session_time ON agent_behavior_log;"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_baseline_agent_type_active ON behavior_baseline (agent_code, baseline_type, is_active);",
            "DROP INDEX idx_baseline_agent_type_active ON behavior_baseline;"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_anomaly_severity_status ON anomaly_detection (severity, status);",
            "DROP INDEX idx_anomaly_severity_status ON anomaly_detection;"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_anomaly_time_type ON anomaly_detection (detected_at, anomaly_type);",
            "DROP INDEX idx_anomaly_time_type ON anomaly_detection;"
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_pattern_agent_type_active ON behavior_pattern (agent_code, pattern_type, is_active);",
            "DROP INDEX idx_pattern_agent_type_active ON behavior_pattern;"
        ),
    ]