# Generated by Django 6.0.1 on 2026-07-28 17:07

import auth_app.behavior_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0037_add_behavior_baseline_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "safety_points",
                    models.IntegerField(default=0, verbose_name="安全积分"),
                ),
                (
                    "trust_score",
                    models.FloatField(default=0.0, verbose_name="信任评分"),
                ),
                (
                    "total_checks",
                    models.IntegerField(default=0, verbose_name="检测总数"),
                ),
                (
                    "text_checks",
                    models.IntegerField(default=0, verbose_name="文本检测数"),
                ),
                (
                    "image_checks",
                    models.IntegerField(default=0, verbose_name="图片检测数"),
                ),
                (
                    "marketing_checks",
                    models.IntegerField(default=0, verbose_name="营销文案检测数"),
                ),
                (
                    "total_risks",
                    models.IntegerField(default=0, verbose_name="风险总数"),
                ),
                ("high_risks", models.IntegerField(default=0, verbose_name="高风险数")),
                (
                    "medium_risks",
                    models.IntegerField(default=0, verbose_name="中风险数"),
                ),
                ("low_risks", models.IntegerField(default=0, verbose_name="低风险数")),
                (
                    "total_evidences",
                    models.IntegerField(default=0, verbose_name="存证总数"),
                ),
                (
                    "evidence_chain_length",
                    models.IntegerField(default=0, verbose_name="证据链长度"),
                ),
                (
                    "behavior_graph",
                    models.JSONField(default=dict, verbose_name="行为图谱"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "账号资产",
                "verbose_name_plural": "账号资产",
                "db_table": "account_asset",
            },
        ),
        migrations.CreateModel(
            name="AdversarialPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("pattern_type", models.CharField(max_length=50)),
                ("pattern_regex", models.CharField(max_length=200)),
                ("attack_intent", models.CharField(max_length=100)),
                ("hidden_info_type", models.CharField(blank=True, max_length=50)),
                ("severity", models.CharField(default="critical", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "adversarial_pattern",
            },
        ),
        migrations.CreateModel(
            name="AgentBehaviorLoop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_code", models.CharField(db_index=True, max_length=50)),
                ("behavior_hash", models.CharField(db_index=True, max_length=64)),
                ("loop_count", models.IntegerField(default=0)),
                ("loop_detected", models.BooleanField(default=False)),
                (
                    "detected_time",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={
                "db_table": "agent_behavior_loop",
            },
        ),
        migrations.CreateModel(
            name="AgentHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_code", models.CharField(db_index=True, max_length=50)),
                ("agent_name", models.CharField(max_length=100)),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                ("current_task", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(default="healthy", max_length=20)),
                (
                    "heartbeat_time",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={
                "db_table": "agent_heartbeat",
            },
        ),
        migrations.CreateModel(
            name="AgentRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("agent_name", models.CharField(max_length=100)),
                ("permissions", models.JSONField(default=list)),
                ("minimal_permissions", models.JSONField(default=list)),
                ("excessive_permissions", models.JSONField(default=list)),
                ("status", models.CharField(default="minimal", max_length=20)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "agent_registry",
            },
        ),
        migrations.CreateModel(
            name="APICallUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("api_endpoint", models.CharField(max_length=100)),
                ("call_count", models.IntegerField(default=1)),
                ("cost", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "api_call_usage",
            },
        ),
        migrations.CreateModel(
            name="AutomatedAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("threat_type", models.CharField(db_index=True, max_length=50)),
                ("severity", models.CharField(default="medium", max_length=20)),
                ("confidence", models.FloatField(default=0.0)),
                ("expert_equivalent", models.IntegerField(default=0)),
                ("analysis_result", models.JSONField(default=dict)),
                ("processing_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "automated_analysis",
            },
        ),
        migrations.CreateModel(
            name="Auto处置闭环",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("threat_id", models.CharField(db_index=True, max_length=64)),
                ("threat_type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=20)),
                ("processing_steps", models.JSONField(default=list)),
                ("mttr_before", models.FloatField(default=0.0)),
                ("mttr_after", models.FloatField(default=0.0)),
                ("compression_rate", models.FloatField(default=0.0)),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={
                "db_table": "auto_disposal_loop",
            },
        ),
        migrations.CreateModel(
            name="BrandExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("experience_type", models.CharField(max_length=50)),
                ("experience_score", models.FloatField(default=0.0)),
                ("feedback_text", models.TextField(blank=True)),
                ("brand_perception", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "brand_experience",
            },
        ),
        migrations.CreateModel(
            name="CompiledRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("rule_name", models.CharField(max_length=100)),
                ("original_pattern", models.CharField(max_length=500)),
                ("compiled_pattern", models.BinaryField()),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("compilation_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compiled_rule",
            },
        ),
        migrations.CreateModel(
            name="CostComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comparison_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("enterprise_type", models.CharField(max_length=50)),
                ("traditional_cost", models.FloatField(default=0.0)),
                ("saas_cost", models.FloatField(default=0.0)),
                ("cost_saving", models.FloatField(default=0.0)),
                ("saving_percentage", models.FloatField(default=0.0)),
                ("comparison_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cost_comparison",
            },
        ),
        migrations.CreateModel(
            name="CreationTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("content_create", "内容创作"),
                            ("content_edit", "内容编辑"),
                            ("content_detect", "内容检测"),
                            ("image_upload", "图片上传"),
                            ("image_detect", "图片检测"),
                            ("evidence_save", "证据存证"),
                            ("report_export", "报告导出"),
                        ],
                        max_length=20,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "event_title",
                    models.CharField(max_length=200, verbose_name="事件标题"),
                ),
                (
                    "event_description",
                    models.TextField(default="", verbose_name="事件描述"),
                ),
                (
                    "session_id",
                    models.CharField(default="", max_length=64, verbose_name="会话ID"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        default="", max_length=64, verbose_name="内容哈希"
                    ),
                ),
                (
                    "evidence_hash",
                    models.CharField(
                        default="", max_length=128, verbose_name="证据哈希"
                    ),
                ),
                (
                    "evidence_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="证据时间戳"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "创作时间线",
                "verbose_name_plural": "创作时间线",
                "db_table": "creation_timeline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpertKnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=50)),
                ("threat_pattern", models.CharField(max_length=200)),
                ("analysis_method", models.JSONField(default=dict)),
                ("mitigation_strategy", models.JSONField(default=dict)),
                ("expert_count", models.IntegerField(default=1)),
                ("confidence_level", models.FloatField(default=0.8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "expert_knowledge_base",
            },
        ),
        migrations.CreateModel(
            name="ExtensionFingerprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hash",
                    models.CharField(max_length=64, unique=True, verbose_name="哈希值"),
                ),
                (
                    "prev_hash",
                    models.CharField(
                        default="0", max_length=64, verbose_name="前序哈希"
                    ),
                ),
                (
                    "operation_id",
                    models.CharField(max_length=100, verbose_name="操作ID"),
                ),
                ("timestamp", models.DateTimeField(verbose_name="生成时间")),
                (
                    "timestamp_display",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="显示时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "插件指纹记录",
                "verbose_name_plural": "插件指纹记录",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_id",
                    models.CharField(max_length=100, verbose_name="操作ID"),
                ),
                (
                    "operation_type",
                    models.CharField(max_length=50, verbose_name="操作类型"),
                ),
                ("timestamp", models.DateTimeField(verbose_name="操作时间")),
                (
                    "timestamp_display",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="显示时间"
                    ),
                ),
                (
                    "timestamp_source",
                    models.CharField(
                        default="ntp.ntsc.ac.cn",
                        max_length=100,
                        verbose_name="时间来源",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(max_length=100, verbose_name="平台名称"),
                ),
                (
                    "platform_type",
                    models.CharField(max_length=50, verbose_name="平台类型"),
                ),
                (
                    "content_preview",
                    models.TextField(blank=True, verbose_name="内容预览"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="内容哈希"
                    ),
                ),
                (
                    "page_url",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="页面URL"
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="页面标题"
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "插件操作记录",
                "verbose_name_plural": "插件操作记录",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="会话ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="会话标题"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "录制中"),
                            ("completed", "已完成"),
                            ("exported", "已导出"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "operations_count",
                    models.IntegerField(default=0, verbose_name="操作数"),
                ),
                (
                    "fingerprints_count",
                    models.IntegerField(default=0, verbose_name="指纹数"),
                ),
                (
                    "platforms_count",
                    models.IntegerField(default=0, verbose_name="平台数"),
                ),
                ("platforms", models.JSONField(default=list, verbose_name="平台列表")),
                (
                    "device_id",
                    models.CharField(blank=True, max_length=100, verbose_name="设备ID"),
                ),
                (
                    "extension_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="插件版本"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "插件录制会话",
                "verbose_name_plural": "插件录制会话",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=100, verbose_name="会话ID")),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("start", "开始录制"),
                            ("operation", "操作同步"),
                            ("end", "停止录制"),
                            ("full", "完整同步"),
                        ],
                        max_length=20,
                        verbose_name="同步类型",
                    ),
                ),
                (
                    "operations_synced",
                    models.IntegerField(default=0, verbose_name="同步操作数"),
                ),
                (
                    "fingerprints_synced",
                    models.IntegerField(default=0, verbose_name="同步指纹数"),
                ),
                (
                    "device_id",
                    models.CharField(blank=True, max_length=100, verbose_name="设备ID"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "插件同步日志",
                "verbose_name_plural": "插件同步日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InlineInterception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interception_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("threat_type", models.CharField(db_index=True, max_length=50)),
                ("threat_pattern", models.CharField(max_length=200)),
                ("interception_time", models.FloatField(default=0.0)),
                ("response_time", models.FloatField(default=0.0)),
                ("action_taken", models.CharField(max_length=50)),
                ("success", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "inline_interception",
            },
        ),
        migrations.CreateModel(
            name="InlineInterceptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("input_content", models.TextField()),
                ("interception_time", models.FloatField(default=0.0)),
                ("compilation_time", models.FloatField(default=0.0)),
                ("execution_time", models.FloatField(default=0.0)),
                ("matched_rules", models.JSONField(default=list)),
                ("action_taken", models.CharField(max_length=50)),
                (
                    "engine_version",
                    models.CharField(default="v2.0-inline", max_length=20),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "inline_interception_record",
            },
        ),
        migrations.CreateModel(
            name="JourneyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("day_number", models.IntegerField(db_index=True)),
                ("stage_name", models.CharField(max_length=100)),
                ("activity_name", models.CharField(max_length=200)),
                ("activity_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("objectives", models.JSONField(default=list)),
                ("success_criteria", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "journey_activity",
            },
        ),
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "license_key",
                    models.CharField(
                        db_index=True, max_length=32, unique=True, verbose_name="授权码"
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("beta", "内测版"),
                            ("pro", "专业版"),
                            ("enterprise", "企业版"),
                            ("lifetime", "永久版"),
                        ],
                        default="beta",
                        max_length=20,
                        verbose_name="授权类型",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="设备指纹"
                    ),
                ),
                (
                    "bound_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="绑定时间"
                    ),
                ),
                (
                    "valid_days",
                    models.IntegerField(default=30, verbose_name="有效天数"),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="激活时间"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有效"),
                            ("expired", "已过期"),
                            ("revoked", "已撤销"),
                            ("unused", "未使用"),
                        ],
                        default="unused",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "watermark_code",
                    models.CharField(max_length=16, unique=True, verbose_name="水印码"),
                ),
                (
                    "last_verify_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后验证时间"
                    ),
                ),
                (
                    "verify_count",
                    models.IntegerField(default=0, verbose_name="验证次数"),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "授权码",
                "verbose_name_plural": "授权码",
                "db_table": "auth_license_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="设备指纹"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User-Agent"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=False, verbose_name="是否成功"),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="错误信息"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="验证时间"),
                ),
            ],
            options={
                "verbose_name": "授权验证日志",
                "verbose_name_plural": "授权验证日志",
                "db_table": "auth_license_verification_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRiskRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=200, verbose_name="素材名称"),
                ),
                (
                    "material_type",
                    models.CharField(
                        default="image", max_length=50, verbose_name="素材类型"
                    ),
                ),
                (
                    "material_hash",
                    models.CharField(
                        default="", max_length=64, verbose_name="素材哈希"
                    ),
                ),
                (
                    "ai_probability",
                    models.FloatField(default=0.0, verbose_name="AI生成概率"),
                ),
                ("confidence", models.FloatField(default=0.0, verbose_name="置信度")),
                (
                    "is_ai_generated",
                    models.BooleanField(default=False, verbose_name="是否AI生成"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("safe", "安全"),
                            ("warning", "低风险"),
                            ("danger", "高风险"),
                        ],
                        default="safe",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("risk_score", models.FloatField(default=0.0, verbose_name="风险评分")),
                (
                    "risk_factors",
                    models.JSONField(default=list, verbose_name="风险因素"),
                ),
                (
                    "copyright_status",
                    models.CharField(
                        default="unknown", max_length=50, verbose_name="版权状态"
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        default="", max_length=50, verbose_name="许可证类型"
                    ),
                ),
                (
                    "evidence_hash",
                    models.CharField(
                        default="", max_length=128, verbose_name="存证哈希"
                    ),
                ),
                (
                    "evidence_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="存证时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "素材风险记录",
                "verbose_name_plural": "素材风险记录",
                "db_table": "material_risk_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OriginalWork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="作品标题")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("article", "文章"),
                            ("image", "图片"),
                            ("code", "代码"),
                            ("ai_dialog", "AI对话"),
                            ("video", "视频"),
                            ("other", "其他"),
                        ],
                        default="ai_dialog",
                        max_length=20,
                        verbose_name="作品类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="作品描述")),
                ("content", models.TextField(blank=True, verbose_name="作品内容")),
                ("file_url", models.URLField(blank=True, verbose_name="文件链接")),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="内容哈希"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, max_length=100, verbose_name="会话ID"),
                ),
                (
                    "evidence_chain",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="证据链数据"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("reviewing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("review_note", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "declaration_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="原创声明编号",
                    ),
                ),
                (
                    "declaration_issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="声明签发时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "原创作品",
                "verbose_name_plural": "原创作品",
                "db_table": "auth_original_work",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OriginalWorkEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(max_length=50, verbose_name="证据类型"),
                ),
                ("evidence_data", models.JSONField(verbose_name="证据数据")),
                ("timestamp", models.DateTimeField(verbose_name="时间戳")),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="哈希指纹"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "原创作品证据",
                "verbose_name_plural": "原创作品证据",
                "db_table": "auth_original_work_evidence",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PermissionControlAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_code", models.CharField(db_index=True, max_length=50)),
                ("operation", models.CharField(max_length=100)),
                ("resource", models.CharField(max_length=200)),
                ("allowed", models.BooleanField(default=False)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "permission_control_audit_log",
            },
        ),
        migrations.CreateModel(
            name="PermissionViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_code", models.CharField(db_index=True, max_length=50)),
                ("violation_type", models.CharField(max_length=50)),
                ("operation", models.CharField(max_length=100)),
                ("resource", models.CharField(max_length=200)),
                ("severity", models.CharField(default="high", max_length=20)),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "permission_violation",
            },
        ),
        migrations.CreateModel(
            name="PetInteractionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("click", "点击"),
                            ("drag", "拖拽"),
                            ("voice", "语音"),
                            ("gesture", "手势"),
                            ("emotion", "情感"),
                            ("command", "命令"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interaction_data",
                    models.JSONField(default=dict, help_text="交互详细数据"),
                ),
                (
                    "pet_state_before",
                    models.CharField(help_text="交互前桌宠状态", max_length=20),
                ),
                (
                    "pet_state_after",
                    models.CharField(help_text="交互后桌宠状态", max_length=20),
                ),
                ("duration_ms", models.IntegerField(help_text="交互持续时间(毫秒)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "synced",
                    models.BooleanField(default=False, help_text="是否已同步到云端"),
                ),
            ],
            options={
                "db_table": "pet_interaction_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("plan_name", models.CharField(max_length=100)),
                ("plan_type", models.CharField(default="saas", max_length=20)),
                ("monthly_price", models.FloatField(default=0.0)),
                ("api_call_price", models.FloatField(default=0.0)),
                ("features", models.JSONField(default=list)),
                ("api_limit", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pricing_plan",
            },
        ),
        migrations.CreateModel(
            name="PromptInjectionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("input_content", models.TextField()),
                ("attack_type", models.CharField(db_index=True, max_length=50)),
                ("attack_pattern", models.CharField(max_length=200)),
                ("detected_method", models.CharField(max_length=50)),
                ("severity", models.CharField(default="high", max_length=20)),
                ("is_malicious", models.BooleanField(default=True)),
                ("is_honeypot_triggered", models.BooleanField(default=False)),
                ("hidden_info_requested", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "prompt_injection_attempt",
            },
        ),
        migrations.CreateModel(
            name="UserJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "journey_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("current_day", models.IntegerField(default=1)),
                ("current_stage", models.CharField(max_length=50)),
                ("journey_timeline", models.JSONField(default=dict)),
                ("completed_activities", models.JSONField(default=list)),
                ("feedback_data", models.JSONField(default=dict)),
                ("brand_experience_score", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "user_journey",
            },
        ),
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("timeline", "创作时间线报告"),
                            ("material_risk", "素材风险报告"),
                            ("account_asset", "账号资产报告"),
                            ("full", "综合报告（三合一）"),
                        ],
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="报告标题")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "生成失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("summary", models.TextField(default="", verbose_name="报告摘要")),
                ("data", models.JSONField(default=dict, verbose_name="报告数据")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="统计开始时间"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="统计结束时间"
                    ),
                ),
                (
                    "total_checks",
                    models.IntegerField(default=0, verbose_name="检测总数"),
                ),
                (
                    "total_risks",
                    models.IntegerField(default=0, verbose_name="风险总数"),
                ),
                (
                    "safety_score",
                    models.FloatField(default=0.0, verbose_name="安全评分"),
                ),
                (
                    "file_path",
                    models.CharField(
                        default="", max_length=500, verbose_name="文件路径"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="文件大小(bytes)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户报告",
                "verbose_name_plural": "用户报告",
                "db_table": "user_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="securitytestcase",
            name="idx_test_case_category",
        ),
        migrations.RemoveIndex(
            model_name="securitytestcase",
            name="idx_test_case_status",
        ),
        migrations.RemoveIndex(
            model_name="securitytestcase",
            name="idx_test_case_severity",
        ),
        migrations.DeleteModel(
            name="SecurityTestCase",
        ),
        migrations.RemoveIndex(
            model_name="securityvulnerability",
            name="idx_vuln_status",
        ),
        migrations.RemoveIndex(
            model_name="securityvulnerability",
            name="idx_vuln_severity",
        ),
        migrations.RemoveIndex(
            model_name="securityvulnerability",
            name="idx_vuln_category",
        ),
        migrations.RemoveIndex(
            model_name="securityvulnerability",
            name="idx_vuln_created",
        ),
        migrations.DeleteModel(
            name="SecurityVulnerability",
        ),
        migrations.AlterModelOptions(
            name="anomalydetection",
            options={
                "ordering": ["-detected_at"],
                "verbose_name": "异常检测结果",
                "verbose_name_plural": "异常检测结果",
            },
        ),
        migrations.RemoveField(
            model_name="agentbehaviorlog",
            name="related_session",
        ),
        migrations.AddField(
            model_name="agentbehaviorlog",
            name="behavior_id",
            field=models.CharField(
                db_index=True,
                default=auth_app.behavior_models.generate_behavior_id,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="agent_code",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="anomaly_id",
            field=models.CharField(
                db_index=True,
                default=auth_app.behavior_models.generate_anomaly_id,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="behavior_id",
            field=models.CharField(
                db_index=True,
                default=auth_app.behavior_models.generate_behavior_id,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="deviation_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="behaviorbaseline",
            name="baseline_id",
            field=models.CharField(
                db_index=True,
                default=auth_app.behavior_models.generate_baseline_id,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="behaviorbaseline",
            name="behavior_type",
            field=models.CharField(default="unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="behaviorbaseline",
            name="deviation_threshold",
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name="behaviorpattern",
            name="frequency",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="behaviorpattern",
            name="pattern_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="behaviorpattern",
            name="pattern_id",
            field=models.CharField(
                db_index=True,
                default=auth_app.behavior_models.generate_pattern_id,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="agent_code",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="agent_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Agent名称"
            ),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="anomaly_score",
            field=models.FloatField(default=0.0, verbose_name="异常评分"),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="behavior_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="behavior_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="duration_ms",
            field=models.IntegerField(default=0, verbose_name="执行时长(毫秒)"),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="ip_address",
            field=models.GenericIPAddressField(default="", verbose_name="IP地址"),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="is_anomaly",
            field=models.BooleanField(default=False, verbose_name="是否异常"),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="reviewed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_behaviors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="risk_level",
            field=models.CharField(
                default="info", max_length=20, verbose_name="风险等级"
            ),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="risk_score",
            field=models.FloatField(default=0.0, verbose_name="风险评分"),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="session_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="agentbehaviorlog",
            name="user_agent",
            field=models.TextField(default="", verbose_name="User-Agent"),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="anomaly_data",
            field=models.JSONField(default=dict, verbose_name="异常数据"),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="anomaly_description",
            field=models.TextField(default="", verbose_name="异常描述"),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="anomaly_type",
            field=models.CharField(default="unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="分配人",
            ),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="behavior_log",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalies",
                to="auth_app.agentbehaviorlog",
                verbose_name="行为日志",
            ),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="confidence",
            field=models.FloatField(default=0.0, verbose_name="置信度"),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="detected_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="detection_method",
            field=models.CharField(
                default="baseline", max_length=50, verbose_name="检测方法"
            ),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="resolution_notes",
            field=models.TextField(default="", verbose_name="解决说明"),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="severity",
            field=models.CharField(default="medium", max_length=20),
        ),
        migrations.AlterField(
            model_name="anomalydetection",
            name="status",
            field=models.CharField(
                default="detected", max_length=20, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="accuracy",
            field=models.FloatField(default=0.0, verbose_name="准确率"),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="agent_code",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="baseline_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="baseline_type",
            field=models.CharField(
                default="statistical", max_length=50, verbose_name="基线类型"
            ),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="period_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="统计结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="period_start",
            field=models.DateTimeField(auto_now_add=True, verbose_name="统计开始时间"),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="precision",
            field=models.FloatField(default=0.0, verbose_name="精确率"),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="recall",
            field=models.FloatField(default=0.0, verbose_name="召回率"),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="behaviorbaseline",
            name="version",
            field=models.CharField(default="v1.0", max_length=20, verbose_name="版本"),
        ),
        migrations.AlterField(
            model_name="behaviorpattern",
            name="agent_code",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="behaviorpattern",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="behaviorpattern",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="behaviorpattern",
            name="is_normal",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="behaviorpattern",
            name="pattern_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="behaviorpattern",
            name="pattern_type",
            field=models.CharField(default="unknown", max_length=50),
        ),
        migrations.AddIndex(
            model_name="agentbehaviorlog",
            index=models.Index(
                fields=["agent_code", "-timestamp"], name="idx_behavior_agent_time"
            ),
        ),
        migrations.AddIndex(
            model_name="agentbehaviorlog",
            index=models.Index(fields=["risk_level"], name="idx_behavior_risk"),
        ),
        migrations.AddIndex(
            model_name="agentbehaviorlog",
            index=models.Index(fields=["is_anomaly"], name="idx_behavior_anomaly"),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(
                fields=["agent_code", "-detected_at"], name="idx_anomaly_agent_time"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(fields=["severity"], name="idx_anomaly_severity"),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(fields=["status"], name="idx_anomaly_status"),
        ),
        migrations.AddIndex(
            model_name="behaviorbaseline",
            index=models.Index(
                fields=["agent_code", "baseline_type"], name="idx_baseline_agent_type"
            ),
        ),
        migrations.AddIndex(
            model_name="behaviorbaseline",
            index=models.Index(fields=["is_active"], name="idx_baseline_active"),
        ),
        migrations.AddIndex(
            model_name="behaviorpattern",
            index=models.Index(
                fields=["agent_code", "pattern_type"], name="idx_pattern_agent_type"
            ),
        ),
        migrations.AddIndex(
            model_name="behaviorpattern",
            index=models.Index(fields=["is_normal"], name="idx_pattern_normal"),
        ),
        migrations.AddField(
            model_name="accountasset",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_asset",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentregistry",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creationtimeline",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="extensionsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extension_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="extensionoperation",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="auth_app.extensionsession",
                verbose_name="会话",
            ),
        ),
        migrations.AddField(
            model_name="extensionfingerprint",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fingerprints",
                to="auth_app.extensionsession",
                verbose_name="会话",
            ),
        ),
        migrations.AddField(
            model_name="extensionsynclog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extension_sync_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="licensekey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_licenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="licensekey",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="license_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="licenseverificationlog",
            name="license_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_logs",
                to="auth_app.licensekey",
            ),
        ),
        migrations.AddField(
            model_name="materialriskrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_risks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="originalwork",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_works",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="originalwork",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original_works",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="originalworkevidence",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidences",
                to="auth_app.originalwork",
            ),
        ),
        migrations.AddField(
            model_name="petinteractionlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pet_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialriskrecord",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_risks",
                to="auth_app.userreport",
            ),
        ),
        migrations.AddField(
            model_name="creationtimeline",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="auth_app.userreport",
            ),
        ),
        migrations.AddIndex(
            model_name="extensionoperation",
            index=models.Index(
                fields=["session", "timestamp"], name="auth_app_ex_session_18896a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionoperation",
            index=models.Index(
                fields=["operation_type"], name="auth_app_ex_operati_3a7eac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionfingerprint",
            index=models.Index(
                fields=["session", "timestamp"], name="auth_app_ex_session_a157b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extensionfingerprint",
            index=models.Index(fields=["hash"], name="auth_app_ex_hash_1e1484_idx"),
        ),
        migrations.AddIndex(
            model_name="petinteractionlog",
            index=models.Index(
                fields=["user", "-created_at"], name="pet_interac_user_id_31393d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="petinteractionlog",
            index=models.Index(
                fields=["interaction_type"], name="pet_interac_interac_b36c78_idx"
            ),
        ),
    ]
