# Generated by Django 6.0.1 on 2026-07-28 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0038_fix_all_behavior_models_final"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="密钥名称")),
                (
                    "key_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="密钥哈希"
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="密钥前缀"
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(default=list, verbose_name="权限列表"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后使用时间"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "rate_limit",
                    models.IntegerField(
                        default=100, verbose_name="频率限制（次/分钟）"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "API密钥",
                "verbose_name_plural": "API密钥",
                "db_table": "auth_api_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKeyUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=200, verbose_name="端点")),
                ("method", models.CharField(max_length=10, verbose_name="方法")),
                ("status_code", models.IntegerField(verbose_name="状态码")),
                (
                    "response_time_ms",
                    models.IntegerField(verbose_name="响应时间（毫秒）"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="用户代理"
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="auth_app.apikey",
                        verbose_name="API密钥",
                    ),
                ),
            ],
            options={
                "verbose_name": "API密钥使用日志",
                "verbose_name_plural": "API密钥使用日志",
                "db_table": "auth_api_key_usage_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
