# Generated by Django 4.2.11 on 2025-01-29 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0039_apikey_apikeyusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.CharField(blank=True, max_length=32, verbose_name='TOTP密钥')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='备用码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '双因子认证',
                'verbose_name_plural': '双因子认证',
                'db_table': 'auth_two_factor',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('totp', 'TOTP验证'), ('backup', '备用码验证')], max_length=20, verbose_name='尝试类型')),
                ('is_success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_attempts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '双因子认证尝试',
                'verbose_name_plural': '双因子认证尝试',
                'db_table': 'auth_two_factor_attempt',
                'ordering': ['-created_at'],
            },
        ),
    ]