# Generated by Django 6.0.1 on 2026-07-28 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0040_two_factor_auth_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twofactorattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="two_factor_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="twofactorauth",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="two_factor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
