# Generated by Django 6.0.1 on 2026-08-08 14:06

import auth_app.agent_activity_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0041_alter_twofactorattempt_user_alter_twofactorauth_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentActivityAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_bucket",
                    models.DateTimeField(
                        db_index=True,
                        help_text="1分钟/5分钟/1小时聚合",
                        verbose_name="时间桶",
                    ),
                ),
                (
                    "bucket_type",
                    models.CharField(
                        help_text="1min/5min/1hour",
                        max_length=20,
                        verbose_name="桶类型",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(max_length=20, verbose_name="Agent类型"),
                ),
                ("client_id", models.CharField(max_length=64, verbose_name="客户端ID")),
                (
                    "total_activities",
                    models.IntegerField(default=0, verbose_name="总活动数"),
                ),
                (
                    "avg_risk_score",
                    models.FloatField(default=0.0, verbose_name="平均风险分数"),
                ),
                (
                    "max_risk_score",
                    models.IntegerField(default=0, verbose_name="最高风险分数"),
                ),
                (
                    "high_risk_count",
                    models.IntegerField(
                        default=0,
                        help_text="risk_score > 60的行为数量",
                        verbose_name="高风险行为数",
                    ),
                ),
                (
                    "critical_count",
                    models.IntegerField(
                        default=0,
                        help_text="risk_score > 80的行为数量",
                        verbose_name="严重风险行为数",
                    ),
                ),
                (
                    "action_distribution",
                    models.JSONField(default=dict, verbose_name="操作类型分布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "Agent活动聚合统计",
                "verbose_name_plural": "Agent活动聚合统计",
                "db_table": "agent_activity_aggregation",
                "indexes": [
                    models.Index(fields=["-time_bucket"], name="idx_agg_time"),
                    models.Index(
                        fields=["client_id", "-time_bucket"], name="idx_agg_client_time"
                    ),
                ],
                "unique_together": {
                    ("time_bucket", "bucket_type", "agent_type", "client_id")
                },
            },
        ),
        migrations.CreateModel(
            name="AgentActivityLog",
            fields=[
                (
                    "activity_id",
                    models.CharField(
                        default=auth_app.agent_activity_models.generate_activity_id,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="活动ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        db_index=True,
                        help_text="cursor/claude/copilot/unknown",
                        max_length=20,
                        verbose_name="Agent类型",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="file_operation/clipboard_operation/process_started/agent_detected/ai_api_call",
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "target",
                    models.TextField(
                        help_text="文件路径/剪贴板/进程名/网络域名",
                        verbose_name="操作目标",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        db_index=True,
                        help_text="low/medium/high/critical",
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        db_index=True,
                        help_text="0-100，单次行为风险分数",
                        verbose_name="风险分数",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="0.5-1.0，检测结果的可信程度",
                        verbose_name="置信度",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        help_text="file/clipboard/process/network",
                        max_length=20,
                        verbose_name="监控来源",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="精确到毫秒的时间戳",
                        verbose_name="发生时间",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="用于关联同一Agent会话的多个行为",
                        max_length=50,
                        verbose_name="会话ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="包含检测详情、内容片段等",
                        verbose_name="元数据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="记录创建时间"
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        db_index=True,
                        help_text="桌面端唯一标识，用于数据隔离",
                        max_length=64,
                        verbose_name="客户端ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent活动日志",
                "verbose_name_plural": "Agent活动日志",
                "db_table": "agent_activity_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="idx_activity_time"),
                    models.Index(
                        fields=["agent_type", "-timestamp"],
                        name="idx_activity_agent_time",
                    ),
                    models.Index(
                        fields=["risk_level", "-timestamp"],
                        name="idx_activity_risk_time",
                    ),
                    models.Index(
                        fields=["session_id", "-timestamp"], name="idx_activity_session"
                    ),
                    models.Index(
                        fields=["client_id", "-timestamp"],
                        name="idx_activity_client_time",
                    ),
                    models.Index(
                        fields=["-risk_score", "-timestamp"],
                        name="idx_activity_score_time",
                    ),
                ],
            },
        ),
    ]
