# Generated by Django 6.0.1 on 2026-08-09 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0043_add_trajectory_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        help_text="Agent唯一标识符，格式: agent_<timestamp>_<random>",
                        max_length=50,
                        unique=True,
                        verbose_name="Agent ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        help_text="用户友好的Agent名称",
                        max_length=100,
                        verbose_name="Agent名称",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("cursor", "Cursor IDE"),
                            ("claude", "Claude AI"),
                            ("copilot", "GitHub Copilot"),
                            ("custom", "Custom Agent"),
                        ],
                        help_text="Agent所属类型",
                        max_length=20,
                        verbose_name="Agent类型",
                    ),
                ),
                (
                    "api_key_hash",
                    models.CharField(
                        help_text="API Key的SHA-256哈希值",
                        max_length=128,
                        unique=True,
                        verbose_name="API Key哈希",
                    ),
                ),
                (
                    "api_key_prefix",
                    models.CharField(
                        help_text="API Key的前缀（用于识别）",
                        max_length=8,
                        verbose_name="API Key前缀",
                    ),
                ),
                (
                    "api_key_created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="API Key创建时间"
                    ),
                ),
                (
                    "api_key_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL表示永不过期",
                        null=True,
                        verbose_name="API Key过期时间",
                    ),
                ),
                (
                    "trust_level",
                    models.CharField(
                        choices=[
                            ("low", "低信任级"),
                            ("medium", "中信任级"),
                            ("high", "高信任级"),
                            ("critical", "关键级"),
                        ],
                        default="low",
                        help_text="Agent的信任级别，决定可执行的操作范围",
                        max_length=10,
                        verbose_name="信任级别",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        help_text="资源粒度权限控制，格式: {resource_type: [actions]}",
                        verbose_name="权限策略",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后活跃时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="禁用后将无法通过认证",
                        verbose_name="是否激活",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent身份",
                "verbose_name_plural": "Agent身份管理",
                "db_table": "agent_identities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentAuthSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=64, unique=True, verbose_name="会话ID"),
                ),
                (
                    "jwt_token",
                    models.TextField(
                        help_text="JWT Token内容", verbose_name="JWT Token"
                    ),
                ),
                (
                    "token_created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Token创建时间"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(verbose_name="Token过期时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后活动时间"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="User Agent"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="auth_app.agentidentity",
                        verbose_name="Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent认证会话",
                "verbose_name_plural": "Agent认证会话管理",
                "db_table": "agent_auth_sessions",
                "ordering": ["-token_created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentAuthenticationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        help_text="True表示认证成功，False表示失败",
                        verbose_name="认证结果",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        help_text="认证失败时的原因",
                        max_length=100,
                        null=True,
                        verbose_name="失败原因",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="User Agent"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="认证时间"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_logs",
                        to="auth_app.agentidentity",
                        verbose_name="Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent认证日志",
                "verbose_name_plural": "Agent认证日志管理",
                "db_table": "agent_authentication_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AgentPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("file", "文件系统"),
                            ("network", "网络访问"),
                            ("database", "数据库"),
                            ("system", "系统命令"),
                            ("api", "API调用"),
                        ],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "resource_pattern",
                    models.CharField(
                        help_text="资源匹配模式，支持通配符（如: /home/user/documents/*）",
                        max_length=200,
                        verbose_name="资源模式",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "读取"),
                            ("write", "写入"),
                            ("execute", "执行"),
                            ("delete", "删除"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="额外约束条件（时间范围、频率限制等）",
                        verbose_name="条件约束",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="授权时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="权限过期时间，NULL表示永不过期",
                        null=True,
                        verbose_name="过期时间",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to="auth_app.agentidentity",
                        verbose_name="所属Agent",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授权人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent权限",
                "verbose_name_plural": "Agent权限管理",
                "db_table": "agent_permissions",
                "ordering": ["-granted_at"],
                "unique_together": {
                    ("agent", "resource_type", "resource_pattern", "action")
                },
            },
        ),
    ]
