# Generated by Django 6.0.1 on 2026-08-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0044_add_agent_identity_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentactivitylog",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="执行该行为的Agent身份实例",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="auth_app.agentidentity",
                verbose_name="关联Agent",
            ),
        ),
        migrations.AlterField(
            model_name="agentactivitylog",
            name="agent_type",
            field=models.CharField(
                db_index=True,
                help_text="cursor/claude/copilot/unknown（保留用于类型级查询）",
                max_length=20,
                verbose_name="Agent类型",
            ),
        ),
    ]
