# Generated by Django 6.0.1 on 2026-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0045_add_agent_fk_to_activity_log"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agentidentity",
            index=models.Index(fields=["agent_type"], name="idx_agent_type"),
        ),
        migrations.AddIndex(
            model_name="agentidentity",
            index=models.Index(fields=["trust_level"], name="idx_trust_level"),
        ),
        migrations.AddIndex(
            model_name="agentidentity",
            index=models.Index(fields=["owner"], name="idx_agent_owner"),
        ),
        migrations.AddIndex(
            model_name="agentidentity",
            index=models.Index(fields=["is_active"], name="idx_agent_active"),
        ),
        migrations.AddIndex(
            model_name="agentidentity",
            index=models.Index(
                fields=["agent_type", "trust_level", "is_active"],
                name="idx_agent_type_trust_active",
            ),
        ),
        migrations.AddIndex(
            model_name="agentidentity",
            index=models.Index(
                fields=["owner", "is_active"], name="idx_agent_owner_active"
            ),
        ),
    ]
