# Generated by Django 6.0.1 on 2026-08-10 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0046_add_agent_identity_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortTermMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        db_index=True,
                        help_text="Agent唯一标识符",
                        max_length=100,
                        verbose_name="Agent ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        help_text="如：file_read, api_call, network_access",
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "operation_content",
                    models.TextField(
                        help_text="操作的具体内容", verbose_name="操作内容"
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0,
                        help_text="0.0-1.0，越高越危险",
                        verbose_name="风险分数",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_tags",
                    models.JSONField(
                        default=list,
                        help_text='如：["suspicious", "unusual_time"]',
                        verbose_name="风险标签",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "放行"),
                            ("block", "阻断"),
                            ("ask_user", "询问用户"),
                        ],
                        default="allow",
                        max_length=20,
                        verbose_name="决策结果",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="30分钟后自动过期", verbose_name="过期时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "短期记忆",
                "verbose_name_plural": "短期记忆管理",
                "db_table": "short_term_memories",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="idx_stm_timestamp"),
                    models.Index(
                        fields=["agent_id", "-timestamp"], name="idx_stm_agent_time"
                    ),
                    models.Index(fields=["risk_level"], name="idx_stm_risk"),
                    models.Index(fields=["expires_at"], name="idx_stm_expires"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LongTermMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Agent ID"
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(max_length=50, verbose_name="操作类型"),
                ),
                ("operation_content", models.TextField(verbose_name="操作内容")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("risk_score", models.FloatField(default=0.0, verbose_name="风险分数")),
                ("risk_tags", models.JSONField(default=list, verbose_name="风险标签")),
                (
                    "record_hash",
                    models.CharField(
                        help_text="SHA-256哈希值",
                        max_length=64,
                        unique=True,
                        verbose_name="记录哈希",
                    ),
                ),
                (
                    "prev_hash",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        help_text="形成区块链式结构",
                        max_length=64,
                        verbose_name="前一条记录哈希",
                    ),
                ),
                (
                    "chain_index",
                    models.IntegerField(
                        default=0, help_text="记录在链中的位置", verbose_name="链索引"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "放行"),
                            ("block", "阻断"),
                            ("ask_user", "询问用户"),
                        ],
                        default="allow",
                        max_length=20,
                        verbose_name="决策结果",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="long_term_memories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "长期记忆",
                "verbose_name_plural": "长期记忆管理",
                "db_table": "long_term_memories",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="idx_ltm_timestamp"),
                    models.Index(
                        fields=["agent_id", "-timestamp"], name="idx_ltm_agent_time"
                    ),
                    models.Index(fields=["risk_level"], name="idx_ltm_risk"),
                    models.Index(
                        fields=["user", "-timestamp"], name="idx_ltm_user_time"
                    ),
                    models.Index(fields=["decision"], name="idx_ltm_decision"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StrategicMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_id",
                    models.CharField(
                        help_text="如：rule_file_access_001",
                        max_length=100,
                        unique=True,
                        verbose_name="策略ID",
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("detection_rule", "检测规则"),
                            ("threshold", "阈值配置"),
                            ("whitelist", "白名单"),
                            ("blacklist", "黑名单"),
                            ("behavior_pattern", "行为模式"),
                        ],
                        max_length=50,
                        verbose_name="策略类型",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="规则名称"),
                ),
                (
                    "rule_condition",
                    models.JSONField(
                        help_text="JSON Schema格式的条件", verbose_name="规则条件"
                    ),
                ),
                (
                    "rule_action",
                    models.CharField(
                        choices=[
                            ("allow", "放行"),
                            ("block", "阻断"),
                            ("ask", "询问用户"),
                            ("log", "仅记录"),
                        ],
                        default="allow",
                        max_length=20,
                        verbose_name="规则动作",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.5,
                        help_text="0.0-1.0，策略的可信度",
                        verbose_name="置信度",
                    ),
                ),
                (
                    "sample_count",
                    models.IntegerField(
                        default=0,
                        help_text="该策略基于的样本数",
                        verbose_name="样本数量",
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0, help_text="策略判断的成功率", verbose_name="成功率"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否生效"),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生效开始时间"
                    ),
                ),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生效结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_strategies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "parent_strategy",
                    models.ForeignKey(
                        blank=True,
                        help_text="策略迭代的关系",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_strategies",
                        to="auth_app.strategicmemory",
                        verbose_name="父策略",
                    ),
                ),
            ],
            options={
                "verbose_name": "策略记忆",
                "verbose_name_plural": "策略记忆管理",
                "db_table": "strategic_memories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["strategy_type", "is_active"], name="idx_sm_type_active"
                    ),
                    models.Index(fields=["strategy_id"], name="idx_sm_strategy_id"),
                    models.Index(fields=["-created_at"], name="idx_sm_created"),
                    models.Index(fields=["-confidence"], name="idx_sm_confidence"),
                ],
            },
        ),
    ]
