# Generated by Django 6.0.1 on 2026-08-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0047_shorttermmemory_longtermmemory_strategicmemory"),
    ]

    operations = [
        # SQLite不支持SEQUENCE，改用计数器表
        # 创建计数器表（兼容SQLite）
        migrations.CreateModel(
            name='ChainIndexCounter',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chain_index_counter',
            },
        ),
        # 初始化计数器表（插入一条记录）
        migrations.RunSQL(
            sql="INSERT INTO chain_index_counter (id, counter) VALUES (1, 0);",
            reverse_sql="DELETE FROM chain_index_counter WHERE id = 1;"
        ),
    ]