# Generated by Django 6.0.1 on 2026-08-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0048_add_chain_index_sequence"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="longtermmemory",
            name="idx_ltm_risk",
        ),
        migrations.RemoveIndex(
            model_name="longtermmemory",
            name="idx_ltm_decision",
        ),
        migrations.RemoveIndex(
            model_name="shorttermmemory",
            name="idx_stm_risk",
        ),
        migrations.AddIndex(
            model_name="longtermmemory",
            index=models.Index(fields=["chain_index"], name="idx_ltm_chain"),
        ),
    ]
