# Generated by Django 6.0.1 on 2026-08-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0049_remove_longtermmemory_idx_ltm_risk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chainindexcounter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
