# Generated by Django 6.0.1 on 2026-08-11 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0050_add_governance_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "health_score",
                    models.FloatField(
                        default=100.0,
                        help_text="总分100分，反映整体治理水平",
                        verbose_name="治理健康度评分",
                    ),
                ),
                (
                    "total_agents_count",
                    models.IntegerField(default=0, verbose_name="Agent总数"),
                ),
                (
                    "active_agents_count",
                    models.IntegerField(
                        default=0,
                        help_text="24小时内有活动的Agent",
                        verbose_name="活跃Agent数",
                    ),
                ),
                (
                    "compliant_agents_count",
                    models.IntegerField(
                        default=0,
                        help_text="评分>=60分的Agent",
                        verbose_name="合规Agent数",
                    ),
                ),
                (
                    "high_risk_agents_count",
                    models.IntegerField(
                        default=0,
                        help_text="评分<40分的Agent",
                        verbose_name="高风险Agent数",
                    ),
                ),
                (
                    "operations_24h",
                    models.IntegerField(default=0, verbose_name="24小时操作总数"),
                ),
                (
                    "operations_7d",
                    models.IntegerField(default=0, verbose_name="7天操作总数"),
                ),
                (
                    "operations_30d",
                    models.IntegerField(default=0, verbose_name="30天操作总数"),
                ),
                (
                    "violations_24h",
                    models.IntegerField(default=0, verbose_name="24小时违规次数"),
                ),
                (
                    "violations_7d",
                    models.IntegerField(default=0, verbose_name="7天违规次数"),
                ),
                (
                    "violations_30d",
                    models.IntegerField(default=0, verbose_name="30天违规次数"),
                ),
                (
                    "blocked_operations_24h",
                    models.IntegerField(default=0, verbose_name="24小时阻断操作数"),
                ),
                (
                    "blocked_operations_7d",
                    models.IntegerField(default=0, verbose_name="7天阻断操作数"),
                ),
                (
                    "blocked_operations_30d",
                    models.IntegerField(default=0, verbose_name="30天阻断操作数"),
                ),
                (
                    "compliance_rate",
                    models.FloatField(
                        default=100.0,
                        help_text="合规操作占比（%）",
                        verbose_name="合规率",
                    ),
                ),
                (
                    "blocking_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="阻断操作占比（%）",
                        verbose_name="阻断率",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "snapshot_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="数据统计的截止时间",
                        null=True,
                        verbose_name="快照时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "治理健康度监控",
                "verbose_name_plural": "治理健康度监控管理",
                "db_table": "governance_health",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["health_score"], name="idx_health_score"),
                    models.Index(fields=["-updated_at"], name="idx_health_updated"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentComplianceScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        default=100.0,
                        help_text="总分100分，低于60分为不合格",
                        verbose_name="综合合规评分",
                    ),
                ),
                (
                    "authentication_score",
                    models.FloatField(
                        default=100.0,
                        help_text="评估API Key使用、会话管理等方面的合规性",
                        verbose_name="认证合规评分",
                    ),
                ),
                (
                    "permission_score",
                    models.FloatField(
                        default=100.0,
                        help_text="评估权限使用是否超出授权范围",
                        verbose_name="权限合规评分",
                    ),
                ),
                (
                    "behavior_score",
                    models.FloatField(
                        default=100.0,
                        help_text="评估操作行为是否符合安全规范",
                        verbose_name="行为合规评分",
                    ),
                ),
                (
                    "audit_score",
                    models.FloatField(
                        default=100.0,
                        help_text="评估审计记录是否完整、可追溯",
                        verbose_name="审计合规评分",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("safe", "安全"),
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重风险"),
                        ],
                        default="safe",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "violations_count",
                    models.IntegerField(
                        default=0, help_text="累计违规操作次数", verbose_name="违规次数"
                    ),
                ),
                (
                    "violations_30d",
                    models.IntegerField(default=0, verbose_name="近30天违规次数"),
                ),
                (
                    "blocked_operations_count",
                    models.IntegerField(
                        default=0,
                        help_text="累计被阻断的操作次数",
                        verbose_name="阻断操作次数",
                    ),
                ),
                (
                    "last_operation_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后操作时间"
                    ),
                ),
                (
                    "operations_24h",
                    models.IntegerField(default=0, verbose_name="24小时内操作次数"),
                ),
                (
                    "operations_7d",
                    models.IntegerField(default=0, verbose_name="7天内操作次数"),
                ),
                (
                    "operations_30d",
                    models.IntegerField(default=0, verbose_name="30天内操作次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "score_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="评分更新时间"
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_score",
                        to="auth_app.agentidentity",
                        verbose_name="关联Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent合规性评分",
                "verbose_name_plural": "Agent合规性评分管理",
                "db_table": "agent_compliance_scores",
                "ordering": ["-overall_score", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["overall_score"], name="idx_compliance_overall"
                    ),
                    models.Index(fields=["risk_level"], name="idx_compliance_risk"),
                    models.Index(fields=["-updated_at"], name="idx_compliance_updated"),
                    models.Index(
                        fields=["risk_level", "-updated_at"],
                        name="idx_compliance_risk_time",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StrategyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="格式: v1.0.0", max_length=20, verbose_name="版本号"
                    ),
                ),
                (
                    "version_code",
                    models.IntegerField(
                        default=1,
                        help_text="用于版本比较的数字编码",
                        verbose_name="版本编码",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="完整的策略配置数据",
                        verbose_name="策略配置",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text="相对于上一版本的变更内容",
                        verbose_name="变更记录",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("testing", "测试中"),
                            ("staging", "预发布"),
                            ("production", "生产环境"),
                            ("deprecated", "已废弃"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="发布状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="当前生产环境使用的版本",
                        verbose_name="是否激活",
                    ),
                ),
                (
                    "rollout_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="0-100，表示推送到生产环境的比例",
                        verbose_name="灰度比例",
                    ),
                ),
                (
                    "rollout_agents",
                    models.JSONField(
                        default=list,
                        help_text="参与灰度测试的Agent ID列表",
                        verbose_name="灰度Agent列表",
                    ),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="部署时间"
                    ),
                ),
                (
                    "performance_metrics",
                    models.JSONField(
                        default=dict,
                        help_text="包含命中率、误报率、响应时间等",
                        verbose_name="性能指标",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "changelog",
                    models.TextField(
                        default="",
                        help_text="版本变更的详细说明",
                        verbose_name="变更日志",
                    ),
                ),
                (
                    "deployed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployed_strategies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="部署人",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="auth_app.strategicmemory",
                        verbose_name="关联策略",
                    ),
                ),
            ],
            options={
                "verbose_name": "策略版本",
                "verbose_name_plural": "策略版本管理",
                "db_table": "strategy_versions",
                "ordering": ["-version_code"],
                "indexes": [
                    models.Index(
                        fields=["strategy", "-version_code"],
                        name="idx_strategy_version",
                    ),
                    models.Index(fields=["status"], name="idx_strategy_status"),
                    models.Index(fields=["is_active"], name="idx_strategy_active"),
                    models.Index(fields=["-deployed_at"], name="idx_strategy_deployed"),
                ],
                "unique_together": {("strategy", "version")},
            },
        ),
    ]
