# Generated by Django 6.0.1 on 2026-08-11 12:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0051_add_governance_models_correct"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfAuditReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("hourly", "小时报告"),
                            ("daily", "日报"),
                            ("weekly", "周报"),
                            ("monthly", "月报"),
                        ],
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="报告周期开始")),
                ("period_end", models.DateTimeField(verbose_name="报告周期结束")),
                (
                    "total_checks",
                    models.IntegerField(default=0, verbose_name="总检查次数"),
                ),
                (
                    "issues_found",
                    models.IntegerField(default=0, verbose_name="发现问题数"),
                ),
                (
                    "issues_resolved",
                    models.IntegerField(default=0, verbose_name="已解决问题数"),
                ),
                (
                    "performance_drifts",
                    models.IntegerField(default=0, verbose_name="性能漂移次数"),
                ),
                (
                    "critical_drifts",
                    models.IntegerField(default=0, verbose_name="严重漂移次数"),
                ),
                (
                    "permission_changes",
                    models.IntegerField(default=0, verbose_name="权限变更次数"),
                ),
                (
                    "permission_anomalies",
                    models.IntegerField(default=0, verbose_name="权限异常次数"),
                ),
                (
                    "stale_rules",
                    models.IntegerField(default=0, verbose_name="陈旧规则数"),
                ),
                (
                    "deprecated_rules",
                    models.IntegerField(default=0, verbose_name="废弃规则数"),
                ),
                (
                    "overall_health_score",
                    models.FloatField(default=100.0, verbose_name="整体健康度评分"),
                ),
                (
                    "security_score",
                    models.FloatField(default=100.0, verbose_name="安全评分"),
                ),
                (
                    "performance_score",
                    models.FloatField(default=100.0, verbose_name="性能评分"),
                ),
                (
                    "compliance_score",
                    models.FloatField(default=100.0, verbose_name="合规评分"),
                ),
                ("summary", models.TextField(verbose_name="摘要")),
                (
                    "recommendations",
                    models.JSONField(default=list, verbose_name="建议列表"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "generated_by",
                    models.CharField(
                        default="automatic", max_length=50, verbose_name="生成方式"
                    ),
                ),
            ],
            options={
                "db_table": "self_audit_reports",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "-period_start"],
                        name="self_audit__report__3e0689_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentPermissionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("grant", "授予权限"),
                            ("revoke", "撤销权限"),
                            ("modify", "修改权限"),
                            ("escalate", "权限提升"),
                            ("de-escalate", "权限降低"),
                            ("use", "权限使用"),
                            ("abuse", "权限滥用"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(max_length=50, verbose_name="权限类型"),
                ),
                (
                    "resource_type",
                    models.CharField(max_length=50, verbose_name="资源类型"),
                ),
                (
                    "old_value",
                    models.JSONField(blank=True, null=True, verbose_name="旧值"),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="新值"),
                ),
                ("change_description", models.TextField(verbose_name="变更说明")),
                (
                    "performed_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="执行IP"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("safe", "安全"),
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重风险"),
                        ],
                        default="safe",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "is_anomaly",
                    models.BooleanField(default=False, verbose_name="是否异常"),
                ),
                (
                    "anomaly_reason",
                    models.TextField(blank=True, verbose_name="异常原因"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_audit_logs",
                        to="auth_app.agentidentity",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth_app.agentpermission",
                        verbose_name="关联权限",
                    ),
                ),
            ],
            options={
                "db_table": "agent_permission_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-timestamp"],
                        name="agent_permi_agent_i_ff87a3_idx",
                    ),
                    models.Index(
                        fields=["action", "risk_level"],
                        name="agent_permi_action_77805d_idx",
                    ),
                    models.Index(
                        fields=["is_anomaly", "-timestamp"],
                        name="agent_permi_is_anom_6b7bb8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceDriftRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drift_type",
                    models.CharField(
                        choices=[
                            ("accuracy", "准确率漂移"),
                            ("precision", "精确率漂移"),
                            ("recall", "召回率漂移"),
                            ("f1_score", "F1分数漂移"),
                            ("response_time", "响应时间异常"),
                            ("false_positive_rate", "误报率变化"),
                        ],
                        max_length=50,
                        verbose_name="漂移类型",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "baseline_value",
                    models.FloatField(
                        help_text="历史平均值或阈值", verbose_name="基线值"
                    ),
                ),
                ("current_value", models.FloatField(verbose_name="当前值")),
                (
                    "deviation_rate",
                    models.FloatField(
                        help_text="偏离基线的百分比", verbose_name="偏离率"
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(default=0, verbose_name="样本大小"),
                ),
                (
                    "time_window",
                    models.DurationField(
                        default=datetime.timedelta(seconds=3600),
                        verbose_name="时间窗口",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="是否已解决"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, verbose_name="解决说明"),
                ),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="检测时间"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="额外的上下文信息",
                        verbose_name="元数据",
                    ),
                ),
                (
                    "baseline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth_app.behaviorbaseline",
                        verbose_name="关联基线",
                    ),
                ),
            ],
            options={
                "db_table": "performance_drift_records",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["drift_type", "-detected_at"],
                        name="performance_drift_t_b39007_idx",
                    ),
                    models.Index(
                        fields=["severity", "is_resolved"],
                        name="performance_severit_4d94c4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RuleFreshnessCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("detection_rule", "检测规则"),
                            ("response_policy", "响应策略"),
                            ("risk_assessment", "风险评估"),
                            ("behavior_constraint", "行为约束"),
                        ],
                        max_length=50,
                        verbose_name="规则类型",
                    ),
                ),
                ("last_updated", models.DateTimeField(verbose_name="最后更新时间")),
                (
                    "days_since_update",
                    models.IntegerField(default=0, verbose_name="距上次更新天数"),
                ),
                (
                    "freshness_status",
                    models.CharField(
                        choices=[
                            ("fresh", "新鲜"),
                            ("stale", "陈旧"),
                            ("outdated", "过期"),
                            ("deprecated", "废弃"),
                        ],
                        default="fresh",
                        max_length=20,
                        verbose_name="时效状态",
                    ),
                ),
                (
                    "effectiveness_score",
                    models.FloatField(default=100.0, verbose_name="有效性评分"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "success_rate",
                    models.FloatField(default=100.0, verbose_name="成功率"),
                ),
                ("recommendation", models.TextField(blank=True, verbose_name="建议")),
                (
                    "checked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="检查时间"),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freshness_checks",
                        to="auth_app.strategicmemory",
                        verbose_name="关联策略",
                    ),
                ),
            ],
            options={
                "db_table": "rule_freshness_checks",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "freshness_status"],
                        name="rule_freshn_rule_ty_9f2587_idx",
                    ),
                    models.Index(
                        fields=["days_since_update"],
                        name="rule_freshn_days_si_e9d273_idx",
                    ),
                ],
            },
        ),
    ]
