# Generated by Django 6.0.1 on 2026-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0052_add_self_audit_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorttermmemory",
            name="metadata",
            field=models.JSONField(
                default=dict,
                help_text="可存储响应时间、来源IP等扩展信息",
                verbose_name="元数据",
            ),
        ),
    ]
