# Generated by Django 6.0.1 on 2026-08-12 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0053_add_metadata_to_short_term_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="longtermmemory",
            name="verification_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="人工复核时的备注说明",
                verbose_name="复核说明",
            ),
        ),
        migrations.AddField(
            model_name="longtermmemory",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="复核时间"),
        ),
        migrations.AddField(
            model_name="longtermmemory",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_memories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="复核人",
            ),
        ),
        migrations.AddField(
            model_name="longtermmemory",
            name="verified_result",
            field=models.BooleanField(
                blank=True,
                help_text="True=安全(误报), False=危险(正确), None=未复核",
                null=True,
                verbose_name="人工复核结果",
            ),
        ),
        migrations.AddIndex(
            model_name="longtermmemory",
            index=models.Index(
                fields=["verified_result", "-timestamp"], name="idx_ltm_verified"
            ),
        ),
        migrations.AddIndex(
            model_name="longtermmemory",
            index=models.Index(
                fields=["verified_by", "-verified_at"], name="idx_ltm_verifier"
            ),
        ),
    ]
