# Generated by Django 6.0.1 on 2026-08-12 06:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0054_add_verification_fields_to_long_term_memory"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="文件的完整路径",
                        max_length=1000,
                        verbose_name="文件路径",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_extension",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="文件扩展名"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "文件创建"),
                            ("modify", "文件修改"),
                            ("rename", "文件重命名"),
                            ("delete", "文件删除"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "old_path",
                    models.CharField(
                        blank=True,
                        help_text="重命名操作时的原路径",
                        max_length=1000,
                        verbose_name="原路径",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256哈希值",
                        max_length=64,
                        verbose_name="文件哈希",
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        help_text="用于检测非预期变动",
                        max_length=64,
                        verbose_name="前次哈希",
                    ),
                ),
                (
                    "hash_changed",
                    models.BooleanField(
                        default=False,
                        help_text="用于标识文件内容是否发生变化",
                        verbose_name="哈希是否改变",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("safe", "安全"),
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重风险"),
                        ],
                        default="safe",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("risk_score", models.FloatField(default=0.0, verbose_name="风险分数")),
                (
                    "risk_tags",
                    models.JSONField(
                        default=list,
                        help_text='如：["executable_file", "script_file"]',
                        verbose_name="风险标签",
                    ),
                ),
                (
                    "verification_triggered",
                    models.BooleanField(default=False, verbose_name="是否触发校验"),
                ),
                (
                    "verification_result",
                    models.JSONField(
                        default=dict,
                        help_text="四官协同校验的详细结果",
                        verbose_name="校验结果",
                    ),
                ),
                (
                    "user_confirmed",
                    models.BooleanField(
                        blank=True,
                        help_text="高风险操作时的用户确认结果",
                        null=True,
                        verbose_name="用户确认",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "confirmation_note",
                    models.TextField(blank=True, verbose_name="确认备注"),
                ),
                (
                    "operation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="文件变动的实际发生时间",
                        verbose_name="操作时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="记录创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "文件操作日志",
                "verbose_name_plural": "文件操作日志管理",
                "db_table": "file_operation_logs",
                "ordering": ["-operation_time"],
            },
        ),
        migrations.CreateModel(
            name="FileRiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity_check",
                    models.JSONField(
                        default=dict,
                        help_text="验证用户身份、权限",
                        verbose_name="身份官检查结果",
                    ),
                ),
                (
                    "risk_check",
                    models.JSONField(
                        default=dict,
                        help_text="评估文件风险",
                        verbose_name="风险官检查结果",
                    ),
                ),
                (
                    "verification_check",
                    models.JSONField(
                        default=dict,
                        help_text="二次确认机制",
                        verbose_name="验证官检查结果",
                    ),
                ),
                (
                    "decision_check",
                    models.JSONField(
                        default=dict,
                        help_text="最终决策",
                        verbose_name="决策官检查结果",
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(default=0.0, verbose_name="综合评分"),
                ),
                (
                    "overall_risk_level",
                    models.CharField(
                        choices=[
                            ("safe", "安全"),
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "严重风险"),
                        ],
                        default="safe",
                        max_length=20,
                        verbose_name="综合风险等级",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text='如：["建议隔离文件", "建议重新审核"]',
                        verbose_name="安全建议",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "operation_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessment",
                        to="auth_app.fileoperationlog",
                        verbose_name="操作日志",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件风险评估",
                "verbose_name_plural": "文件风险评估管理",
                "db_table": "file_risk_assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileWatchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watch_path",
                    models.CharField(
                        help_text="绝对路径，如：C:\\漫剧\\素材",
                        max_length=500,
                        verbose_name="监控路径",
                    ),
                ),
                (
                    "watch_name",
                    models.CharField(
                        help_text='用户自定义名称，如："素材目录"',
                        max_length=100,
                        verbose_name="监控名称",
                    ),
                ),
                (
                    "watch_create",
                    models.BooleanField(default=True, verbose_name="监控文件创建"),
                ),
                (
                    "watch_modify",
                    models.BooleanField(default=True, verbose_name="监控文件修改"),
                ),
                (
                    "watch_rename",
                    models.BooleanField(default=True, verbose_name="监控文件重命名"),
                ),
                (
                    "watch_delete",
                    models.BooleanField(default=True, verbose_name="监控文件删除"),
                ),
                (
                    "file_extensions",
                    models.JSONField(
                        default=list,
                        help_text='如：["jpg", "png", "mp4", "py", "js"]，空列表表示监控所有文件',
                        verbose_name="监控的文件扩展名",
                    ),
                ),
                (
                    "exclude_patterns",
                    models.JSONField(
                        default=list,
                        help_text='如：["*.tmp", "*.temp", "~*"]',
                        verbose_name="排除模式",
                    ),
                ),
                (
                    "auto_verify",
                    models.BooleanField(
                        default=True,
                        help_text="文件变动时自动触发四官协同校验",
                        verbose_name="自动触发校验",
                    ),
                ),
                (
                    "risk_threshold",
                    models.CharField(
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                        ],
                        default="medium",
                        help_text="超过此风险等级时弹窗确认",
                        max_length=20,
                        verbose_name="风险阈值",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "total_files",
                    models.IntegerField(default=0, verbose_name="监控文件总数"),
                ),
                (
                    "last_check_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后检查时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_watch_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件监控配置",
                "verbose_name_plural": "文件监控配置管理",
                "db_table": "file_watch_configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="fileoperationlog",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_logs",
                to="auth_app.filewatchconfig",
                verbose_name="监控配置",
            ),
        ),
        migrations.CreateModel(
            name="FileHashRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=1000, verbose_name="文件路径"),
                ),
                (
                    "file_hash",
                    models.CharField(max_length=64, verbose_name="文件哈希(SHA-256)"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="同一文件的哈希更新次数",
                        verbose_name="版本号",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="只有最新版本的is_current为True",
                        verbose_name="是否为当前版本",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hash_records",
                        to="auth_app.filewatchconfig",
                        verbose_name="监控配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件哈希记录",
                "verbose_name_plural": "文件哈希记录管理",
                "db_table": "file_hash_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="filewatchconfig",
            index=models.Index(
                fields=["user", "is_active"], name="idx_fwc_user_active"
            ),
        ),
        migrations.AddIndex(
            model_name="filewatchconfig",
            index=models.Index(fields=["watch_path"], name="idx_fwc_path"),
        ),
        migrations.AddIndex(
            model_name="fileoperationlog",
            index=models.Index(
                fields=["config", "-operation_time"], name="idx_fol_config_time"
            ),
        ),
        migrations.AddIndex(
            model_name="fileoperationlog",
            index=models.Index(fields=["operation_type"], name="idx_fol_op_type"),
        ),
        migrations.AddIndex(
            model_name="fileoperationlog",
            index=models.Index(fields=["risk_level"], name="idx_fol_risk"),
        ),
        migrations.AddIndex(
            model_name="fileoperationlog",
            index=models.Index(fields=["file_hash"], name="idx_fol_hash"),
        ),
        migrations.AddIndex(
            model_name="filehashrecord",
            index=models.Index(
                fields=["file_path", "-created_at"], name="idx_fhr_path_time"
            ),
        ),
        migrations.AddIndex(
            model_name="filehashrecord",
            index=models.Index(fields=["file_hash"], name="idx_fhr_hash"),
        ),
        migrations.AddIndex(
            model_name="filehashrecord",
            index=models.Index(fields=["is_current"], name="idx_fhr_current"),
        ),
    ]
