# Generated by Django 6.0.5 on 2026-08-13 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0055_add_file_watch_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="如：剪映、即梦、Premiere、CapCut、After Effects",
                        max_length=100,
                        verbose_name="工具名称",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(
                        help_text="可执行文件名，如 JianyingPro.exe",
                        max_length=255,
                        verbose_name="进程名称",
                    ),
                ),
                (
                    "pid",
                    models.IntegerField(
                        help_text="本次会话的进程PID", verbose_name="进程PID"
                    ),
                ),
                (
                    "session_start",
                    models.DateTimeField(
                        help_text="进程启动时间", verbose_name="会话开始时间"
                    ),
                ),
                (
                    "session_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="进程退出时间；为空表示仍在运行",
                        null=True,
                        verbose_name="会话结束时间",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="运行时长(秒)"),
                ),
                (
                    "related_files",
                    models.JSONField(
                        default=list,
                        help_text="会话期间发生的文件操作路径列表",
                        verbose_name="关联文件",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="记录创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_usage_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "进程使用记录",
                "verbose_name_plural": "进程使用记录管理",
                "db_table": "process_usage_records",
                "ordering": ["-session_start"],
                "indexes": [
                    models.Index(
                        fields=["user", "-session_start"], name="idx_pur_user_time"
                    ),
                    models.Index(fields=["tool_name"], name="idx_pur_tool"),
                    models.Index(fields=["user", "pid"], name="idx_pur_user_pid"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "pid", "session_start"),
                        name="uniq_pur_user_pid_start",
                    )
                ],
            },
        ),
    ]
