# Generated by Django 6.0.5 on 2026-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0056_processusagerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="processusagerecord",
            name="has_related_files",
            field=models.BooleanField(
                blank=True,
                help_text="null=尚未确定（文件监控未开启/未采集）；false=已扫描但确实无文件操作；true=有文件操作",
                null=True,
                verbose_name="是否已确定关联文件",
            ),
        ),
    ]
