# Generated by Django 6.0.5 on 2026-08-17 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0057_processusagerecord_has_related_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProviderKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("deepseek", "DeepSeek"),
                            ("grok", "Grok"),
                            ("openai", "OpenAI"),
                        ],
                        default="deepseek",
                        max_length=20,
                        verbose_name="服务商",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, verbose_name="密钥别名"
                    ),
                ),
                (
                    "key_encrypted",
                    models.CharField(max_length=1024, verbose_name="加密密钥"),
                ),
                (
                    "key_suffix",
                    models.CharField(
                        blank=True, default="", max_length=8, verbose_name="密钥后缀"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近验证时间"
                    ),
                ),
                (
                    "last_verified_ok",
                    models.BooleanField(default=False, verbose_name="最近验证是否通过"),
                ),
                (
                    "balance",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="余额"
                    ),
                ),
                (
                    "today_used",
                    models.IntegerField(default=0, verbose_name="今日调用次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户自有API密钥",
                "verbose_name_plural": "用户自有API密钥",
                "db_table": "auth_user_provider_key",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider"), name="uniq_user_provider_key"
                    )
                ],
            },
        ),
    ]
