# Generated by Django 6.0.5 on 2026-08-18 08:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0059_apikeyusagelog_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="用户ID"
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="调用ID"
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="场景"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="deepseek", max_length=32, verbose_name="提供商"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="模型"
                    ),
                ),
                (
                    "input_tokens",
                    models.IntegerField(default=0, verbose_name="输入tokens"),
                ),
                (
                    "output_tokens",
                    models.IntegerField(default=0, verbose_name="输出tokens"),
                ),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="总tokens"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="费用(元)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("error", "失败")],
                        db_index=True,
                        default="success",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI调用计费记录",
                "verbose_name_plural": "AI调用计费记录",
                "db_table": "auth_app_api_call_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
