# Generated by Django 6.0.5 on 2026-08-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0060_apicalllog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favorites",
            field=models.JSONField(blank=True, default=list, verbose_name="收藏列表"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="layout",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="界面布局偏好"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="个性化主题"
            ),
        ),
    ]
