# Generated by Django 6.0.5 on 2026-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0061_userprofile_favorites_userprofile_layout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HourlyRegionStats",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("hour", models.DateTimeField(db_index=True, verbose_name="小时")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("cn", "中国大陆"),
                            ("us", "北美"),
                            ("eu", "欧洲"),
                            ("all", "其他/全局"),
                        ],
                        db_index=True,
                        default="all",
                        max_length=10,
                        verbose_name="区域",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=14,
                        verbose_name="消耗额度(元)",
                    ),
                ),
                (
                    "call_count",
                    models.PositiveIntegerField(default=0, verbose_name="调用次数"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="错误次数"),
                ),
                (
                    "avg_latency",
                    models.PositiveIntegerField(default=0, verbose_name="平均耗时(ms)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "每小时区域监控",
                "verbose_name_plural": "每小时区域监控",
                "db_table": "hourly_region_stats",
                "ordering": ["-hour", "region"],
                "indexes": [
                    models.Index(fields=["hour", "region"], name="idx_hour_region")
                ],
            },
        ),
    ]
