# Generated by Django 6.0.5 on 2026-08-21 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0062_hourlyregionstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquota",
            name="trial_claimed",
            field=models.BooleanField(
                default=False, verbose_name="是否已领取过免费试用"
            ),
        ),
        migrations.CreateModel(
            name="RedemptionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=32, unique=True, verbose_name="兑换码"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="vip_monthly", max_length=20, verbose_name="类型"
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="开通时长(天)"
                    ),
                ),
                (
                    "vip_level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "基础"), (2, "高级"), (3, "企业")],
                        default=1,
                        verbose_name="开通等级",
                    ),
                ),
                (
                    "total_uses",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1=一次性；N=批量码/可多次",
                        verbose_name="总可兑换次数",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="已兑换次数"),
                ),
                (
                    "redeem_code_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="批量生成时同批数量",
                        verbose_name="生成数量",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有效"),
                            ("disabled", "已停用"),
                            ("expired", "已过期"),
                        ],
                        default="active",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="兑换码过期时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redemption_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="生成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "兑换码",
                "verbose_name_plural": "兑换码",
                "db_table": "redemption_code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RedemptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granted_days",
                    models.PositiveIntegerField(default=0, verbose_name="发放天数"),
                ),
                (
                    "granted_level",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="发放等级"
                    ),
                ),
                (
                    "new_expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="兑换后到期时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "redemption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemption_records",
                        to="auth_app.redemptioncode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redemption_uses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "兑换码使用记录",
                "verbose_name_plural": "兑换码使用记录",
                "db_table": "redemption_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
