# Generated by Django 5.2.14 on 2026-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0002_category_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="covers/%Y/%m/", verbose_name="封面图"
            ),
        ),
    ]
