# Generated by Django 5.2.14 on 2026-05-25 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0003_article_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "avatar",
                    models.URLField(blank=True, default="", verbose_name="头像"),
                ),
                ("bio", models.TextField(blank=True, default="", verbose_name="简介")),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="邮箱"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "作者",
                "verbose_name_plural": "作者",
                "db_table": "content_author",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="标签名"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL标识")),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "db_table": "content_tag",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at", "-created_at"],
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="comment_count",
            field=models.IntegerField(default=0, verbose_name="评论数"),
        ),
        migrations.AddField(
            model_name="article",
            name="is_recommended",
            field=models.BooleanField(default=False, verbose_name="是否推荐"),
        ),
        migrations.AddField(
            model_name="article",
            name="like_count",
            field=models.IntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
        ),
        migrations.AddField(
            model_name="article",
            name="read_count",
            field=models.IntegerField(default=0, verbose_name="阅读量"),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                default="folder", max_length=50, verbose_name="图标"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(default="", verbose_name="内容（Markdown）"),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.URLField(blank=True, default="", verbose_name="封面图"),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("published", "已发布"),
                    ("archived", "已归档"),
                ],
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="摘要"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=500, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="content_app.frontauthor",
                verbose_name="作者",
            ),
        ),
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_tags",
                        to="content_app.article",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_articles",
                        to="content_app.tag",
                    ),
                ),
            ],
            options={
                "db_table": "content_article_tag",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                through="content_app.ArticleTag",
                to="content_app.tag",
                verbose_name="标签",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["status"], name="idx_article_status"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["-published_at"], name="idx_article_published"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["-read_count"], name="idx_article_read_count"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["category"], name="idx_article_category"),
        ),
        migrations.AlterUniqueTogether(
            name="articletag",
            unique_together={("article", "tag")},
        ),
    ]
