# Generated by Django 5.2.14 on 2026-05-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0004_frontauthor_tag_alter_article_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=0, verbose_name="用户ID")),
                (
                    "username",
                    models.CharField(
                        default="匿名用户", max_length=50, verbose_name="用户名"
                    ),
                ),
                ("avatar", models.URLField(default="", verbose_name="头像")),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "ip_address",
                    models.GenericIPAddressField(default="", verbose_name="IP地址"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="是否审核通过"),
                ),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="content_app.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="content_app.articlecomment",
                        verbose_name="父评论",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章评论",
                "verbose_name_plural": "文章评论",
                "db_table": "content_article_comment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["article", "-created_at"],
                        name="idx_comment_article_time",
                    ),
                    models.Index(fields=["is_approved"], name="idx_comment_approved"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticleLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                (
                    "ip_address",
                    models.GenericIPAddressField(default="", verbose_name="IP地址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="content_app.article",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章点赞",
                "verbose_name_plural": "文章点赞",
                "db_table": "content_article_like",
                "unique_together": {("article", "user_id", "ip_address")},
            },
        ),
    ]
