# Generated by Django 6.0.1 on 2026-05-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0005_add_like_comment_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="content_app.frontauthor",
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户关注",
                "verbose_name_plural": "用户关注",
                "db_table": "content_user_follow",
                "unique_together": {("user_id", "author")},
            },
        ),
    ]
