# Generated by Django 6.0.1 on 2026-05-26 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0006_userfollow"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL标识"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="folder", max_length=50, verbose_name="图标"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "document_count",
                    models.IntegerField(default=0, verbose_name="文档数量"),
                ),
                (
                    "chunk_count",
                    models.IntegerField(default=0, verbose_name="分片数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "知识库分类",
                "verbose_name_plural": "知识库分类",
                "db_table": "rag_kb_category",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="文档标题")),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(bytes)"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF文档"),
                            ("word", "Word文档"),
                            ("txt", "文本文件"),
                            ("markdown", "Markdown"),
                            ("excel", "Excel表格"),
                            ("html", "HTML网页"),
                            ("json", "JSON数据"),
                            ("other", "其他格式"),
                        ],
                        default="txt",
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "上传中"),
                            ("parsing", "解析中"),
                            ("chunking", "分块中"),
                            ("embedding", "向量化中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="uploading",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="处理进度(%)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "page_count",
                    models.IntegerField(default=0, verbose_name="页数/段数"),
                ),
                ("word_count", models.IntegerField(default=0, verbose_name="字数")),
                (
                    "chunk_count",
                    models.IntegerField(default=0, verbose_name="分片数量"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="文档摘要"),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, verbose_name="关键词列表"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="是否公开"),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="允许访问的角色ID列表"
                    ),
                ),
                (
                    "uploaded_by",
                    models.IntegerField(default=0, verbose_name="上传人ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="content_app.knowledgebasecategory",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库文档",
                "verbose_name_plural": "知识库文档",
                "db_table": "rag_kb_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(verbose_name="分片序号")),
                ("content", models.TextField(verbose_name="分片内容")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "page_number",
                    models.IntegerField(default=0, verbose_name="页码/段落号"),
                ),
                (
                    "section_title",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="章节标题"
                    ),
                ),
                (
                    "embedding",
                    models.TextField(
                        blank=True, default="", verbose_name="向量数据(Base64编码)"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-ada-002",
                        max_length=100,
                        verbose_name="嵌入模型",
                    ),
                ),
                (
                    "token_count",
                    models.IntegerField(default=0, verbose_name="Token数量"),
                ),
                ("char_count", models.IntegerField(default=0, verbose_name="字符数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="content_app.knowledgedocument",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档分片",
                "verbose_name_plural": "文档分片",
                "db_table": "rag_kb_chunk",
                "ordering": ["document_id", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="RetrievalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(verbose_name="查询内容")),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("semantic", "语义检索"),
                            ("keyword", "关键词检索"),
                            ("hybrid", "混合检索"),
                        ],
                        default="hybrid",
                        max_length=20,
                        verbose_name="检索类型",
                    ),
                ),
                (
                    "results_count",
                    models.IntegerField(default=0, verbose_name="结果数量"),
                ),
                (
                    "top_chunks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Top-K分片ID列表"
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(default=0, verbose_name="响应时间(ms)"),
                ),
                ("user_id", models.IntegerField(default=0, verbose_name="用户ID")),
                (
                    "session_id",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="会话ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(default="", verbose_name="IP地址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "检索日志",
                "verbose_name_plural": "检索日志",
                "db_table": "rag_retrieval_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "-created_at"],
                        name="idx_retrieval_user_time",
                    ),
                    models.Index(fields=["query_type"], name="idx_retrieval_type"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["category", "-created_at"], name="idx_doc_category_time"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["status"], name="idx_doc_status"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["is_public"], name="idx_doc_public"),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document_id", "chunk_index"], name="idx_chunk_doc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(fields=["embedding_model"], name="idx_chunk_model"),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
