# Generated by Django 6.0.1 on 2026-05-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0007_add_rag_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "文档上传"),
                            ("delete", "文档删除"),
                            ("re_vectorize", "重新向量化"),
                            ("search", "检索查询"),
                            ("ask", "RAG问答"),
                            ("category_create", "创建分类"),
                            ("category_update", "更新分类"),
                            ("category_delete", "删除分类"),
                            ("chunk_delete", "删除分片"),
                            ("export", "导出数据"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        default="", max_length=20, verbose_name="目标类型"
                    ),
                ),
                (
                    "target_id",
                    models.IntegerField(blank=True, null=True, verbose_name="目标ID"),
                ),
                (
                    "target_name",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="目标名称"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="操作用户ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="操作用户名",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "request_detail",
                    models.JSONField(blank=True, default=dict, verbose_name="请求详情"),
                ),
                (
                    "response_detail",
                    models.JSONField(blank=True, default=dict, verbose_name="响应详情"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(default=0, verbose_name="耗时(ms)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
            ],
            options={
                "db_table": "rag_operation_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="rag_operati_action_efe749_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="rag_operati_target__6555f0_idx",
                    ),
                    models.Index(
                        fields=["user_id", "-created_at"],
                        name="rag_operati_user_id_e59cb7_idx",
                    ),
                    models.Index(
                        fields=["status"], name="rag_operati_status_8d4787_idx"
                    ),
                ],
            },
        ),
    ]
