# Generated by Django 6.0.1 on 2026-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0008_ragoperationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="副标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="详细描述"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="封面图片URL",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="跳转链接"
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("article", "文章"),
                            ("url", "外部链接"),
                            ("action", "内部动作"),
                        ],
                        default="article",
                        max_length=20,
                        verbose_name="链接类型",
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#2563EB", max_length=7, verbose_name="背景色"
                    ),
                ),
                (
                    "category_tag",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="分类标签"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "停用")],
                        default="active",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(default=0, verbose_name="点击次数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "轮播图管理",
                "verbose_name_plural": "轮播图管理",
                "db_table": "content_banner",
                "ordering": ["-sort_order", "-id"],
            },
        ),
    ]
