# Generated by Django 6.0.1 on 2026-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0009_add_banner_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cta_link",
            field=models.URLField(blank=True, default="", verbose_name="CTA链接"),
        ),
        migrations.AddField(
            model_name="article",
            name="cta_text",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="CTA文字"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="hook_line",
            field=models.TextField(blank=True, default="", verbose_name="扎心钩子"),
        ),
        migrations.AddField(
            model_name="article",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="是否精选置顶"),
        ),
        migrations.AddField(
            model_name="article",
            name="real_case_title",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="案例标题"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="xinfa_tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agent_pitfall", "Agent避坑"),
                    ("dev_survival", "开发保命"),
                    ("corp_compliance", "企业合规"),
                    ("pitfall_records", "踩坑实录"),
                    ("", "无"),
                ],
                default="",
                help_text="Agent避坑/开发保命/企业合规/踩坑实录",
                max_length=20,
                verbose_name="心法标签",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="zone_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dev", "个人开发者专区"),
                    ("enterprise", "企业部署专区"),
                    ("multi_agent", "多智能体专区"),
                    ("pitfall_records", "真实踩坑专区"),
                    ("", "默认"),
                ],
                default="",
                help_text="个人开发者/企业部署/多智能体/真实踩坑",
                max_length=20,
                verbose_name="Agent专区",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["xinfa_tag"], name="idx_article_xinfa_tag"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["is_pinned"], name="idx_article_is_pinned"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["zone_id"], name="idx_article_zone_id"),
        ),
    ]
