# Generated by Django 6.0.1 on 2026-05-31 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_app",
            "0010_article_cta_link_article_cta_text_article_hook_line_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BScenarioDesignDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "design_type",
                    models.CharField(
                        choices=[
                            ("ui_design", "UI设计稿"),
                            ("ux_wireframe", "UX线框图"),
                            ("graphic_design", "平面设计"),
                            ("logo_design", "Logo设计"),
                            ("illustration", "插画作品"),
                            ("3d_model", "3D模型"),
                            ("motion_graphics", "动效设计"),
                            ("brand_identity", "品牌VI设计"),
                            ("other", "其他设计稿"),
                        ],
                        max_length=20,
                        verbose_name="设计类型",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="文件名"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(bytes)"
                    ),
                ),
                (
                    "original_text",
                    models.TextField(
                        blank=True, default="", verbose_name="原始文本/描述"
                    ),
                ),
                (
                    "image_preview_url",
                    models.URLField(blank=True, default="", verbose_name="预览图URL"),
                ),
                (
                    "ai_generated_prob",
                    models.FloatField(default=0, verbose_name="AI生成概率(0-1)"),
                ),
                (
                    "plagiarism_score",
                    models.FloatField(default=0, verbose_name="抄袭相似度(0-100)"),
                ),
                (
                    "originality_score",
                    models.FloatField(default=100, verbose_name="原创度评分(0-100)"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "高风险"),
                            ("medium", "中风险"),
                            ("low", "低风险"),
                            ("safe", "安全"),
                        ],
                        default="safe",
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待检测"),
                            ("processing", "检测中"),
                            ("completed", "已完成"),
                            ("failed", "检测失败"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "detection_result",
                    models.JSONField(default=dict, verbose_name="检测结果详情"),
                ),
                (
                    "plagiarism_sources",
                    models.JSONField(default=list, verbose_name="疑似抄袭来源列表"),
                ),
                (
                    "ai_style_markers",
                    models.JSONField(default=list, verbose_name="AI风格特征列表"),
                ),
                (
                    "ai_indicators",
                    models.JSONField(default=dict, verbose_name="AI生成指标"),
                ),
                (
                    "professional_report",
                    models.TextField(
                        blank=True, default="", verbose_name="原创度分析报告"
                    ),
                ),
                (
                    "designer_alias",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="设计师昵称(脱敏)",
                    ),
                ),
                (
                    "design_tool",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="使用工具"
                    ),
                ),
                (
                    "color_palette",
                    models.JSONField(default=list, verbose_name="色彩方案"),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="尺寸规格"
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_drafts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "B级-设计稿鉴别",
                "verbose_name_plural": "B级-设计稿鉴别",
                "db_table": "bscenario_design_draft",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_design_user_time"
                    ),
                    models.Index(fields=["status"], name="idx_design_status"),
                    models.Index(fields=["risk_level"], name="idx_design_risk"),
                    models.Index(fields=["design_type"], name="idx_design_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BScenarioFinancialStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statement_type",
                    models.CharField(
                        choices=[
                            ("balance_sheet", "资产负债表"),
                            ("income_statement", "利润表"),
                            ("cash_flow", "现金流量表"),
                            ("equity_change", "所有者权益变动表"),
                            ("audit_report", "审计报告"),
                            ("financial_notes", "财务报表附注"),
                            ("other", "其他财务文件"),
                        ],
                        max_length=20,
                        verbose_name="报表类型",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="文件名"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(bytes)"
                    ),
                ),
                ("original_text", models.TextField(verbose_name="原始文本内容")),
                (
                    "ai_generated_prob",
                    models.FloatField(default=0, verbose_name="AI生成概率(0-1)"),
                ),
                (
                    "fraud_risk_score",
                    models.FloatField(default=0, verbose_name="造假风险评分(0-100)"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "高风险"),
                            ("medium", "中风险"),
                            ("low", "低风险"),
                            ("safe", "安全"),
                        ],
                        default="safe",
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待检测"),
                            ("processing", "检测中"),
                            ("completed", "已完成"),
                            ("failed", "检测失败"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "detection_result",
                    models.JSONField(default=dict, verbose_name="检测结果详情"),
                ),
                (
                    "fraud_indicators",
                    models.JSONField(default=list, verbose_name="造假指标列表"),
                ),
                (
                    "anomaly_items",
                    models.JSONField(default=list, verbose_name="异常项目列表"),
                ),
                (
                    "ai_indicators",
                    models.JSONField(default=dict, verbose_name="AI生成指标"),
                ),
                (
                    "professional_report",
                    models.TextField(
                        blank=True, default="", verbose_name="专业审计报告"
                    ),
                ),
                (
                    "company_name_masked",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="企业名称(脱敏)",
                    ),
                ),
                (
                    "reporting_period",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="报告期间"
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="资产总额(元)",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="营收总额(元)",
                    ),
                ),
                (
                    "audit_firm",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="会计师事务所",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_statements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "B级-财务报表鉴别",
                "verbose_name_plural": "B级-财务报表鉴别",
                "db_table": "bscenario_financial_statement",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_finance_user_time"
                    ),
                    models.Index(fields=["status"], name="idx_finance_status"),
                    models.Index(fields=["risk_level"], name="idx_finance_risk"),
                    models.Index(fields=["statement_type"], name="idx_finance_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BScenarioLegalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("contract", "合同协议"),
                            ("litigation", "诉讼文书"),
                            ("intellectual_property", "知识产权文件"),
                            ("company_governance", "公司治理文件"),
                            ("compliance", "合规文件"),
                            ("legal_opinion", "法律意见书"),
                            ("other", "其他法律文书"),
                        ],
                        max_length=30,
                        verbose_name="文书类型",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="文件名"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(bytes)"
                    ),
                ),
                ("original_text", models.TextField(verbose_name="原始文本内容")),
                (
                    "ai_generated_prob",
                    models.FloatField(default=0, verbose_name="AI生成概率(0-1)"),
                ),
                (
                    "legal_risk_score",
                    models.FloatField(default=0, verbose_name="法律风险评分(0-100)"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "高风险"),
                            ("medium", "中风险"),
                            ("low", "低风险"),
                            ("safe", "安全"),
                        ],
                        default="safe",
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待检测"),
                            ("processing", "检测中"),
                            ("completed", "已完成"),
                            ("failed", "检测失败"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "detection_result",
                    models.JSONField(default=dict, verbose_name="检测结果详情"),
                ),
                (
                    "legal_risks",
                    models.JSONField(default=list, verbose_name="法律风险列表"),
                ),
                (
                    "compliance_issues",
                    models.JSONField(default=list, verbose_name="合规问题列表"),
                ),
                (
                    "ai_indicators",
                    models.JSONField(default=dict, verbose_name="AI生成指标"),
                ),
                (
                    "professional_report",
                    models.TextField(
                        blank=True, default="", verbose_name="专业鉴别报告"
                    ),
                ),
                (
                    "parties_involved",
                    models.JSONField(default=list, verbose_name="相关方信息(脱敏)"),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="管辖区域"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="生效日期"),
                ),
                (
                    "doc_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="涉及金额(元)",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "B级-法律文书鉴别",
                "verbose_name_plural": "B级-法律文书鉴别",
                "db_table": "bscenario_legal_document",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_legal_user_time"
                    ),
                    models.Index(fields=["status"], name="idx_legal_status"),
                    models.Index(fields=["risk_level"], name="idx_legal_risk"),
                    models.Index(fields=["doc_type"], name="idx_legal_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BScenarioMedicalReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("lab_report", "检验报告"),
                            ("imaging_report", "影像报告"),
                            ("pathology_report", "病理报告"),
                            ("discharge_summary", "出院小结"),
                            ("prescription", "处方单"),
                            ("other", "其他医疗文书"),
                        ],
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="文件名"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(bytes)"
                    ),
                ),
                ("original_text", models.TextField(verbose_name="原始文本内容")),
                (
                    "ai_generated_prob",
                    models.FloatField(default=0, verbose_name="AI生成概率(0-1)"),
                ),
                (
                    "medical_error_score",
                    models.FloatField(
                        default=0, verbose_name="医疗错误风险评分(0-100)"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "高风险"),
                            ("medium", "中风险"),
                            ("low", "低风险"),
                            ("safe", "安全"),
                        ],
                        default="safe",
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待检测"),
                            ("processing", "检测中"),
                            ("completed", "已完成"),
                            ("failed", "检测失败"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "detection_result",
                    models.JSONField(default=dict, verbose_name="检测结果详情"),
                ),
                (
                    "medical_issues",
                    models.JSONField(default=list, verbose_name="医疗问题列表"),
                ),
                (
                    "ai_indicators",
                    models.JSONField(default=dict, verbose_name="AI生成指标"),
                ),
                (
                    "professional_report",
                    models.TextField(
                        blank=True, default="", verbose_name="专业鉴别报告"
                    ),
                ),
                (
                    "patient_id_masked",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="患者ID(脱敏)",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="医疗机构"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="科室"
                    ),
                ),
                (
                    "report_date",
                    models.DateField(blank=True, null=True, verbose_name="报告日期"),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "B级-医疗报告鉴别",
                "verbose_name_plural": "B级-医疗报告鉴别",
                "db_table": "bscenario_medical_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_medical_user_time"
                    ),
                    models.Index(fields=["status"], name="idx_medical_status"),
                    models.Index(fields=["risk_level"], name="idx_medical_risk"),
                    models.Index(fields=["report_type"], name="idx_medical_type"),
                ],
            },
        ),
    ]
