# Generated by Django 6.0.1 on 2026-05-31 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0012_tech_provenance_deepfake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseSecurityAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enterprise_name",
                    models.CharField(max_length=200, verbose_name="企业名称"),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="行业领域"
                    ),
                ),
                (
                    "employee_count",
                    models.PositiveIntegerField(default=0, verbose_name="员工规模"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="负责人"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "audit_name",
                    models.CharField(max_length=200, verbose_name="审计任务名称"),
                ),
                (
                    "audit_scope",
                    models.CharField(
                        choices=[
                            ("full_content", "全量内容审计"),
                            ("ai_generated_only", "仅AI生成检测"),
                            ("sensitive_data", "敏感数据审计"),
                            ("compliance_focused", "合规专项审计"),
                            ("custom", "自定义范围"),
                        ],
                        max_length=20,
                        verbose_name="审计范围",
                    ),
                ),
                (
                    "audit_config",
                    models.JSONField(
                        default=dict, verbose_name="审计配置(关键词/规则/阈值)"
                    ),
                ),
                (
                    "scheduled_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "实时"),
                            ("hourly", "每小时"),
                            ("daily", "每日"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                            ("manual", "手动"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="监控频率",
                    ),
                ),
                (
                    "alert_threshold",
                    models.JSONField(default=dict, verbose_name="告警阈值配置"),
                ),
                (
                    "total_items_scanned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="已扫描项目总数"
                    ),
                ),
                (
                    "risk_items_found",
                    models.PositiveIntegerField(default=0, verbose_name="发现风险项数"),
                ),
                (
                    "critical_count",
                    models.PositiveIntegerField(default=0, verbose_name="严重风险数"),
                ),
                (
                    "high_count",
                    models.PositiveIntegerField(default=0, verbose_name="高风险数"),
                ),
                (
                    "medium_count",
                    models.PositiveIntegerField(default=0, verbose_name="中风险数"),
                ),
                (
                    "low_count",
                    models.PositiveIntegerField(default=0, verbose_name="低风险数"),
                ),
                (
                    "overall_risk_score",
                    models.FloatField(default=0, verbose_name="综合风险评分(0-100)"),
                ),
                (
                    "compliance_score",
                    models.FloatField(default=100, verbose_name="合规评分(0-100)"),
                ),
                (
                    "audit_results",
                    models.JSONField(default=list, verbose_name="审计结果明细"),
                ),
                (
                    "active_alerts",
                    models.JSONField(default=list, verbose_name="活跃告警列表"),
                ),
                (
                    "alert_history",
                    models.JSONField(default=list, verbose_name="历史告警记录"),
                ),
                (
                    "remediation_tracking",
                    models.JSONField(default=list, verbose_name="整改跟踪记录"),
                ),
                (
                    "dashboard_snapshot",
                    models.JSONField(default=dict, verbose_name="仪表盘快照数据"),
                ),
                (
                    "compliance_standards",
                    models.JSONField(
                        default=list,
                        verbose_name="对照合规标准(等保2.0/ISO27001/PIPL等)",
                    ),
                ),
                (
                    "executive_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="高管摘要报告"
                    ),
                ),
                (
                    "detailed_audit_report",
                    models.TextField(
                        blank=True, default="", verbose_name="详细审计报告"
                    ),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="合同金额(元/年)",
                    ),
                ),
                (
                    "audit_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="审计周期起始"
                    ),
                ),
                (
                    "audit_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="审计周期结束"
                    ),
                ),
                (
                    "next_audit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="下次审计日期"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("configured", "已配置"),
                            ("running", "审计中"),
                            ("paused", "已暂停"),
                            ("completed", "已完成"),
                            ("expired", "已过期"),
                        ],
                        default="configured",
                        max_length=14,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次运行时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="企业用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "C级-企业级安全审计",
                "verbose_name_plural": "C级-企业级安全审计",
                "db_table": "cscenario_enterprise_audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseAuditAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "严重"),
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                            ("info", "信息"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(max_length=50, verbose_name="告警类型"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="告警标题")),
                ("description", models.TextField(verbose_name="详细描述")),
                (
                    "affected_resource",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="受影响资源",
                    ),
                ),
                (
                    "detection_method",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="检测方式"
                    ),
                ),
                (
                    "raw_evidence",
                    models.JSONField(default=dict, verbose_name="原始证据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                            ("dismissed", "已忽略"),
                        ],
                        default="active",
                        max_length=14,
                        verbose_name="状态",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, default="", verbose_name="解决备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="content_app.enterprisesecurityaudit",
                        verbose_name="关联审计",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计告警",
                "verbose_name_plural": "审计告警",
                "db_table": "cscenario_audit_alert",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AcademicIntegrityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="所属机构"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="院系/部门"
                    ),
                ),
                (
                    "submitter_role",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="提交者身份(学生/教师/研究员)",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("research_paper", "学术论文/期刊论文"),
                            ("degree_thesis", "学位论文(本科/硕士/博士)"),
                            ("coursework", "课程作业"),
                            ("lab_report", "实验报告"),
                            ("project_report", "项目报告/结题报告"),
                            ("conference_paper", "会议论文"),
                            ("grant_application", "基金申请书"),
                            ("patent_doc", "专利文档"),
                            ("other", "其他学术文档"),
                        ],
                        max_length=20,
                        verbose_name="文档类型",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="文件名"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(bytes)"
                    ),
                ),
                (
                    "file_hash_sha256",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="SHA256哈希"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="文档标题"
                    ),
                ),
                (
                    "author_names",
                    models.JSONField(default=list, verbose_name="作者列表"),
                ),
                (
                    "abstract_text",
                    models.TextField(blank=True, default="", verbose_name="摘要"),
                ),
                ("full_content", models.TextField(verbose_name="全文内容")),
                (
                    "word_count",
                    models.PositiveIntegerField(default=0, verbose_name="字数"),
                ),
                (
                    "reference_count",
                    models.PositiveIntegerField(default=0, verbose_name="引用数量"),
                ),
                (
                    "overall_verdict",
                    models.CharField(
                        choices=[
                            ("original", "原创"),
                            ("minor_issue", "轻微问题(需修改)"),
                            ("moderate_concern", "中度关注(需重审)"),
                            ("serious_violation", "严重违规(学术不端)"),
                            ("plagiarism_confirmed", "确认抄袭"),
                            ("ai_generated_confirmed", "确认AI代写"),
                            ("mixed_violation", "混合违规"),
                            ("inconclusive", "无法判定"),
                        ],
                        default="inconclusive",
                        max_length=24,
                        verbose_name="综合判定",
                    ),
                ),
                (
                    "integrity_score",
                    models.FloatField(default=100, verbose_name="学术诚信评分(0-100)"),
                ),
                (
                    "ai_detection_result",
                    models.JSONField(default=dict, verbose_name="AI生成检测结果"),
                ),
                (
                    "ai_generated_probability",
                    models.FloatField(default=0, verbose_name="AI生成概率(0-1)"),
                ),
                (
                    "ai_generated_sections",
                    models.JSONField(default=list, verbose_name="疑似AI生成的段落"),
                ),
                (
                    "plagiarism_result",
                    models.JSONField(default=dict, verbose_name="查重检测结果"),
                ),
                (
                    "overall_similarity",
                    models.FloatField(default=0, verbose_name="总体相似度(0-1)"),
                ),
                (
                    "plagiarism_sources",
                    models.JSONField(default=list, verbose_name="相似来源列表"),
                ),
                (
                    "matched_segments",
                    models.JSONField(default=list, verbose_name="匹配段落详情"),
                ),
                (
                    "citation_analysis",
                    models.JSONField(default=dict, verbose_name="引用规范性分析"),
                ),
                (
                    "fabrication_check",
                    models.JSONField(default=dict, verbose_name="数据伪造检测"),
                ),
                (
                    "image_manipulation",
                    models.JSONField(default=list, verbose_name="图片篡改检测"),
                ),
                (
                    "authorship_analysis",
                    models.JSONField(default=dict, verbose_name="署名真实性分析"),
                ),
                (
                    "violation_categories",
                    models.JSONField(default=list, verbose_name="违规类别详情"),
                ),
                (
                    "recommended_actions",
                    models.JSONField(default=list, verbose_name="建议措施"),
                ),
                (
                    "academic_report",
                    models.TextField(
                        blank=True, default="", verbose_name="学术不端检测报告"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待检测"),
                            ("analyzing", "分析中"),
                            ("completed", "已完成"),
                            ("failed", "检测失败"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "C级-学术不端全链路检测",
                "verbose_name_plural": "C级-学术不端全链路检测",
                "db_table": "cscenario_academic_integrity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_academic_user_time"
                    ),
                    models.Index(fields=["status"], name="idx_academic_status"),
                    models.Index(
                        fields=["overall_verdict"], name="idx_academic_verdict"
                    ),
                    models.Index(fields=["document_type"], name="idx_academic_type"),
                    models.Index(fields=["institution"], name="idx_academic_inst"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="enterprisesecurityaudit",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_ent_audit_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="enterprisesecurityaudit",
            index=models.Index(fields=["status"], name="idx_ent_audit_status"),
        ),
        migrations.AddIndex(
            model_name="enterprisesecurityaudit",
            index=models.Index(
                fields=["enterprise_name"], name="idx_ent_audit_company"
            ),
        ),
        migrations.AddIndex(
            model_name="enterprisesecurityaudit",
            index=models.Index(fields=["audit_scope"], name="idx_ent_audit_scope"),
        ),
        migrations.AddIndex(
            model_name="enterprisesecurityaudit",
            index=models.Index(
                fields=["-overall_risk_score"], name="idx_ent_audit_risk"
            ),
        ),
        migrations.AddIndex(
            model_name="enterpriseauditalert",
            index=models.Index(
                fields=["audit", "-created_at"], name="idx_alert_audit_time"
            ),
        ),
        migrations.AddIndex(
            model_name="enterpriseauditalert",
            index=models.Index(
                fields=["severity", "status"], name="idx_alert_sev_status"
            ),
        ),
        migrations.AddIndex(
            model_name="enterpriseauditalert",
            index=models.Index(fields=["alert_type"], name="idx_alert_type"),
        ),
    ]
