# Generated by Django 6.0.1 on 2026-05-31 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0017_papersubmission_chapteranalysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlagiarismScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_text", models.TextField(verbose_name="待检测文本")),
                (
                    "text_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="文本哈希(SHA256)"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("marketing_copy", "营销文案"),
                            ("product_description", "产品描述"),
                            ("ad_slogan", "广告标语"),
                            ("brand_story", "品牌故事"),
                            ("landing_page", "落地页文案"),
                            ("social_media", "社交媒体文案"),
                            ("email_copy", "邮件营销"),
                            ("press_release", "新闻通稿"),
                            ("blog_article", "博客文章"),
                            ("academic_paper", "学术论文"),
                            ("general_content", "通用内容"),
                        ],
                        default="general_content",
                        max_length=30,
                        verbose_name="内容类型",
                    ),
                ),
                (
                    "overall_similarity",
                    models.FloatField(default=0.0, verbose_name="整体相似度(0-100)"),
                ),
                (
                    "unique_score",
                    models.FloatField(default=100.0, verbose_name="原创度(0-100)"),
                ),
                (
                    "plagiarism_risk",
                    models.CharField(
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中等风险"),
                            ("high", "高风险"),
                            ("critical", "严重风险"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="抄袭风险等级",
                    ),
                ),
                (
                    "match_count",
                    models.IntegerField(default=0, verbose_name="匹配源数量"),
                ),
                (
                    "total_sources",
                    models.IntegerField(default=0, verbose_name="检索到的总源数"),
                ),
                (
                    "exact_matches",
                    models.IntegerField(default=0, verbose_name="完全匹配数"),
                ),
                (
                    "near_duplicates",
                    models.IntegerField(default=0, verbose_name="近似重复数"),
                ),
                (
                    "paraphrased",
                    models.IntegerField(default=0, verbose_name="改写匹配数"),
                ),
                (
                    "plagiarism_breakdown",
                    models.JSONField(default=dict, verbose_name="抄袭类型分布"),
                ),
                (
                    "platform_distribution",
                    models.JSONField(default=dict, verbose_name="平台分布"),
                ),
                (
                    "sentence_analyses",
                    models.JSONField(default=list, verbose_name="逐句分析结果"),
                ),
                (
                    "executive_summary",
                    models.TextField(blank=True, verbose_name="执行摘要"),
                ),
                (
                    "detailed_report",
                    models.TextField(blank=True, verbose_name="详细报告"),
                ),
                (
                    "improvement_suggestions",
                    models.JSONField(default=list, verbose_name="改进建议"),
                ),
                (
                    "scan_metadata",
                    models.JSONField(default=dict, verbose_name="扫描元数据"),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "plagiarism_scan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(max_length=500, verbose_name="来源URL")),
                (
                    "source_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="来源标题"
                    ),
                ),
                ("domain", models.CharField(max_length=200, verbose_name="域名")),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("website", "网站"),
                            ("ecommerce", "电商平台"),
                            ("social_media", "社交媒体"),
                            ("news", "新闻媒体"),
                            ("blog", "博客"),
                            ("forum", "论坛"),
                            ("document", "文档库"),
                            ("unknown", "未知"),
                        ],
                        default="website",
                        max_length=30,
                        verbose_name="平台类型",
                    ),
                ),
                (
                    "similarity_percent",
                    models.FloatField(default=0.0, verbose_name="相似度百分比"),
                ),
                (
                    "matched_words",
                    models.IntegerField(default=0, verbose_name="匹配字数"),
                ),
                ("total_words", models.IntegerField(default=0, verbose_name="总字数")),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact_copy", "完全复制"),
                            ("minor_edits", "轻微修改"),
                            ("restructured", "结构调整"),
                            ("paraphrased", "改写重述"),
                            ("translated", "翻译复制"),
                            ("ai_rewritten", "AI改写"),
                            ("fragment_match", "片段匹配"),
                        ],
                        default="exact_copy",
                        max_length=25,
                        verbose_name="匹配类型",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(default=0.0, verbose_name="置信度(0-1)"),
                ),
                (
                    "matched_snippets",
                    models.JSONField(default=list, verbose_name="匹配片段列表"),
                ),
                (
                    "source_excerpt",
                    models.TextField(blank=True, verbose_name="来源摘要"),
                ),
                (
                    "context_before",
                    models.TextField(blank=True, verbose_name="上下文前文"),
                ),
                (
                    "context_after",
                    models.TextField(blank=True, verbose_name="上下文后文"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "last_crawled",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后爬取时间"
                    ),
                ),
                (
                    "page_authority",
                    models.FloatField(default=0.0, verbose_name="页面权重(0-100)"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已验证"),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "待验证"),
                            ("verified_confirmed", "已确认"),
                            ("verified_false_positive", "误报"),
                            ("error", "验证失败"),
                        ],
                        default="pending",
                        max_length=25,
                        verbose_name="验证状态",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="风险级别",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发现时间"),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_sources",
                        to="content_app.plagiarismscan",
                    ),
                ),
            ],
            options={
                "db_table": "match_source",
                "ordering": ["-similarity_percent"],
            },
        ),
        migrations.AddIndex(
            model_name="plagiarismscan",
            index=models.Index(fields=["user"], name="plagiarism__user_id_5ce4d5_idx"),
        ),
        migrations.AddIndex(
            model_name="plagiarismscan",
            index=models.Index(
                fields=["text_hash"], name="plagiarism__text_ha_17bc1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismscan",
            index=models.Index(
                fields=["content_type"], name="plagiarism__content_88d050_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismscan",
            index=models.Index(
                fields=["overall_similarity"], name="plagiarism__overall_5a43fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismscan",
            index=models.Index(
                fields=["plagiarism_risk"], name="plagiarism__plagiar_85e37c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismscan",
            index=models.Index(
                fields=["-created_at"], name="plagiarism__created_3a7e4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plagiarismscan",
            index=models.Index(
                fields=["match_count"], name="plagiarism__match_c_1da080_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchsource",
            index=models.Index(fields=["scan"], name="match_sourc_scan_id_cd1a76_idx"),
        ),
        migrations.AddIndex(
            model_name="matchsource",
            index=models.Index(fields=["domain"], name="match_sourc_domain_9cce93_idx"),
        ),
        migrations.AddIndex(
            model_name="matchsource",
            index=models.Index(
                fields=["platform_type"], name="match_sourc_platfor_1f70db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchsource",
            index=models.Index(
                fields=["-similarity_percent"], name="match_sourc_similar_9e1e3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchsource",
            index=models.Index(
                fields=["match_type"], name="match_sourc_match_t_f65a91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchsource",
            index=models.Index(
                fields=["risk_level"], name="match_sourc_risk_le_f3dd32_idx"
            ),
        ),
    ]
