# Generated by Django 6.0.1 on 2026-05-31 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0019_grammarcheck_correctionsuggestion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resume_text", models.TextField(verbose_name="简历文本")),
                (
                    "resume_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="简历哈希(SHA256)"
                    ),
                ),
                (
                    "target_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="目标职位"
                    ),
                ),
                (
                    "target_industry",
                    models.CharField(
                        choices=[
                            ("tech", "互联网/IT"),
                            ("finance", "金融/投资"),
                            ("consulting", "咨询/专业服务"),
                            ("manufacturing", "制造业"),
                            ("retail", "零售/电商"),
                            ("healthcare", "医疗/健康"),
                            ("education", "教育/培训"),
                            ("media", "媒体/广告"),
                            ("real_estate", "房地产"),
                            ("logistics", "物流/供应链"),
                            ("government", "政府/公共事业"),
                            ("other", "其他行业"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="目标行业",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "应届生/入门(0-2年)"),
                            ("junior", "初级(2-5年)"),
                            ("mid", "中级(5-8年)"),
                            ("senior", "高级(8-12年)"),
                            ("executive", "高管/专家(12年+)"),
                            ("career_change", "转行/转型"),
                        ],
                        default="mid",
                        max_length=20,
                        verbose_name="经验水平",
                    ),
                ),
                (
                    "overall_score",
                    models.IntegerField(default=0, verbose_name="综合评分(0-100)"),
                ),
                (
                    "ats_score",
                    models.IntegerField(default=0, verbose_name="ATS通过率(0-100)"),
                ),
                (
                    "impact_score",
                    models.IntegerField(default=0, verbose_name="影响力得分(0-100)"),
                ),
                (
                    "clarity_score",
                    models.IntegerField(default=0, verbose_name="清晰度得分(0-100)"),
                ),
                (
                    "completeness_score",
                    models.IntegerField(default=0, verbose_name="完整度得分(0-100)"),
                ),
                (
                    "total_suggestions",
                    models.IntegerField(default=0, verbose_name="建议总数"),
                ),
                (
                    "critical_suggestions",
                    models.IntegerField(default=0, verbose_name="关键建议数"),
                ),
                (
                    "improvement_suggestions",
                    models.IntegerField(default=0, verbose_name="优化建议数"),
                ),
                (
                    "enhancement_suggestions",
                    models.IntegerField(default=0, verbose_name="增强建议数"),
                ),
                (
                    "section_analysis",
                    models.JSONField(default=dict, verbose_name="章节分析"),
                ),
                (
                    "keyword_analysis",
                    models.JSONField(default=dict, verbose_name="关键词分析"),
                ),
                (
                    "ats_compatibility",
                    models.JSONField(default=dict, verbose_name="ATS兼容性详情"),
                ),
                (
                    "salary_impact_estimate",
                    models.JSONField(default=dict, verbose_name="薪资影响预估"),
                ),
                (
                    "executive_summary",
                    models.TextField(blank=True, verbose_name="执行摘要"),
                ),
                (
                    "optimization_roadmap",
                    models.JSONField(default=list, verbose_name="优化路线图"),
                ),
                (
                    "benchmark_comparison",
                    models.JSONField(default=dict, verbose_name="行业基准对比"),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(default=0, verbose_name="处理耗时(ms)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resume_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_category",
                    models.CharField(
                        choices=[
                            ("ats_keyword", "ATS关键词优化"),
                            ("achievement_quantification", "成就量化"),
                            ("action_verbs", "动作动词升级"),
                            ("impact_language", "影响力语言"),
                            ("section_structure", "章节结构优化"),
                            ("content_clarity", "内容清晰度"),
                            ("redundancy_removal", "冗余删除"),
                            ("skill_highlighting", "技能突出"),
                            ("formatting", "格式规范"),
                            ("industry_specific", "行业特定优化"),
                            ("salary_optimization", "薪资谈判优化"),
                            ("personal_branding", "个人品牌塑造"),
                        ],
                        default="action_verbs",
                        max_length=30,
                        verbose_name="建议类别",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "关键问题"),
                            ("important", "重要改进"),
                            ("recommended", "推荐优化"),
                            ("optional", "可选增强"),
                        ],
                        default="recommended",
                        max_length=15,
                        verbose_name="重要程度",
                    ),
                ),
                (
                    "affected_section",
                    models.CharField(
                        choices=[
                            ("summary", "个人总结/求职意向"),
                            ("experience", "工作经历"),
                            ("education", "教育背景"),
                            ("skills", "技能列表"),
                            ("projects", "项目经历"),
                            ("certifications", "证书/资质"),
                            ("awards", "获奖/荣誉"),
                            ("other", "其他部分"),
                        ],
                        default="experience",
                        max_length=50,
                        verbose_name="涉及章节",
                    ),
                ),
                ("original_text", models.TextField(verbose_name="原文片段")),
                (
                    "optimized_text",
                    models.TextField(blank="", verbose_name="优化后文本"),
                ),
                (
                    "alternative_options",
                    models.JSONField(default=list, verbose_name="备选方案列表"),
                ),
                ("explanation", models.TextField(blank="", verbose_name="优化理由")),
                (
                    "impact_description",
                    models.TextField(blank="", verbose_name="预期效果描述"),
                ),
                (
                    "salary_impact_range",
                    models.CharField(
                        blank="", max_length=50, verbose_name="薪资影响范围"
                    ),
                ),
                (
                    "before_example",
                    models.TextField(blank=True, verbose_name="修改前示例"),
                ),
                (
                    "after_example",
                    models.TextField(blank=True, verbose_name="修改后示例"),
                ),
                (
                    "confidence",
                    models.FloatField(default=0.0, verbose_name="置信度(0-1)"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "简单(1分钟)"),
                            ("medium", "中等(5分钟)"),
                            ("hard", "较难(15分钟)"),
                            ("complex", "复杂(30分钟+)"),
                        ],
                        default="easy",
                        max_length=10,
                        verbose_name="实施难度",
                    ),
                ),
                (
                    "is_applied",
                    models.BooleanField(
                        null=True, verbose_name="是否应用(null=待处理)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimizations",
                        to="content_app.resumeanalysis",
                    ),
                ),
            ],
            options={
                "db_table": "optimization_suggestion",
                "ordering": ["-confidence", "-severity"],
            },
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(fields=["user"], name="resume_anal_user_id_8997d9_idx"),
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["resume_hash"], name="resume_anal_resume__ab6007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["target_industry"], name="resume_anal_target__537e03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["experience_level"], name="resume_anal_experie_fb187c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["overall_score"], name="resume_anal_overall_3b3862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["-created_at"], name="resume_anal_created_76b495_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["ats_score"], name="resume_anal_ats_sco_1272b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationsuggestion",
            index=models.Index(
                fields=["analysis"], name="optimizatio_analysi_ea9e38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationsuggestion",
            index=models.Index(
                fields=["suggestion_category"], name="optimizatio_suggest_c3a6a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationsuggestion",
            index=models.Index(
                fields=["severity"], name="optimizatio_severit_c740a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationsuggestion",
            index=models.Index(
                fields=["affected_section"], name="optimizatio_affecte_092a67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationsuggestion",
            index=models.Index(
                fields=["difficulty"], name="optimizatio_difficu_a3af27_idx"
            ),
        ),
    ]
