# Generated by Django 6.0.1 on 2026-05-31 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0020_resumeanalysis_optimizationsuggestion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=50, verbose_name="创作者昵称"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, default="", verbose_name="个人简介"),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="头像URL"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否认证创作者"),
                ),
                (
                    "verification_reason",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="认证理由"
                    ),
                ),
                (
                    "tip_enabled",
                    models.BooleanField(default=True, verbose_name="开启打赏"),
                ),
                (
                    "min_tip_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=10,
                        verbose_name="最低打赏金额(元)",
                    ),
                ),
                (
                    "suggested_amounts",
                    models.JSONField(
                        default=list,
                        help_text="如 [3, 5, 10, 20, 50]",
                        verbose_name="推荐金额列表",
                    ),
                ),
                (
                    "thank_you_message",
                    models.TextField(
                        blank=True,
                        default="谢谢你的支持！☕ 这对我意义重大！",
                        verbose_name="感谢语",
                    ),
                ),
                (
                    "custom_goal",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="筹款目标描述",
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="目标金额(元)",
                    ),
                ),
                (
                    "total_tips_count",
                    models.IntegerField(default=0, verbose_name="总打赏次数"),
                ),
                (
                    "total_tips_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总打赏金额(元)",
                    ),
                ),
                (
                    "unique_supporters",
                    models.IntegerField(default=0, verbose_name="独立支持者数"),
                ),
                (
                    "monthly_tips_count",
                    models.IntegerField(default=0, verbose_name="本月打赏次数"),
                ),
                (
                    "monthly_tips_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="本月打赏金额(元)",
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(default=dict, verbose_name="社交链接"),
                ),
                (
                    "featured_on",
                    models.JSONField(default=list, verbose_name="展示位置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "creator_profile",
            },
        ),
        migrations.CreateModel(
            name="TipDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="打赏金额(元)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="货币"),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="留言"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="匿名打赏"),
                ),
                (
                    "supporter_display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="支持者显示名",
                    ),
                ),
                (
                    "source_page",
                    models.CharField(
                        choices=[
                            ("unified_scan", "全品类检测报告"),
                            ("dual_engine", "双引擎检测报告"),
                            ("chapter_detect", "论文检测报告"),
                            ("copyscape", "抄袭检测报告"),
                            ("grammarly", "语法纠错报告"),
                            ("resume", "简历优化报告"),
                            ("anti_fraud", "反欺诈报告"),
                            ("profile", "创作者主页"),
                            ("other", "其他页面"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="来源页面",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="来源记录ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("completed", "已完成"),
                            ("failed", "支付失败"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("balance", "余额支付"),
                            ("test", "测试支付"),
                        ],
                        default="wechat",
                        max_length=30,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="交易流水号",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "creator_reply",
                    models.TextField(blank=True, default="", verbose_name="创作者回复"),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回复时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips_received",
                        to="content_app.creatorprofile",
                    ),
                ),
                (
                    "supporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tips_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tip_donation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(fields=["user"], name="creator_pro_user_id_c8646a_idx"),
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(
                fields=["is_verified"], name="creator_pro_is_veri_b0130d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(
                fields=["tip_enabled"], name="creator_pro_tip_ena_824aec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(
                fields=["-total_tips_amount"], name="creator_pro_total_t_33a019_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(
                fields=["-created_at"], name="creator_pro_created_f98f04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tipdonation",
            index=models.Index(
                fields=["creator"], name="tip_donatio_creator_f771f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tipdonation",
            index=models.Index(
                fields=["supporter"], name="tip_donatio_support_b5b087_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tipdonation",
            index=models.Index(fields=["status"], name="tip_donatio_status_9c7270_idx"),
        ),
        migrations.AddIndex(
            model_name="tipdonation",
            index=models.Index(
                fields=["-amount"], name="tip_donatio_amount_3ed23d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tipdonation",
            index=models.Index(
                fields=["source_page"], name="tip_donatio_source__42c727_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tipdonation",
            index=models.Index(
                fields=["-created_at"], name="tip_donatio_created_662d5a_idx"
            ),
        ),
    ]
