# Generated by Django 6.0.1 on 2026-06-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0021_creatorprofile_tipdonation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="xinfa_tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("industry_insight", "行业认知洞察"),
                    ("ai_security_pitfall", "AI安全避坑"),
                    ("compute_cost", "算力成本拆解"),
                    ("startup_review", "项目创业复盘"),
                    ("qa_qa", "赛道问答解惑"),
                    ("beginner_guide", "新手入门指南"),
                    ("architecture_inside", "架构干货内幕"),
                    ("", "无"),
                ],
                default="",
                help_text="Agent避坑/开发保命/企业合规/踩坑实录",
                max_length=20,
                verbose_name="心法标签",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="zone_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("industry", "行业洞察区"),
                    ("security", "安全避坑区"),
                    ("compute", "算力成本区"),
                    ("startup", "创业复盘区"),
                    ("qa", "问答解惑区"),
                    ("guide", "入门指南区"),
                    ("inside", "架构内幕区"),
                    ("", "默认"),
                ],
                default="",
                help_text="个人开发者/企业部署/多智能体/真实踩坑",
                max_length=20,
                verbose_name="Agent专区",
            ),
        ),
    ]
