# Generated by Django 6.0.1 on 2026-06-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0022_update_xinfa_zone_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                (
                    "ip_address",
                    models.GenericIPAddressField(default="", verbose_name="IP地址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="content_app.article",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章收藏",
                "verbose_name_plural": "文章收藏",
                "db_table": "content_article_favorite",
                "unique_together": {("article", "user_id", "ip_address")},
            },
        ),
    ]
