# Generated by Django 6.0.1 on 2026-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0023_articlefavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="favorite_count",
            field=models.IntegerField(default=0, verbose_name="收藏数"),
        ),
    ]
