# Generated by Django 6.0.1 on 2026-06-26 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0025_add_gallery_images"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=50, verbose_name="申请昵称"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, default="", verbose_name="个人简介"),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="为什么想成为创作者？", verbose_name="申请理由"
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="作品集链接",
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(default=dict, verbose_name="社交账号链接"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, default="", verbose_name="审核备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "creator_application",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="creator_app_user_id_4f566c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="creator_app_status_8c44ce_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="creator_app_created_55705b_idx"
                    ),
                ],
            },
        ),
    ]
