# Generated by Django 5.2.14 on 2026-05-25 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置键"
                    ),
                ),
                ("value", models.TextField(default="", verbose_name="配置值")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "文本"),
                            ("number", "数字"),
                            ("boolean", "布尔"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="值类型",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="描述"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "data_system_config",
            },
        ),
        migrations.CreateModel(
            name="DataExportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("articles", "文章数据"),
                            ("users", "用户数据"),
                            ("login_logs", "登录日志"),
                        ],
                        max_length=20,
                        verbose_name="导出类型",
                    ),
                ),
                ("file_name", models.CharField(max_length=200, verbose_name="文件名")),
                ("record_count", models.IntegerField(default=0, verbose_name="记录数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="导出时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="导出人",
                    ),
                ),
            ],
            options={
                "verbose_name": "导出记录",
                "verbose_name_plural": "导出记录",
                "db_table": "data_export_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
